3-async
MastersAcademy/frontend-course-2021 pull request #100
Opened 2021-11-03 10:35 UTC by kovalov

2021-11-04 08:57 UTC, TArch64 requested changes

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +        const title = data.body.charAt(0).toUpperCase() + data.body.slice(1);
```js
data.body.charAt(0).toUpperCase() + data.body.slice(1)
```
Тут відбувається капіталайз? Краще це винести в хелпер та використати тут

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +        const { id } = data;
ти можеш зробити деструкторизацію в аргументах
```js
createPostElement({ id, body }) {
```

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +    removePost(event) {
Якщо говорити за ООП архітектуру то тут буде більш правильно зробити клас `Post` який буде працювати конкретно з одним постом на сторінці. Він буде його рендерити та видаляти

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +        if (!this.postsContainerEl.contains(loader)) {
Зазвичай ти знаєш чи тобі потрібно показати лодер чи додати тому краще зроби 2 метода для цього і викликай потрібний. І лоігку лодера ти також можеш винести в окремий клас. App класс має використовувати тільки для відпрацювання початкової логіки, а логіка списку, поста, лодера має бути в їх власних класах

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +    toggleNotificatonMessage(textMessage) {
```suggestion
    showNotificatonMessage(textMessage) {
```

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/http.js
> +        return posts;
```suggestion
        return response.json();
```

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +            });
перемісти цю логіку в App клас. Там має бути метод який викликається в контрукторі та робить оце все

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +            });
http ти можеш передавати в конструктор App як параметр

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +window.addEventListener('DOMContentLoaded', () => {
замість цього лістенера можна просто додати атрибут defer до скріпт тега

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/index.html
> +    <script src="https://kit.fontawesome.com/a99b8e16e5.js" crossorigin="anonymous"></script>
цей скріпт точно має бути в хеді? Він точно має блочити відмалювання всієї сторінки до тих під поки не завантажеться та не виконається?

2021-11-04 08:57 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/index.html
> +                            class="button__icon fas fa-trash-alt fa-2x" data-delete-button-icon></i></button>
пофіки форматування цього файлу. Постав де потрібно переноси рядки та повирівнюй пробілами

2021-11-04 11:21 UTC, kovalov commented on homeworks/vladyslav.kovalov_kovalov/3-async/index.html
> +    <script src="https://kit.fontawesome.com/a99b8e16e5.js" crossorigin="anonymous"></script>
Да. В документации указано именно такое расположение [https://fontawesome.com/kits/a99b8e16e5/use](url)

2021-11-05 13:36 UTC, TArch64 requested changes

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +    notification.show();
ця логіка має бути методом класу `Notification`. Це частина логіки цього класу і вона має бути там

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +        const path = `${this.url}/${postId}`;
Винесення методів із запитами було хорошим рішенням. Я б повернув назад той класік, але тут потрібно трохи підправити
```js
class HTTP {
  getPosts(){}
  deletePost() {}
}

class App {
    constructor(http) {
      this.http = http;
    }

    getPosts() {
       return this.http.getPosts();
    }
}
```

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +            }
```suggestion
            const isVisible = title.toLowerCase().includes(text)
            postEl.classList.toggle('display-none', !isVisible);
```

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +    event.preventDefault();
```js
event.preventDefault();
```
зазвичай викликають на початку

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +            .then()
пустий then не потрібен тут

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/index.html
> +                        data-button-sort-icon></i></button>
Пофікси форматування цього файлу. Один рядок = один тег. Також якщо починаєш переносити атрибути на новий рядок то всі атрибути мають бути перенесені. Або перенось всі або не перенось їх взагалі

```suggestion
                <button class="actions-container__button actions-section__button button button--sort" data-button-sort>
                    Sort
                    <i class="button__icon fas fa-sort-amount-up-alt" data-button-sort-icon></i>
                </button>
```

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/loader.js
> +    }
```suggestion
    show() {
        const content = this.templateElement.content.cloneNode(true);
        const element = content.querySelector('[data-loader]');
        this.containerEl.append(element);
    }
```

і `display-none` можна не вішати. Ти всеодно видаляєш його з дома по закінченню завантаження

2021-11-05 13:36 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/post.js
> +    }
```suggestion
    render() {
        const element = this.templateEl.content.cloneNode(true);
        element.querySelector('[data-post-title]').textContent = this.capitalizeString(this.title);
        element.querySelector('[data-post-body]').textContent = this.capitalizeString(this.body);
        element.querySelector('[data-post]').dataset.id = this.id;
        this.containerEl.append(element);
    }
```

2021-11-05 13:38 UTC, TArch64 commented
Немає фовер стейту і цієї кнопки. Всі інтерактивні елементи мають мати ховер та фокус стейт + на кнопки зазвичай додають cursor pointer

![image](https://user-images.githubusercontent.com/29049264/140519046-8466d3d0-b59c-4c22-b738-5a299ba40010.png)

2021-11-05 15:22 UTC, TArch64 approved these changes

2021-11-05 15:22 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +        return this.http.deletePost();
А ти перевіряв чи працює видалення?) тут в тебе id для видалення поста не працює

2021-11-05 15:24 UTC, merged

2021-11-05 15:27 UTC, kovalov commented on homeworks/vladyslav.kovalov_kovalov/3-async/app.js
> +        return this.http.deletePost();
Исправил ` deletePost(postId) {}`