3-async/Base implementation
MastersAcademy/frontend-course-2021 pull request #102
Opened 2021-11-04 09:29 UTC by svkul

2021-11-04 12:28 UTC, svkul commented
https://svkul.github.io/frontend-course-2021/homeworks/serhii.kulakivskyi_svkul/3-async/

2021-11-04 18:12 UTC, electrovladyslav requested changes

2021-11-04 18:12 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +                await await fetch(`https://jsonplaceholder.typicode.com/posts/${postId}`, {
Вот, тем более, ты этот урл используешь больше чем один раз. 100% надо в константу вынести как какой-нибудь `BASE_URL`

2021-11-04 18:12 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +            const postId = isPostDeleteBtn.dataset.postDelete;
Я бы вынес эту логику в функцию `deletePost`
Обычно так и делают: 
- в самом обработчике оставляют логику которая относится конкретно к обработчику - какая кнопка была нажата, или как здесь у тебя на корзинку ли кликнули;
- а логику которая относится к другим частям приложения выносят в функции, которые красивенько называют и вызывают в обработчике.

2021-11-04 18:12 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +        const isPostDeleteBtn = e.target.closest('[data-post-delete');
Делегирование - 👍

2021-11-04 18:12 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +        const { value } = e.target;
👍

2021-11-05 06:31 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/documentClick.js
> +document.addEventListener('click', (e) => {
Тут на самом деле возможна логика не только по селекту, поэтому это вынесено в отдельный файл.

2021-11-05 06:50 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    (async () => {
Просто чтобы не писать:
const init = async () => {...};
init();

2021-11-05 06:52 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +                text: 'Sort',
+

2021-11-05 06:54 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +                await await fetch(`https://jsonplaceholder.typicode.com/posts/${postId}`, {
Второй await - опечатка.
BASE_URL - :white_check_mark:

2021-11-05 06:56 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +(() => {
Вынес самовызывающуюся функцию в низ

2021-11-05 06:57 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +(() => {
Первая самовызывающаяся функция чисто для того чтобы ограничить скоуп.

2021-11-05 07:00 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +            const postId = isPostDeleteBtn.dataset.postDelete;
✅

2021-11-05 09:23 UTC, electrovladyslav requested changes

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/documentClick.js
> +document.addEventListener('click', (e) => {
Что это за аккордеон? Он есть только в этом файле. В разметке его нет. Зачем тогда он здесь?
Удали всё что его касается отсюда.

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/documentClick.js
> +document.addEventListener('click', (e) => {
Я хочу, чтобы ты держал логику, которая касается селекта в одном месте. 
По хорошему, закрытие селекта по клику на свободную область документа - это основная функциональность селекта. Потому, место ей в файле customSelect.js в методе initListeners.
Если ты не хочешь лезть в этот файл (который ты видимо где-то скачал и положил в свой проект), то помести эту логику к иниту селекта в своём файле.
Первый вариант предпочтительнее.

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +(() => {
Ограничить скоуп - это хорошо. 
Непонятно, где точка входа в твой скрипт? Откуда всё начинается. 
Если ты пишешь в таком императивном ("функциональном") стиле, надо сделать явный инит, в котором будут только вызовы других функций. Вроде того, что происходит в конструкторе Селекта https://github.com/MastersAcademy/frontend-course-2021/pull/102/files#diff-4823697e37daa99f19cf05986e075154150acfa4141353e49c815e61decea5d8R12

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    select.render();
вот это надо вынести в инит

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    (async () => {
зачем ты пишешь async () => {... 
Какой смысл в этом async?

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    (async () => {
Эту функцию можно назвать initLayout например, и тоже вызывать в ините.

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +            await new Promise((res) => setTimeout(res, 3000));
Зачем это? Ты делаешь задержку чтобы посты приехали? Если да, то
1. Нет смысла оборачивать таймаут в промис.
2. На следующих двух строках ты ждёшь, пока они приедут. В этой задержке нет смысла.
_Опционально: можешь не исправлять._

2021-11-05 09:23 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    function showMessage(type, text) {
Хорошим тоном считается написание консистентного кода: если ты используешь стрелочные функции, то используй их везде. 
А такое объявление функции (function declaration) нужно для создания своего контекста. Ты же в ней не обращаешься к `this`? Значит её тоже можно переписать на стрелочную.
_Опционально: можешь не исправлять._

2021-11-05 09:29 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +            await new Promise((res) => setTimeout(res, 3000));
А, сорян, это по заданию так надо.

2021-11-05 09:41 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    function postLayout(data) {
Название функции должно начинаться с глагола. Я бы добавил get в начало названия. 
А то получается, что это функция, которая постит где-то какую-то разметку
_Опционально: можешь не исправлять._

2021-11-05 09:53 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/documentClick.js
> +document.addEventListener('click', (e) => {
> Что это за аккордеон? Он есть только в этом файле. В разметке его нет. Зачем тогда он здесь? Удали всё что его касается отсюда.

Это пример что в этом месте может быть логика по сокрытию других компонентов. И чтобы не вещать доп. обработчики кликов на document это делается в одном месте.

2021-11-05 09:55 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/documentClick.js
> +document.addEventListener('click', (e) => {
> Если ты не хочешь лезть в этот файл (который ты видимо где-то скачал и положил в свой проект)

К чему это вообще??? Я нигде ничего не качал! Выше описана причина почему сделал именно так.

2021-11-05 09:57 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    (async () => {
> зачем ты пишешь async () => {... Какой смысл в этом async?

Внутри функции есть await

2021-11-05 11:24 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/documentClick.js
> +document.addEventListener('click', (e) => {
> К чему это вообще??? Я нигде ничего не качал!
Я так решил, потому что файл customSelect.js  написан классом, а файл index.js в фунциональном стиле.
Если это твой файл, тогда тем более добавь это туда. 
Плюс ты используешь захардкодженые название css-классов в разных файлах. Это черевато тем, что имя цсс-класса поменяется в одном месте, а про второе место забудут, и там эта логика сломается. 
Потому пусть лучше будут в одном месте.

2021-11-05 11:26 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/index.js
> +    (async () => {
Точняк

2021-11-05 11:28 UTC, electrovladyslav commented on homeworks/serhii.kulakivskyi_svkul/3-async/src/js/documentClick.js
> +document.addEventListener('click', (e) => {
А аккордеона у тебя же нет, потому следует удалить всё, что с ним связано из этого файла. 
Если бы был, то логику по его закрытию тоже следовало поместить в файл, с основной логикой аккордеона.

2021-11-05 12:52 UTC, merged