3 async
MastersAcademy/frontend-course-2021 pull request #103
Opened 2021-11-04 14:52 UTC by Chakipaki

Without sort and filter
This 1st version

2021-11-05 07:11 UTC, Chakipaki commented
Add sort, delete post  options

2021-11-05 09:46 UTC, electrovladyslav commented
Это бы сильно облегчило мою работу

> Також було б класно якби всі налаштували собі в репозиторіях GitHub Pages (з наступної домашки то буде обовʼязково) https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source
> Потрібно включити це в сетінгах та відкрити по потрібній вам url

2021-11-05 10:10 UTC, Chakipaki commented
https://chakipaki.github.io/home3-async/

2021-11-05 11:13 UTC, electrovladyslav requested changes

2021-11-05 11:13 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +async function requestPostsAZ(url) {
Видимо из-за этого запроса ломается совместная работа фильтра и сортировки 
Здесь я сначала ввёл название, потом изменил сортировку, и фильтрация сломалась.
![image](https://user-images.githubusercontent.com/7540757/140500741-de04055f-0981-4c6e-9d2c-63b0ab5c8cbb.png)

2021-11-05 11:13 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/index.html
> +                        <option data-sorting-def selected value="sort">sort</option>
Здесь укажи, что это значение по умолчанию: `unsorted` / `default`

2021-11-05 11:13 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/index.html
> +                        <option data-sorting-AtZ value="A__to__Z">A to Z</option>
тут лучше использовать один дата атрибут с разными значениями, [типовыми](https://kb.blackbaud.com/knowledgebase/Article/117098)
- `data-sorting="ASC"` 
- `data-sorting="DESC"`

2021-11-05 11:13 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +    if (sorting.value === 'A__to__Z') {
если ты проверяешь одну переменную несколько раз -  используй [switch](https://learn.javascript.ru/switch)

2021-11-05 11:13 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +    for (let i = 0; i < content.length; i++) {
везде, где можно избежать цикла - избегай его в пользу [встроенных методов работы с массивами](https://learn.javascript.ru/array-methods#preobrazovanie-massiva)
Тут, например, идеально заюзать [forEach](https://learn.javascript.ru/array-methods#perebor-foreach) со стрелочной фунцией
```
posts.forEach((post) => someAction(post))
```

2021-11-05 14:33 UTC, Chakipaki commented
https://chakipaki.github.io/home3-async/

2021-11-05 17:23 UTC, electrovladyslav commented
Всё ещё сломана совместная работа фильтров и сортировки https://github.com/MastersAcademy/frontend-course-2021/pull/103#discussion_r743565914

2021-11-05 17:28 UTC, electrovladyslav requested changes

2021-11-05 17:28 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/index.html
> +                        <option data-sort='AtoZ' -AtZ value="AtoZ">A to Z</option>
`-Atz` потерялась - удали

2021-11-05 17:28 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/style.css
> +  position: absolute;
Тут же по дизайну картинка корзины должна быть.
Её можно импортировать из [фигмы](https://www.figma.com/file/UZb1G4rilTZO6Y1l6xMZcl/3-async?node-id=0%3A1) и засунуть сюда бэкграундом, например.
_Опционально - можешь не исправлять_
![image](https://user-images.githubusercontent.com/7540757/140550885-f1fd3dbc-19c8-48be-89bb-0c5303251626.png)

2021-11-05 17:28 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +    content.forEach((el) => {
Поменяй всё же `content` на `posts`.
Название переменной должно отражать то, что в ней храниться. 
Так как это массив, то переменная должна называться множественным числом. 
Если ты перебираешь этот массив, то на каждой итерации форИча у тебя будет элемет этого массива, пост. 
Ведь гораздо понятнее читать
```
postMarkupPost(post.id, post.title, post.body);
```

2021-11-05 17:28 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +function deletePost() {
У тебя функция удалитьПост навешивает обработчик, в котором и пост удаляется, и показывается сообщение. 
Назови эту функцию `addDeleteSupport` например, и внутри разбей логику на две функции - удалитьПост и показатьСообщение

2021-11-05 17:28 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +                blog.removeChild(e.target.parentElement.parentElement);
На лекции говорили, что так делать не очень хорошо. В разметке ты добавишь ещё один враппер, и у тебя сломается эта логика. 
Ищи конкретный элемент для удаления, через `closest` например.
_Опционально - можешь не исправлять_

2021-11-05 17:28 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +                blog.removeChild(e.target.parentElement.parentElement);
Также по заданию надо отправлять запрос для удаления поста и обрабатывать его, для проверки ошибок https://github.com/MastersAcademy/frontend-course-2021/issues/99#issue-1042758805
_Опционально - можешь не исправлять_

2021-11-05 17:52 UTC, Chakipaki commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +                blog.removeChild(e.target.parentElement.parentElement);
Я не смог сделать совместную роботу фильтра и сортировки, перепробовал много, так и не смог

2021-11-05 20:38 UTC, Chakipaki commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +                blog.removeChild(e.target.parentElement.parentElement);
Попробую сделать завтра  до 12, не мержайте пока пожалуйста))

2021-11-06 09:53 UTC, electrovladyslav requested changes

2021-11-06 09:53 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +    const deleteMessege = document.createElement('div');
Эту строчку надо поместить в функцию presentMessage, как и строки 63-65. 
Тогда эта функция не будет зависеть от внешних переменных, и её можно будет вынести наружу. 
Вообще объявлять одну функцию внутри другой - не очень хорошая практика. Нужно стремиться к тому, чтобы каждая функция была независима и делала свой маленький кусочек работы. Иначе получается [спагетти-код](https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B0%D0%B3%D0%B5%D1%82%D1%82%D0%B8-%D0%BA%D0%BE%D0%B4)

2021-11-06 09:53 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +    filtering.oninput = (e) => {
Замени на addEventListener

2021-11-06 09:53 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +            await filter();
Эти две функции тоже делают не то, что написано в их названии. Они накидывают обработчики.

2021-11-06 09:53 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +        async function initialization() {
Эту функцию тоже стоит вынести из родительской. И назвать например `attachHandlers`. И в ней только добавить обработчики. А в этих обработчиках уже связать логику ввода текста в инпут/выбор селекта и фильтрацию/сортировку.

2021-11-06 09:55 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +                blog.removeChild(e.target.parentElement.parentElement);
Надо, чтобы у тебя были отделные функции фильтрации постов и для их сортировки. И они должны вызываться и когда вводишь текст и когда выбирает в селекте сортировку.
И лучше всего будет, если эти функции будут принимать посты как параметр, и возвращать отфильтрованные/отсортированные посты. Которые ты будешь показывть на странице в следующей функции.

2021-11-06 10:07 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +                blog.removeChild(e.target.parentElement.parentElement);
Всё нормально, у тебя ещё целые выходные впереди.

2021-11-06 11:41 UTC, Chakipaki commented
https://chakipaki.github.io/home3-async/

2021-11-06 13:05 UTC, Chakipaki commented
https://chakipaki.github.io/home3-async/
Maybe final commit))

2021-11-07 10:16 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +    const deleteMessege = document.createElement('div');
Супер. 
Ну и название у этой функции должно быть более явное, например `showDeleteMessage`

2021-11-07 10:19 UTC, electrovladyslav commented on homeworks/ivan.bieliaiev_Ckakipaki/3-async/app.js
> +function filteringElemets(value) {
`ing` - можно отбросить, и назвать, например, `filterPosts` - раз ты в самой функции завязываешься на посты.

2021-11-07 10:22 UTC, electrovladyslav approved these changes

2021-11-07 10:23 UTC, merged

2021-11-07 10:23 UTC, electrovladyslav commented
Молодец!

2021-11-07 16:13 UTC, Chakipaki commented
Спасибо, всё благодаря вам)))

> 7 нояб. 2021 г., в 12:23, Yermolin Vladyslav ***@***.***> написал(а):
> 
>