3 async
MastersAcademy/frontend-course-2021 pull request #105
Opened 2021-11-04 21:11 UTC by ConstBagel

2021-11-05 12:07 UTC, MZabolotnev requested changes
![image](https://user-images.githubusercontent.com/25617217/140507951-13c7a47d-7cdc-4d21-9409-53702118a8c0.png)
Инпуты не соответствуют дизайну

2021-11-05 12:07 UTC, MZabolotnev commented on homeworks/kostya.bublyk_ConstBagel/3-async/index.html
> +              Sort
![image](https://user-images.githubusercontent.com/25617217/140507791-ebc71831-8114-4307-a8d4-3db1c4e0ccfb.png)
А что в данном контексте означает опция Sort?

2021-11-05 19:25 UTC, ConstDev commented on homeworks/kostya.bublyk_ConstBagel/3-async/index.html
> +              Sort
там в задании было:
Sorting has 3 options:
a. Initial version (without sorting)
b. Sort from A to Z
c. Sort from Z to A

Думал, что Sort как Initial version

2021-11-05 19:26 UTC, ConstDev commented
> ![image](https://user-images.githubusercontent.com/25617217/140507951-13c7a47d-7cdc-4d21-9409-53702118a8c0.png) Инпуты не соответствуют дизайну

А что конкретно нужно изменить. Сортинг?

2021-11-07 10:26 UTC, MZabolotnev commented on homeworks/kostya.bublyk_ConstBagel/3-async/index.html
> +              Sort
Sort - это ж означает сортировка? Немного коньюзит как пользователя , почему Sort = Initial version (without sorting)Но в целом это не критично

2021-11-07 10:26 UTC, MZabolotnev approved these changes

2021-11-07 10:31 UTC, merged