v1
MastersAcademy/frontend-course-2021 pull request #106
Opened 2021-11-04 23:07 UTC by AndriiMorozov88

2021-11-05 13:45 UTC, TArch64 commented
Пиши комміт меседжі так щоб по ним можна було зрозуміти що там за зміни

2021-11-05 13:46 UTC, TArch64 commented
Додай лінк на гітхаб пейджес 

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

2021-11-05 13:48 UTC, TArch64 requested changes

2021-11-05 13:48 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/script_blog.js
> +            data.sort((a, b) => (a.title > b.title ? 1 : -1));
fetchDataA повторюється 4 рази. Зроби це більш оптимальним шляхом

2021-11-05 13:48 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/script_blog.js
> +    if (event.key === 'Enter') {
використай для сорчу івенти форми

2021-11-05 13:48 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/style_blog.css
> +.blog_filter {
це класи написані по бему чи ні?

2021-11-05 16:06 UTC, AndriiMorozov88 commented
> Додай лінк на гітхаб пейджес
> 
> https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

Сделал

2021-11-05 19:19 UTC, TArch64 commented
> > Додай лінк на гітхаб пейджес
> > https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source
> 
> Сделал

Прикріпи лінку на html файл домашки в коммент

2021-11-06 11:14 UTC, AndriiMorozov88 commented
> > > Добавить лінк на гітхаб пейджес 
> > > [https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a -publishing-source](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source)
> > 
> > 
> > Сделал
> 
> Прикріпи лінку на html файл домашки в коммент

2021-11-07 14:02 UTC, TArch64 commented
1. Пофікси еррори лінтерів
2. Комміт меседжі завджи пишуться на англійській. Точно так же як назви зміних, файлів, комментарів у коді

2021-11-07 14:02 UTC, TArch64 commented
Додай лінк на гітхаб пейджес

2021-11-07 14:05 UTC, TArch64 requested changes

2021-11-07 14:05 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/script_blog.js
> +        blogContainer.append(blogElement);
Частина коду у функціях sort... дублюється 3 рази

2021-11-07 14:05 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/style_blog.css
> +.blog_filter-filter {
Назви класи по БЕМу

2021-11-07 14:05 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/style_blog.css
> +.blog_filter-filter {
`blog_filter-filter` -- слово фільтр 2 рази в назві класу

2021-11-08 07:54 UTC, TArch64 commented
@AndriiMorozov88 ping-ping

2021-11-08 13:02 UTC, TArch64 requested changes
Пофікси еррори лінтерів

2021-11-08 13:02 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/script_blog.js
> +        const blogElement = document.createElement('div');
якщо функція називається `createBlogEl` то вона має **тільки** створювати елементи блога. Сортування в ній не має буть взагалі. Як і завантаження даних

2021-11-08 16:36 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/script_blog.js
> +async function filter(event) {
```suggestion
form.addEventListener('submit', async (event) => {
```

2021-11-08 19:36 UTC, TArch64 approved these changes

2021-11-08 19:36 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/script_blog.js
> +}
ці 3 функції мають повністю однаковий код всередині. Їх можна замінити на одну

2021-11-08 19:36 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/3-async/script_blog.js
> +    }
Код цієї функції та createSortBlogEl майже повністю дублюють одна одну. Такі речі як відмалювання постів та сортування можна винести в окремі функції та викликати їх тут

2021-11-08 19:38 UTC, merged