3-async
MastersAcademy/frontend-course-2021 pull request #109
Opened 2021-11-05 01:00 UTC by SanSandru4

2021-11-05 13:39 UTC, TArch64 commented
Пофікси еррори лінтерів

2021-11-06 13:13 UTC, TArch64 commented
@SanSandru4 Пиши людсько зрозумілі меседжі коммітів. По цьому кусочку текста має бути зрозуміло які зміни робилися в коммітови не відкриваючи цей комміт.

Ти зможеш сказати які тут були зміни не дивлячись в код? А через рік - два?
![image](https://user-images.githubusercontent.com/29049264/140610921-1dd7e852-488d-4f41-89ec-232bf4ccb107.png)

2021-11-06 13:29 UTC, SanSandru4 commented
То, все правки - кількість пробілів, довжина строки і томі подібне

2021-11-06 13:40 UTC, TArch64 commented
> То, все правки - кількість пробілів, довжина строки і томі подібне

Але в цих змінах також мають свою назву. Чому просто не написати `Fixed indentation in js` чи `Fixed too long lines in js`?

2021-11-06 13:49 UTC, SanSandru4 commented
ок, я буду старатися так і робити, але вже просто окот тіпає, я його правлю, а мені прилітає шось нове. Мабуть треба відпочити, але немає коли(((

2021-11-06 13:51 UTC, TArch64 commented
> ок, я буду старатися так і робити, але вже просто окот тіпає, я його правлю, а мені прилітає шось нове. Мабуть треба відпочити, але немає коли(((

А чому ти локально не запускаєш? Тобі ж не обов‘язково пушити постійно на гітхаб

2021-11-06 13:56 UTC, SanSandru4 commented
у мене ноут слабенький, боюся що буду сидіти по години чекати поки все прогрузиться і перевіриться(((

2021-11-06 14:01 UTC, TArch64 commented
> у мене ноут слабенький, боюся що буду сидіти по години чекати поки все прогрузиться і перевіриться(((

Так це ж взагалі не діло. Ти так помилки в сліпу не нафіксиш. Да і ресурсів там потрібно не багато. Якщо у тебе зараз з цим проблеми то я не знаю як ти будеш піднімати ангуляр

прожени в руті проекта `npm install`. Як зробиш це то далі можна будн командою `npm run test:js` Запускати лінтер

2021-11-06 14:08 UTC, SanSandru4 commented
Під новий рік у мене новий ноут буде, а покищо мучаюся на цьому. Дякую за підказки

2021-11-06 15:53 UTC, TArch64 commented on package-lock.json
> +    "packages": {
Відміни зміни в цьому файлику

2021-11-06 16:03 UTC, TArch64 requested changes
Додай лінк на гітхаб пейджес

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

2021-11-06 16:03 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/index.html
> +        <header class="blog-header" data-blog-header>
Зроби назви класів по бему

2021-11-06 16:03 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +let postStr = '';
для чого ця змінна?

2021-11-06 16:03 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +const blogMsg = document.querySelector('[data-blog-msg]');
додавай до зміних в яких лежать елементи дому закінчення `El`

2021-11-06 16:04 UTC, SanSandru4 commented on package-lock.json
> +    "packages": {
Тарас, а як відмінити зміни?

2021-11-06 16:05 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/style.css
> +}
ні

2021-11-06 17:52 UTC, SanSandru4 commented
https://sansandru4.github.io/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/3-async/

2021-11-07 14:05 UTC, TArch64 commented on package-lock.json
> +    "packages": {
Можеш просто знайти оригінальний файл і підкинути його собі

2021-11-07 14:06 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/style.css
> +}
Потрібно поставити. А також eslint та stylelint плагіни

2021-11-07 14:10 UTC, TArch64 requested changes

2021-11-07 14:10 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/index.html
> +    <section class="block_blog" data-block>
1. У назвах блоків не пишуть слово блок
2. елемент від блока відділяється за допомогою `__`

2021-11-07 14:10 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/index.html
> +            <div class="blog_logo">BLOG</div>
В класі елементів обовʼязково має бути в назва блоку. Якщо в тебе є блок `header` то в нього лого елемент буде називатися `header__logo`

2021-11-07 14:10 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/index.html
> +            <div class="blog_logo">BLOG</div>
Перепиши всі класи так

2021-11-07 14:10 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +    postTitle.innerHTML = bTitle;
пости мають рендеритися через тег `<template>`

2021-11-07 15:13 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/index.html
> +        <ol class="blog__msg">
`ol` це тег який робить впорядкований список (такий де 1,2,3,4 зліва написано). Ти точно його хочеш використати для поста?

2021-11-07 15:14 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +    const postBody = cloneTemplate.querySelector('p');
Зробити ці селектори через дата атрибути

2021-11-07 15:14 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +        render(`${blog[i].title}`, `${blog[i].body}`);
Для чого косі завички навколо аргументів?

2021-11-07 15:14 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +    for (let i = 0; i < blog.length; i++) {
заміни цей цикл на `forEach`

2021-11-07 15:15 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +function showPost(blog) {
`showPost` це назва функції яка показує **один** пост, а тут у тебе їх багато. Має бути множина в назві

2021-11-07 15:15 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +    .catch(console.log('Error!'));
У тебе `console.log('Error!')` викликається при відкритті сторінки навіть якщо не було помилки

2021-11-07 21:29 UTC, TArch64 submitted a review, later dismissed
Ці комменти що написав опціональні і можна їх не фіксити, а просто прочитати і подумати. Як відміниш зміни в `package-lock.json` замержу

2021-11-07 21:29 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/index.html
> +        <li class="blog__msg">
Було б більш доречно назвати це клас post. Бо його елементи є, а блока нема
```suggestion
        <li class="post">
```

2021-11-07 21:29 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +function render(bTitle, bBody) {
Що означають `b` на початку? Чому не можна без них? Не скорочуй назви. Економити декілька символів тут нічим не допоможе. до того ж потім всеодно якийсь uglify чи terser цей код переформатить

2021-11-07 21:29 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +    });
```suggestion
    posts.forEach(({ title, body }) => render(title, body));
```

2021-11-07 21:29 UTC, TArch64 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +            if (`${sortPostEl.value}` === 'No sort') {
чому скрізь косі кавички в коді? Чому не можна просто `sortPostEl.value`? Для чого додатково поле типу `string` обертати в стрінгу? Воно нічого не робить крім дивного коду і додаткових операцій в браузері

2021-11-07 22:42 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/3-async/script.js
> +            if (`${sortPostEl.value}` === 'No sort') {
ДЯкую за всі правки прийму до уваги і постараюсь більше не тупить)

2021-11-08 07:34 UTC, TArch64 approved these changes

2021-11-08 07:52 UTC, merged