3-sync-first-commit
MastersAcademy/frontend-course-2021 pull request #110
Opened 2021-11-05 08:45 UTC by MaksymSelenkov

2021-11-05 08:52 UTC, MaksymSelenkov commented
sortInitial and filterData dont work. I am finding a resolve, why it doesnt work?

2021-11-05 15:43 UTC, TArch64 requested changes

2021-11-05 15:43 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +                text.classList.add('blog__content-post-text');
створюй новий елемент поста через тег template

2021-11-05 15:43 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +window.addEventListener('load', () => {
заміни load на `defer` атрибут у скріпта

2021-11-05 15:43 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +            const posts = await response.json();
винеси ці всі функцію за межі таймаута і викликай тут якусь функцію

2021-11-05 15:43 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +            const posts = await response.json();
Чим менше тим вкладеностей в коді тим простіше його читати

2021-11-05 15:43 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +const sortAsc = document.querySelector('[data-sort-ascending]');
Додай до констант в яких лежать елементи дому закінчення `El`

2021-11-05 15:43 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/index.html
> +                <div class="blog__header-sort">
тут потрібно додати ще блоків. На сторінці є окремі частини контенту які також можна виділити як блок

2021-11-05 15:43 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/style.css
> +  width: 992px;
замість жорстких розмірів контенту краще роби `max-width` та `width: 100%`. Тоді не буде горизонтального скролу на менших девайсах

2021-11-06 09:03 UTC, MaksymSelenkov commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +                text.classList.add('blog__content-post-text');
+

2021-11-06 09:04 UTC, MaksymSelenkov commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +window.addEventListener('load', () => {
якщо змінити івент на дефер то лоадер не зникає і пости не рендеряться

2021-11-06 09:05 UTC, MaksymSelenkov commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +            const posts = await response.json();
пробував, все працює, але лінтер не пропускає: функції використовуються до їх оголошення.

2021-11-06 09:06 UTC, MaksymSelenkov commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/index.html
> +                <div class="blog__header-sort">
не зрозумів

2021-11-06 13:05 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/index.html
> +                <div class="blog__header-sort">
У тебе всі класи є елементами блока blog. Розбий твою структуру класів на ще додаткові блоки. Це може бути навігація, пост, пошук etc

2021-11-06 13:07 UTC, TArch64 commented
Роби на фікс кожного коментаря окремий комміт. Комміти мають бути невиличками частинами змін твого проекту і уникай коммітів з меседжами типу `3-async-first-fixed`. По меседжу комміта має бути зрозуміло які ти робив зміни не відкриваючи його

2021-11-06 13:07 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +            const posts = await response.json();
То зміни їх порядок) Спочатку декларація функцій, а потім їх використання

2021-11-06 13:08 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +window.addEventListener('load', () => {
а лістенер на load ти видаляв? Помилки в консолі є?

2021-11-06 13:10 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +            posts.map((item) => {
map має використовувати тільки для перетворення даних. а тут ти його використовуєш замість forEach. Почитай в чому їх різниця і коли що потрібно використовувати

2021-11-06 13:11 UTC, TArch64 commented
Додай лінк на гітхаб пейджес

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

2021-11-07 07:32 UTC, MaksymSelenkov commented
https://maksymselenkov.github.io/frontend-course-2021//homeworks/maksym.selenkov_MaksymSelenkov/3-async/index.html

2021-11-07 09:09 UTC, MaksymSelenkov commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/app.js
> +window.addEventListener('load', () => {
window load видалив, додав дефер у тег скріпт

2021-11-07 14:12 UTC, TArch64 commented
Не відповідає дизайну. Потрібно зробити так як там намальовано

![image](https://user-images.githubusercontent.com/29049264/140648575-347a0e70-9c31-4d98-9961-8370c1ad5a5a.png)

2021-11-07 14:14 UTC, TArch64 commented
Лодер занадто великий та піксельний. Зменши його та знайди імедж з більшим резолюшином
![image](https://user-images.githubusercontent.com/29049264/140648635-230c5c62-de43-43bd-a248-36701de398f8.png)

2021-11-07 14:15 UTC, TArch64 commented
Використовуй, коли можна, браузерні дропдауни. Кастомний це окрема розмова як його робити щоб він був адекватним і ним не больно було користовуватися. У браузера є тег `<select>` то його і використовуй

![image](https://user-images.githubusercontent.com/29049264/140648697-8ffa20c1-ed05-40c1-87d6-ac4f87922f87.png)

2021-11-07 14:20 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/style.css
> +.blog__header-sort-content a {
не використовуй теги як селектори

2021-11-07 14:20 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/index.html
> +                        <a href="#" data-sort-descending>A-Z</a>
Якщо робити кнопку то в 95% випадків це має бути тег `<button>`. Почитай коли потрібно використовувати лінку а коли кнопку

2021-11-07 14:20 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/index.html
> +                    <div class="blog__header-sort-content">
чому це елемент blog а не sort?

2021-11-07 14:20 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/style.css
> +.blog__header-sort:hover .blog__header-sort-content {
перенеси стилі які відносяться до контролу сортування в клас `sort` а не `blog__header-sort`. В останньому має бути лише те що відноситься до позиціювання сортування в лаяуті

2021-11-07 14:20 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/style.css
> +.blog__content-post {
Більш логічно було назвати цей клас `post` бо його елементи є, а самого класу поста немає. До того ж це стилі власне поста, а не його позиціювання

2021-11-07 14:20 UTC, TArch64 commented on homeworks/maksym.selenkov_MaksymSelenkov/3-async/style.css
> +  flex-wrap: wrap;
зроби тут через grid

2021-11-08 07:54 UTC, TArch64 commented
@MaksymSelenkov ping-ping

2021-11-08 13:03 UTC, TArch64 approved these changes

2021-11-08 13:10 UTC, merged