3-async
MastersAcademy/frontend-course-2021 pull request #112
Opened 2021-11-05 09:26 UTC by Vladimior

https://vladimior.github.io/frontend-course-2021/homeworks/volodymyr.khrushch_Vladimior/3-async/index.html

2021-11-05 14:56 UTC, Vladimior commented
> Пофікси еррори лінтерів
на данний момент я не знаю як його пофіксити, я пробував багато варіантів. переписував по іншому фукцію, писав ось так. і все рівно вивалює таку помилку. я весь час сиджу читаю доки, дивлюсь як виправити.  `const filter = function () {
    const input = document.querySelector('[data-input]');

    input.addEventListener('keyup', () => {
        const filters = input.value.toLowerCase();
        const filterElements = container.querySelectorAll('[data-title]');

        filterElements.forEach((item) => {
            if (item.innerHTML.toLowerCase().indexOf(filters) > -1) {
                item.closest('[data-card]').style.display = '';
            } else {
                item.closest('[data-card]').style.display = 'none';
            }
        });`

2021-11-05 15:15 UTC, TArch64 commented
> > Пофікси еррори лінтерів
> > на данний момент я не знаю як його пофіксити, я пробував багато варіантів. переписував по іншому фукцію, писав ось так. і все рівно вивалює таку помилку. я весь час сиджу читаю доки, дивлюсь як виправити.  `const filter = function () {
> > const input = document.querySelector('[data-input]');
> 
> ```
> input.addEventListener('keyup', () => {
>     const filters = input.value.toLowerCase();
>     const filterElements = container.querySelectorAll('[data-title]');
> 
>     filterElements.forEach((item) => {
>         if (item.innerHTML.toLowerCase().indexOf(filters) > -1) {
>             item.closest('[data-card]').style.display = '';
>         } else {
>             item.closest('[data-card]').style.display = 'none';
>         }
>     });`
> ```

Пробема в тому що ти всередині функції змінюєш поле аргумента, що наш лінтер забороняє. Підправив правило щоб так можна було робити

2021-11-05 15:20 UTC, Vladimior commented
дякую. 
"Пробема в тому що ти всередині функції змінюєш поле аргумента, що наш лінтер забороняє.", постараюсь десь почитати чому так не бажано робити.

2021-11-06 13:20 UTC, TArch64 commented
Виконання не повністю відповідає дизайну 
![image](https://user-images.githubusercontent.com/29049264/140611163-dfc2b085-6a56-4af0-8dde-84b1963820ae.png)

2021-11-06 13:21 UTC, TArch64 commented
В полі сьорчу немає відступів зправа та зліва 
![image](https://user-images.githubusercontent.com/29049264/140611190-ddcc32ea-1181-4e5a-b6f2-81f10a1e29d9.png)

2021-11-06 13:28 UTC, TArch64 commented
Там вуглики мають інший колір ніж інша частина фону 
![image](https://user-images.githubusercontent.com/29049264/140611444-54d2dca9-a46a-49be-8f5f-3c16f4aa712f.png)

2021-11-06 13:38 UTC, TArch64 requested changes

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +  margin-top: 62px;
Цей маржін робить відступ від верха сторінки. margin це зовнішній відсуп для того щоб робити дірки між елементами, а коли тобі потрібно зробити відступ для контенту всередині то це має бути padding

https://tppr.me/bJdni

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +.content__posts__title {
У тебе всі елементи відносяться до блока content. Це не дуже добре і потрібно додати сюди ще блоків. Як блок може виступати будь-який кусок ui

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +  line-height: 50px;
ці стилі повторюються в `.content__header`

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +  display: flex;
для розстановки елементів в ряди та колонки краще використати grid

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +  width: 950px;
не використовуй жорстких розмірів. Це приходить до проблем коли хтось заходить з трохи меншого девайсу. Якщо тобі потрібно обмежувати ширину то тут потрібно використовувати `max-width`.

В твоєму випадку це може бути 
```css
width: 100%;
max-width: 950px;
```

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +  margin: 10px;
не використовуй маржіни в усі сторони. Краще заміни це на `grid + gap`

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +.load hr {
не використовуй стилі на теги

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <hr />
чому для лодера використовуються теги `hr`?

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +      <section class="content__header">
тут десь має бути тег `header`, якщо ти робиш хедер

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <nav class="content__navigation">
чому весь хедер всередині навігації? У тебе десь тут є лінки навігації по сайту?

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +  <script src="js/script.js" defer></script>
js апа має підключатився в кінці body. В head підключається лише супер важливі скріпти які мають повністю блочити відмалювання всього контенту до їх виконання

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +  <script src="js/script.js" defer></script>
Також це впливає на приорітетність завантаження файлів

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        <p class='content__posts__text'>${posts.body}</p>
Використовуй для такого тег `<template>`

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        url += `?_sort=title&_order=${search}`;
винеси відправлення запиту на апішку в окрему функцію

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +    const render = await fetch(url);
чому ця константа називається `render`?

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +const load = document.querySelector('[data-load]');
додавай до всіх змінних де лежать елементи дому закінчення `El`

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +    const result = `${event.target.value}`;
для чого тут темплейт стрінг?

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +            ? 'block'
зроби класік який буде ховати елементи та використовуй його для лодера та тут

2021-11-06 13:38 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +    container.querySelectorAll('[data-title]').forEach((element) => {
У тебе є логіка фільтрування тут та у функції `renderPosts`. Це дві логіки про одне і те ж саме тому залиш тільки одну

2021-11-07 07:50 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <hr />
просто колись робив цей лоадер по прикладу, так і лишилось, так візульно було зручно.  зміню на блоки.

2021-11-07 07:53 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <nav class="content__navigation">
значить зроблю окремо хедер і винесу це туди.

2021-11-07 07:57 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +  <script src="js/script.js" defer></script>
я читав і думав до defer дає можливість загружати скріпт в фоновому режимі, не блокуючи завантаження сторінки, але ще здається я його не там написав, треба було перед src писати.

2021-11-07 07:59 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +    const render = await fetch(url);
згоден рендер не підходить бо це (візуалізація, проявлення) в перекладі. заміню на щось краще.

2021-11-07 09:04 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +    const result = `${event.target.value}`;
тут трошки не зрозумів, про що саме? тут слухаю зміни в випадаючому списку, і беру значення вибраного.

2021-11-07 09:05 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +            ? 'block'
Сорян тут не зрозумів що саме мається на увазі. Якщо не складно можеш трошки пояснити.))

2021-11-07 14:23 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +            ? 'block'
Поточний варіант не дуже ок, бо ти не знаєш яке було початкове позиціювання в цієї карточки. До того ж воно може змінюватися. Наприкдлад якщо в поста буде flex позиціювання то ця логіка його перепише. Більш безпечним є використання класу
```css
.hidden { display: none !important }
```
```js
cardEl.classList.toggle('hidden', true/false);
```

2021-11-07 14:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +    const result = `${event.target.value}`;
```js
`${event.target.value}`
```
Для чого тут `event.target.value` обернуто в кавички? чому не просто `const result = event.target.value;`

2021-11-07 14:26 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <hr />
У тега `<hr>` є певне призначення і це точно не воно. Копіпаст це не причина писати в коді все що завгодно. Коли щось копіпастиш то потрібно передивитися все і буде впевненим в цьому коді бо тепер ти несеш за нього відповідальність

2021-11-07 14:27 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <nav class="content__navigation">
`<nav>` може використовуватись лише тоді коли в тебе є навігація на сайту через лінки `<a>`. Інші варіанти не є семантично правильними

2021-11-07 14:28 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +  <script src="js/script.js" defer></script>
Порядок атрибутів зазвичай не має значення. Але має значення чи скріпт доданий в `<head>` чи `<body>`

2021-11-07 23:42 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        <p class='content__posts__text'>${posts.body}</p>
Переписував з використанням тегу <template>, але тоді перестає працювати реалізоване сортування по алфавіту.

2021-11-08 09:15 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        <p class='content__posts__text'>${posts.body}</p>
Тоді можливо слід знайти проблему та пофіксити) Не можна просто так щось відкидати не вияснивши проблему

2021-11-08 09:24 UTC, TArch64 requested changes

2021-11-08 09:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +.content__posts__card {
коли ти робиш 2 розділення `__` це означає що потрібно додати ще один блок. Що тут і потрібно зробити

2021-11-08 09:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +          <a href="#" class="header__logo--link"><h1>BLOG</h1></a>
```html
          <a href="#" class="header__logo--link"><h1>BLOG</h1></a>
```

`link` це елемент header, а не модифікатор logo. Коли ти пишеш клас `header__logo--link` це означає що в тебе на цьому елементі уже є клас `header__logo` і ти **модифікуєш** стилі цього елмента

Тут же це не так. У тебе є елемент logo і в тебе є елемент link

2021-11-08 09:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <nav class="header__navigation">
тега `<nav>` тут не має бути бо в тебе тут немає навігації по сайту. Немає тегів `<a>` всередині = немає навігації

2021-11-08 09:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +        <section class="header__logo">
`<section>` це секція сторінки, а не якогось блока. Наприклад у тебе є на сторінці декілька блочків hero image, about us, subscribe form. В такому випадку кожен цей блочок буде секцією. А тут в тебе просто декілька компонентів ui. Вони не є окремими секціями сторінки тому тут не має бути тегів section в середині хедера

2021-11-08 09:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <article class="content__posts" data-blogs>
`<article>` це один конкретно пост, а не їх список

2021-11-08 09:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +    <article class="content__posts" data-blogs>
article описує одну сутність на сторінці, а не їх множину

2021-11-08 09:24 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        element.closest('[data-card]').style.display = element.innerText.toLowerCase().includes(val)
Якщо робиш сортування через апішку то і фільтрацію також роби через апішку

2021-11-08 09:42 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        element.closest('[data-card]').style.display = element.innerText.toLowerCase().includes(val)
фільтрацію так зробив, бо через апішку виходить зробити пошук тільки по всіх елементах викорстовуючи '?q=', а не тільки в title.

2021-11-08 09:45 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        <p class='content__posts__text'>${posts.body}</p>
написав таку частину, все виводить, але не сортує, я намагався довго до ночі то пофіксити, але не вистачає ні довсіду ні знань.
`const addPosts = async (result) => {
    const addPostBox = await result;
    const containerEl = document.querySelector('[data-blogs]')
    const template = document.querySelector('[data-posts]');

    addPostBox.forEach((posts) => {
        const clone = template.content.cloneNode(true);
        const h3 = clone.querySelector('[data-title]');
        const text = clone.querySelector('[data-text]');
        h3.textContent= `${posts.title}`;
        text.textContent = `${posts.body}`;
        containerEl.append(clone);
    });
};`

2021-11-08 10:38 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/css/style.css
> +.content__posts__card {
прочитав тут написано https://ru.bem.info/methodology/quick-start/  що одне роділення для модифікатора, два для елемента. в інших статтях прочитав, що використовують два мінуси для модифікатора.

2021-11-08 13:20 UTC, TArch64 requested changes

2021-11-08 13:20 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +        <article class="header__logo">
Поясни, будь-ласка, чому ти вирішив тут використати саме тег `<article>` а не якийсь інший

2021-11-08 13:20 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +          <a href="#" class="header__logo__link"><h1>BLOG</h1></a>
уникай в назвах 2 `__`. Це можна назвати просто `header__logo-link`. Це `logo-link` це елемент хедера і так уж вийшло що він знаходиться всередині іншого елемента. Але в структурі класів там не обовʼязково про це знати

2021-11-08 13:20 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        <p class='content__posts__text'>${posts.body}</p>
Тобі апішка в правильному порядку віддає пости взагалі?

2021-11-08 13:20 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +    const addPostBox = await result;
цей `await ` має бути за межами функції, а сюди потрібно передавати уже отриманий список постів

2021-11-08 13:20 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        <p class='content__posts__text'>${posts.body}</p>
Ти правильно відправляєш параметри в запиті?

2021-11-08 13:20 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        element.closest('[data-card]').style.display = element.innerText.toLowerCase().includes(val)
Параметр `q` це пошук по всьому тексту. Для пошуку по конкретному полі потрібно використовувати `назва_поля_like`. Наприклад `title_like=sunt`

2021-11-08 13:45 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/js/script.js
> +        <p class='content__posts__text'>${posts.body}</p>
зараз так, сортує все правильно в обидва боки. запит проходить вірний.
коли робив з темплейтом проставляв консоль логи, щоб відслідкувати що не так, і мені здалось що доходить до `.forEach` і він перезапускається щоб дати нові дані.

2021-11-08 14:07 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +        <article class="header__logo">
читав про  article  що "Элемент должен содержать часть самодостаточной информации, которая может быть вырвана из контекста всей страницы без потери смысла." . Порахував що він підходить. зараз передивлявся доку і розумію, що не дуже.

2021-11-08 16:08 UTC, TArch64 commented on homeworks/volodymyr.khrushch_Vladimior/3-async/index.html
> +        <article class="header__logo">
Лого саме по собі не самодостатнє. Це частина контенту сторінки. Тут не має буть article в хедері. Секшинів всередині хедера я також не бачив

Можеш почитати оце. https://html5book.ru/html-tags/

2021-11-08 19:32 UTC, closed without merging