3 async (LL)
MastersAcademy/frontend-course-2021 pull request #113
Opened 2021-11-05 10:06 UTC by deadhard90

2021-11-05 13:40 UTC, TArch64 commented on homeworks/leonid.lushchiy_deadhar90/3-async/css/general_style.css
> +[data-header] {
всі стилі мають бути на класах

2021-11-05 13:40 UTC, TArch64 commented
Пофікси еррори лінтерів

2021-11-05 14:23 UTC, deadhard90 commented
Та знаю))) времени нет. Работы много было. Сегодня уже не успею.

2021-11-05 21:06 UTC, deadhard90 commented on homeworks/leonid.lushchiy_deadhar90/3-async/css/general_style.css
> +[data-header] {
переробив)))

только не понимаю о чем говорит спнцификация по ошибкам(((

2021-11-06 13:18 UTC, TArch64 commented
![image](https://user-images.githubusercontent.com/29049264/140611024-6880f96c-f3e8-4d2e-b83c-ff6b328aadff.png)

![image](https://user-images.githubusercontent.com/29049264/140611059-89e7874e-8fa3-4288-a7c1-4ca84d5680b2.png)

Погугли в гуглі ці штуки. Він тобі покаже посилання на сайт https://eslint.org/ де це все описано і з прикладами

2021-11-06 20:54 UTC, deadhard90 commented
Это все я прекрасно понимаю. Я же говорю, что не понимаю о чем речь в документации. Попробовал поправить как, мне показалось, требует документация - стало хуже)))

2021-11-07 20:07 UTC, NickCashFlow requested changes
исправьте ошибки линтеров и добавьте ссылку на github pages

2021-11-07 20:07 UTC, NickCashFlow commented on homeworks/leonid.lushchiy_deadhar90/3-async/js/general.js
> +        Array.prototype.map.call(nodesToSort, (node) => { return { node: node, relevantText: node.querySelector('h1').textContent, };
зачем здесь сделано через прототип?

2021-11-08 12:34 UTC, deadhard90 commented on homeworks/leonid.lushchiy_deadhar90/3-async/js/general.js
> +        Array.prototype.map.call(nodesToSort, (node) => { return { node: node, relevantText: node.querySelector('h1').textContent, };
https://deadhard90.github.io/frontend-course-2021/homeworks/leonid.lushchiy_deadhar90/3-async/index.html

2021-11-09 12:13 UTC, closed without merging