3-async with *
MastersAcademy/frontend-course-2021 pull request #116
Opened 2021-11-05 10:49 UTC by ConstantinRusenko

https://constantinrusenko.github.io/frontend-course-2021/homeworks/konstantin.rusenko_ConstantinRusenko/3-async/

2021-11-05 11:47 UTC, MZabolotnev reviewed
![image](https://user-images.githubusercontent.com/25617217/140505516-ef42d481-a304-4d4b-a880-19d2f79b6727.png)
Стиль заголовка не соответствует дизайну.
![image](https://user-images.githubusercontent.com/25617217/140505557-3cbb767f-ae47-4ac7-8d6c-53247ff6aebe.png)
Кнопка не соответствует дизайну. Можно и нужно экспортировать svg или png из figma. 
![image](https://user-images.githubusercontent.com/25617217/140505748-f41f1582-28d6-4779-a48b-3d63c41f54f2.png)

![image](https://user-images.githubusercontent.com/25617217/140505826-24527ba3-40a1-4cb4-a275-64003a35554b.png)

Border-radius не соответствует дизайну

2021-11-05 11:47 UTC, MZabolotnev commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/style.css
> +  width: 30px;
Зачем тут изменения из прошлой домашки?

2021-11-05 11:47 UTC, MZabolotnev commented on homeworks/konstantin.rusenko_ConstantinRusenko/3-async/index.js
> +    if (statement === 'Message sucvessfuly delete') {
Не критично - но опечатка) Так же, хорошая практика все текстовки/статичные строки выносить в константы либо наверх файла, либо даже в отдельный файл. Что то типа const MESSAGE_SUCCESS = 'Message deleted successfully'

2021-11-05 11:47 UTC, MZabolotnev commented on homeworks/konstantin.rusenko_ConstantinRusenko/3-async/index.js
> +    const message = delMessage;
зачем тут создавать эту переменную?

2021-11-05 11:56 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/style.css
> +  width: 30px;
Случайно добавил.
А по дизайну, я вчера на лекции спрашивал за это и ответ был что не нужно точь в точь следовать дизайну.

2021-11-05 12:00 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/3-async/index.js
> +    const message = delMessage;
Если не создавать переменную, то линтер будет выдавать ошибку. 
![image](https://user-images.githubusercontent.com/30158130/140507266-c37efb94-8fc8-43b6-a3c5-4d7e6c117dd3.png)

2021-11-05 12:04 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/3-async/index.js
> +    if (statement === 'Message sucvessfuly delete') {
Спасибо за совет, добавил в константу.

2021-11-05 12:55 UTC, MZabolotnev commented on homeworks/konstantin.rusenko_ConstantinRusenko/3-async/index.js
> +    const message = delMessage;
Цель не обойти линтер, а исправить код. Создавая новую переменную и присваивая ей параметр - ты всего лишь обходишь линтер - но все равно изменяешь параметр функции потому что он передается по ссылке.

2021-11-05 13:03 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/3-async/index.js
> +    const message = delMessage;
Я не изменяю параметр функции, я беру парент ноду чтобы изменить у нее стиль. Как сделать по другому?

2021-11-05 15:39 UTC, MZabolotnev commented on homeworks/konstantin.rusenko_ConstantinRusenko/3-async/index.js
> +    const message = delMessage;
Мы решили удалить вообще это правило, так что вопрос закрыт)

2021-11-05 16:03 UTC, MZabolotnev requested changes

2021-11-05 16:03 UTC, MZabolotnev commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/style.css
> +  width: 30px;
Вопрос с дизайном тоже закрыт. А изменения с прошлой домашки нужно удалить

2021-11-05 18:35 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/style.css
> +  width: 30px;
Готово.

2021-11-07 10:27 UTC, MZabolotnev approved these changes

2021-11-07 10:30 UTC, merged