3-async
MastersAcademy/frontend-course-2021 pull request #117
Opened 2021-11-05 11:52 UTC by skyprog

2021-11-05 13:41 UTC, TArch64 commented
Пофікси еррори лінтерів

2021-11-06 16:13 UTC, TArch64 requested changes
Додай лінк на гітхаб пейджес

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

2021-11-06 16:13 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/index.html
> +                    <option value="sort_a-z">A - z</option>
це контрол сортування тому не потрібно писати на початку кожного опшина `sort_`

2021-11-06 16:13 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/index.html
> +                        src="https://s3-alpha-sig.figma.com/img/fc79/dbc8/ca892b8f222e7476d95cb5283a69c996?Expires=1636934400&Signature=cTVmUN4AgRrht4QMeE-vSae86ZGZ4~ylPwKiS~YrYSI~~3VFdBMS8EUK3pcSjPD
Поправ форматування. Кожен теж має бути в своєму рядку кода

2021-11-06 16:13 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/js.js
> +                articleTitle.textContent = show.title;
Розбий код на функції. Одна функція = один логічнй кусок коду

2021-11-06 16:13 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/js.js
> +                articleShow.remove();
тут трошки коду повторюється. Оптимізуй це

2021-11-06 16:13 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/style.css
> +}
```suggestion
.article__text::first-letter,
.content__article::first-letter {
  text-transform: uppercase;
}
```

2021-11-06 16:13 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/index.html
> +                <button class="article__remove--btn" data-remove-btn><img
Тут має бути не модифікатор, а елемент. Модифікатор це коли в тебе є уже тут клас `article__remove` а ти його **модифікуєш** за допомогою `--btn`

2021-11-06 16:13 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/style.css
> +.article__remove--btn img {
стилі можна вішати тільки на класи

2021-11-07 06:56 UTC, skyprog commented
Лінк на гітхаб пейджес: https://skyprog.github.io/frontend-course-2021/homeworks/roman.kushnirenko_skyprog/3-async/index.html

2021-11-07 06:58 UTC, skyprog commented on homeworks/roman.kushnirenko_skyprog/3-async/js.js
> +                articleShow.remove();
оптимізував

2021-11-07 14:37 UTC, TArch64 requested changes

2021-11-07 14:37 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/js.js
> +            filterSearch.addEventListener('keyup', () => {
код все ще не розбитий на логічні частини. Завантаження даних маю бути в одній функції, сортування в іншій, а відмалювання в третій і так далі

2021-11-07 14:37 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/js.js
> +                    filterFound.map((show) => {
тут має бути не map. Він використовується лише для перетворення даних. Тут потрібно використовувати `forEach`. Почитай в чому різниця між ними двома і що коли потрібно використовувати

2021-11-07 14:37 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/js.js
> +            // Filtering
Замість коментарів краще розділяй код на логічні частини. Коли є нормально названі функції та зміні то не потрібні і коментарі в коді

2021-11-07 14:37 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/index.html
> +                    <img class="img_remove" src="https://s3-alpha-sig.figma.com/img/fc79/dbc8/ca892b8f222e7476d95cb5283a69c996?Expires=1636934400&Signature=cTVmUN4AgRrht4QMeE-vSae86ZGZ4~ylPwKiS~YrYSI
Цей імеж є елментрм блока article? Виглядає як так

2021-11-07 14:37 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/style.css
> +  left: 316px;
Для чого тут top та left? В цього елемента статичне позиціювання

2021-11-07 14:37 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/style.css
> +  left: 316px;
Тут більш доцільно використовувати `bottom` та `right`. В поточному випадку top та left привʼязують позицію кнопки до розмірів контенту

2021-11-07 14:37 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/3-async/style.css
> +}
постав плагін `editorconfig`

2021-11-08 07:54 UTC, TArch64 commented
@skyprog ping-ping

2021-11-08 08:46 UTC, skyprog commented
> ping-ping

Виправив

2021-11-08 13:51 UTC, TArch64 approved these changes

2021-11-08 13:51 UTC, merged