3 async
MastersAcademy/frontend-course-2021 pull request #118
Opened 2021-11-05 12:06 UTC by DmitriyKondaurov

2021-11-06 16:27 UTC, TArch64 requested changes
Додай лінк на гітхаб пейджес
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +        <div class="posts-sort">
зроби класіки по бему

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +            <label for="filter" hidden>filter</label>
Для чого заховані лейбли?

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +const preLoader = () => {
`preLoader` що? Що робить прелодер? В назвах функцій має бути дія. Наприклад `addPost` додає пост, а що робить прелодер?

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    document.querySelector('.loader_inner').classList.add('hide');
`loader_inner` знаходиться всередині `loader` тому якщо захований останній елемент цей буде також захований. Для нього не потрібно накидати класік

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    newElCloseBtn.classList.add('trash-bnt');
зроби рендерінг поста через тег `<template>`

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +const postSort = document.body.querySelector('[data-sort]');
додавай до зміних що тримають в собі елементи дому закінчення `El`

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    const bTitle = b.firstElementChild.textContent.toUpperCase();
замість firstElementChild використовуй селектори. Сьогодні це перший елемент,  завтра другий, а після завтра там враппер зʼявився

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    const bTitle = b.firstElementChild.textContent.toUpperCase();
firstElementChild привʼязує твій js до структури html до не є добре бо тягне за собою зайві зміни та баги

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    } if (postSort.value === 'z-a') {
винеси кожну сортування під кожен напрямок в окремі функції. Старайся уникати таких вкладений конструкцій

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +        // eslint-disable-next-line max-len
не відключай лінтери а фікси їх те що вони тобі говорять

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                json.map((post) => addPost(post.title, post.body));
map використовується для того щоб перетворювати дані в масивах, а для сайд ефектів потрібно використовувати forEach. Почитай що це така та в чому їх різниця

2021-11-06 16:27 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +window.onload = () => getPosts();
Замість onload івента використовуй атрибут `defer` в скріпта

2021-11-06 17:24 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +            <label for="filter" hidden>filter</label>
Коли небуло лейблів то ІДЄшка ругалася типу це не валідно... але не макеті лейблів немає. То як мені правильно зробити, прибрати їх чи показати?

2021-11-06 17:54 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +window.onload = () => getPosts();
done

2021-11-06 17:54 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    document.querySelector('.loader_inner').classList.add('hide');
done

2021-11-06 17:55 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +const preLoader = () => {
done

2021-11-06 17:55 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +        <div class="posts-sort">
done

2021-11-06 18:14 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    } if (postSort.value === 'z-a') {
done

2021-11-06 18:14 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    const bTitle = b.firstElementChild.textContent.toUpperCase();
done

2021-11-06 18:24 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                json.map((post) => addPost(post.title, post.body));
done

2021-11-06 18:24 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +        // eslint-disable-next-line max-len
done

2021-11-06 20:21 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    newElCloseBtn.classList.add('trash-bnt');
done

2021-11-06 20:23 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +            <label for="filter" hidden>filter</label>
done

2021-11-07 14:38 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +const postSort = document.body.querySelector('[data-sort]');
Цей комментар все ще не пофікшений

2021-11-07 14:48 UTC, TArch64 requested changes

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                        <a href="#" class="trash-btn__link" data-post-trash-bnt-link>
Чому тут тег `<a>`. Чому не `<button>`?

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                    <h2 class="post-list__item-title" data-post-title>Title</h2>
було б більш логічно зробити пост окремим блоком, бо в нього є купа елементів

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +const hideLoaderGifImage = () => {
```suggestion
const hideLoader = () => {
```
Достатньо такого. `hideLoaderGifImage ` має забагато деталей в назві. Що гіфка заміниться на svg чи на теги та стилі? Потрібно буде ходити змінювати назви. Достатньо знати лише того що це  лодер і ця функція його ховає

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +            } return 0;
Тут трошки не так щось з переносами рядків
```suggestion
            if (postSort.value === 'a-z') {
                return sortElForward(a, b);
            }
            if (postSort.value === 'z-a') {
                return sortElReverse(a, b);
            }
            return 0;
```

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    listOfPosts
`listOfPosts` потрібно тільки для того щоб зробити ререндер. Краще дістань цей масив перед `fieldForPosts.innerHTML = ''`. Так буде на 1 менше глобальну зміну та не доведеться думати за оновлення цього списку

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                listOfPosts = Array.from(document.body.querySelector('[data-main-box]').children);
У кожного поста є свій атрибутик. Краще використовуй тут його
```js
listOfPosts = Array.from(document.querySelectorAll('[data-post-item]'));
```

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                listOfPosts.shift();
для чого тут `shift()`?

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                template = document.querySelector('[data-post-template]');
для чого перезаписувати темплейт?

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +  margin-top: -30px;
використовуй `transform: translate` замість маржінів. Браузеру простіше малювати його ніж зміну позицій контенту через маржіни

2021-11-07 14:48 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +  background-position: center center;
чому через фоновий імедж? Чому не тег `<img>`?

2021-11-07 20:16 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +const postSort = document.body.querySelector('[data-sort]');
done

2021-11-07 20:32 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                    <h2 class="post-list__item-title" data-post-title>Title</h2>
не зрозумів що треба зробити....  пост в <li>, хіба це не окремий блок?

2021-11-07 20:38 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +    listOfPosts
done

2021-11-07 20:39 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                        <a href="#" class="trash-btn__link" data-post-trash-bnt-link>
done

2021-11-07 20:42 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                listOfPosts = Array.from(document.body.querySelector('[data-main-box]').children);
done

2021-11-07 20:50 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                listOfPosts.shift();
коли я брав `('[data-main-box]').children` то в `listOfPosts` залазив `<template>` для його видалення я використовував `shift()`
Але зараз після використання `querySelectorAll('[data-post-item]')` це стало непотрібно
Done

2021-11-07 20:56 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +                template = document.querySelector('[data-post-template]');
done

2021-11-07 21:16 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +  margin-top: -30px;
done

2021-11-07 21:21 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +  background-position: center center;
Потому что это фоновое изображение которое не нисёт никакой смысловой нагрузки и не имеет отношения к  контенту. Фон при ожидании ответа от сервера...
P.S. Если я не прав, то исправлю на `<img>`.

2021-11-07 21:32 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +            } return 0;
done

2021-11-07 21:33 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +  background-position: center center;
`background-image` це коли ти хочеш на фон чогось покласти імедж. Власне з цього і назва. В усіх інших випадках використовується тег `<img>`. І цей імедж несе за собою смислову нагрузку -- це показати юзеру що контент завантажується. Кожна частинка контенту несе за собою сенс, а якщо його немає то навіщо взагалі це показувати юзеру?

2021-11-07 21:34 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/main.js
> +const hideLoaderGifImage = () => {
done

2021-11-07 21:35 UTC, TArch64 commented
> fixed mentor's comment (second part)
Кожен комміт має бути логічно завершеним кусочком змін. По його назві має бути зрозуміло що там було зменено не відкриваючи код. Уникай таких коммітів де все скинуто підряд. В ідеальному варіанті кожжен коммент з ревью має бути окремим коммітом

2021-11-07 21:37 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                    <h2 class="post-list__item-title" data-post-title>Title</h2>
`post-list__item` це не окремий блок. Це елемент блока `post-list`. Як і всі елементи всередині поста. А я кажу про те що потрібно пост зробити окремим блоком, який буде, наприклад, називатися `post`

2021-11-07 21:41 UTC, DmitriyKondaurov commented
> > fixed mentor's comment (second part)
> 
> Кожен комміт має бути логічно завершеним кусочком змін. По його назві має бути зрозуміло що там було зменено не відкриваючи код. Уникай таких коммітів де все скинуто підряд. В ідеальному варіанті кожжен коммент з ревью має бути окремим коммітом

Добре наступні коміти буду робити по кожному питанню окремо

2021-11-07 21:41 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                                 width=66 height=42>
Потрібно додавати до атрибутів кавички та до розмірів їх юніти
```suggestion
                                 width="66px" height="42px">
```

2021-11-07 21:41 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                            <img class="trash-btn__icon" src="Trash-Icon.png" alt="Trash" data-post-trash-bnt-icon
`alt="Trash"` має описувати що це за імедж і для чого він. В даному випадку буде краще написати `Delete post`

2021-11-07 21:41 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +.main-content__loader {
лодер потрібно зробити окремим блоком. Елемент `loader__inner` є, а блока `loader` немає. Коли ти в класі пишеш `loader__inner` то десь обовʼязково має бути класс `loader`. І точно так же на всі інші елементи та блоки

2021-11-07 21:42 UTC, TArch64 commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                            <img class="trash-btn__icon" src="Trash-Icon.png" alt="Trash" data-post-trash-bnt-icon
alt це alternative text. Тобто те що буде показуватися якщо імедж не завантажився

2021-11-07 21:48 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                    <h2 class="post-list__item-title" data-post-title>Title</h2>
done

2021-11-07 21:51 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +  background-position: center center;
Добре виправляю

2021-11-07 21:54 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/index.html
> +                            <img class="trash-btn__icon" src="Trash-Icon.png" alt="Trash" data-post-trash-bnt-icon
Добре, виправив

2021-11-07 21:57 UTC, DmitriyKondaurov commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/3-async/style.css
> +.main-content__loader {
Done

2021-11-07 22:18 UTC, TArch64 approved these changes

2021-11-07 22:19 UTC, merged