added 3-async
MastersAcademy/frontend-course-2021 pull request #121
Opened 2021-11-05 13:34 UTC by igordordev

2021-11-05 13:41 UTC, TArch64 commented
Пофікси еррори лінтерів

2021-11-05 15:09 UTC, igordordev commented
> 
> 
> Пофікси еррори лінтерів

Виправив.

2021-11-07 14:56 UTC, TArch64 requested changes
Додай лінк на гітхаб пейджес
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

2021-11-07 14:56 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/script.js
> +        newArticle.classList.add('articles-area__article', 'article');
Зроби рендер поста через тег `<template>`

2021-11-07 14:56 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/script.js
> +    return articlesSorted;
Коли можеш використовуй замість `if ... else if`  конструкцію `if + return`. Зазвичай це більш приємно читати і простіге в цьому розбиратися
```suggestion
    if (sortCondition.value === 'sort-a-z') {
        return articlesSorted.sort((a, b) => ((a.title > b.title) ? 1 : -1));
    }
    if (sortCondition.value === 'sort-z-a') {
        return articlesSorted.sort((a, b) => ((a.title > b.title) ? 1 : -1)).reverse();
    }
    return articlesArr;
```

2021-11-07 14:56 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/script.js
> +        articlesSorted.sort((a, b) => ((a.title > b.title) ? 1 : -1)).reverse();
щоб зробити реверсивне сортування ти можеш тут просто поміняти місцями 1 та -1. Так буде менше операцій з масивам

2021-11-07 14:56 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/script.js
> +const loadingBLock = document.querySelector('.loading-window');
1. Всі js селектори мають бути через дата атрибути
2. додавай закінчення `El` до зміних які тримають в собі елементи дому

2021-11-07 14:56 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/style.css
> +h1::first-letter, h2::first-letter, p::first-letter {
не використовуй теги як селектори в стилях. Все тільки через класи (body та html є виключенням)

2021-11-07 14:56 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/style.css
> +}
Постав собі editorconfig плагін в IDE

2021-11-08 07:54 UTC, TArch64 commented
@igordordev ping-ping

2021-11-08 09:26 UTC, igordordev commented
> 
> 
> @igordordev ping-ping

Так, я бачив коментарі. Зараз виправляю.

2021-11-08 12:20 UTC, igordordev commented
> 
> 
> @igordordev ping-ping

Помилки виправив. 

Не знаю, чи правильно я нашалтував GitHub Pages. За посиланням у мене відкривається опис курсу.
Сторінка: https://igordordev.github.io/frontend-course-2021/
Прямий лінк на цю тему: https://igordordev.github.io/frontend-course-2021/homeworks/igor.doroshenko_igordordev/3-async/index.html

2021-11-08 13:52 UTC, TArch64 commented
> > @igordordev ping-ping
> 
> Помилки виправив.
> 
> Не знаю, чи правильно я нашалтував GitHub Pages. За посиланням у мене відкривається опис курсу. Сторінка: https://igordordev.github.io/frontend-course-2021/ Прямий лінк на цю тему: https://igordordev.github.io/frontend-course-2021/homeworks/igor.doroshenko_igordordev/3-async/index.html

Все правильно, так і має бути

2021-11-08 13:55 UTC, TArch64 requested changes

2021-11-08 13:55 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/script.js
> +        const articlesCloneTemplate = articleTemplateEl.content.cloneNode(true);
Потрібно спочатку зробити клон контенту темплейта, а уже потім змінювати елементи саме клона. Сам елемент темплейта змінюватися ніяк не повинен

2021-11-08 13:55 UTC, TArch64 commented on homeworks/igor.doroshenko_igordordev/3-async/style.css
> +.header-panel__title::first-letter, .article__title::first-letter, .article__content::first-letter {
Став переноси рядочків після коми
```suggestion
.header-panel__title::first-letter,
.article__title::first-letter,
.article__content::first-letter {
```

2021-11-08 13:56 UTC, TArch64 commented
@igordordev  2 останні (сподіваюся) комментарів

2021-11-08 14:16 UTC, TArch64 approved these changes

2021-11-08 14:17 UTC, merged