4 layouts
MastersAcademy/frontend-course-2021 pull request #129
Opened 2021-11-06 20:44 UTC by 20-Igorek-21

2021-11-07 00:08 UTC, 20-Igorek-21 commented
https://20-igorek-21.github.io/frontend-course-2021/homeworks/ihor.kropyvnyi_20-Igorek-21/4-layouts/flexbox/index-flex

2021-11-07 00:09 UTC, 20-Igorek-21 commented
https://20-igorek-21.github.io/frontend-course-2021/homeworks/ihor.kropyvnyi_20-Igorek-21/4-layouts/grid/index-grid

2021-11-07 19:39 UTC, NickCashFlow commented
ссылки не работают

2021-11-07 20:00 UTC, NickCashFlow requested changes
ссылки на github pages не работают, без них функционал не получается проверить

2021-11-08 19:17 UTC, 20-Igorek-21 commented
я сделал изменения, проверьте пожалуйста)

2021-11-08 19:34 UTC, 20-Igorek-21 commented
> ссылки на страницы github не работают, без них функционал не получается проверить

я возобновил их функционал.

2021-11-13 07:30 UTC, closed without merging