4 flex
MastersAcademy/frontend-course-2021 pull request #130
Opened 2021-11-06 22:01 UTC by turuta7

2021-11-07 15:10 UTC, TArch64 requested changes
Додай лінк на гітхаб пейджес
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

2021-11-07 15:10 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/3-async/index.html
> +            <div class="loader-1"></div>
`loader-1`? Десь тут є `loader-2`?

2021-11-07 15:10 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/3-async/index.html
> +                <button class="message__button" data-button-ok>ok</button>
пофікси кількість пробільчиків у html

2021-11-07 15:10 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/3-async/script.js
> +    addEventListenerPost();
Замість того щоб ще один раз шукати в домі пости та бігати по масиву ти можеш викликати функцію всередині `data.forEach((element) => {` де ти власне створюєш пост і одразу додати необхідні лістенери

2021-11-07 15:10 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/3-async/style.css
> +.main__header-input-filter[type="text"] {
тут точно потрібна додаткова специфічність з `[type="text"]`?

2021-11-07 15:10 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/3-async/style.css
> +.main__container__messages {
уникай 2х `__` в назві одного класа

2021-11-07 15:10 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-flex/flex/index.html
> +    <title>3-flex-Turuta</title>
4та домашка має бути окремим пулл реквестом

2021-11-07 15:10 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-flex/flex/index.html
> +    <title>3-flex-Turuta</title>
Дивитися в ній я зараз нічого не буду

2021-11-11 17:32 UTC, TArch64 commented
@turuta7 Поправ еррори лінтера

2021-11-13 17:57 UTC, TArch64 requested changes
Немає варіанти з використанням грід лаяута

2021-11-13 17:57 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-flex/flex/style.css
> +  height: 100vh;
Старайся уникати використання `vh`. Цей юніт має різні баги на девайсах, особливо коли це мобайл чи таблет. Наприклад у тебе може зʼявитися вертикальний скрол на сторінці

2021-11-13 17:57 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-flex/flex/index.html
> +            <div class="main">
Використай семантичні теги

2021-11-13 17:57 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-flex/flex/style.css
> +  width: 100%;
`main__center` не може мати `width: 100%` бо окрім нього ще є інші елементи в контейнері. Якщо ти хочеш щоб елемент займав все вільне місце то краще використовуй для цього `flex-grow: 1;`

2021-11-15 22:06 UTC, turuta7 commented
пофіксив

2021-11-18 17:37 UTC, TArch64 commented
@turuta7 Немає варіанту з використанням css grid

2021-11-18 17:40 UTC, turuta7 commented
Не встигаю. Варіанту немає.

2021-11-24 17:14 UTC, closed without merging