4 layout
MastersAcademy/frontend-course-2021 pull request #132
Opened 2021-11-08 16:22 UTC by VladislavMedvedyev

2021-11-08 16:25 UTC, VladislavMedvedyev reviewed
Удалил лишние файлы с дом. работы 2-3

2021-11-11 17:56 UTC, NickCashFlow requested changes
а зачем поудалял вот эти файлы
homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/index.html
homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
?
теперь эта ветка конфликтует с мейном
порезолвай конфликты с мейном и тогда я замержу, по коду всё норм

2021-11-12 11:11 UTC, VladislavMedvedyev commented
Вроде конфликт зарезолвил. Не прошла проверка Awesome Linter / Lint HTML. Пока не получилось включить Awesome Linter / Lint HTML в VSCode. Займусь подключением

2021-11-13 21:48 UTC, VladislavMedvedyev commented
Поправил HTML Linter errors. Вродь все

2021-11-14 16:53 UTC, NickCashFlow approved these changes

2021-11-14 16:55 UTC, merged