4-modules
MastersAcademy/frontend-course-2021 pull request #137
Opened 2021-11-11 07:09 UTC by kovalov

2021-11-11 12:21 UTC, kovalov commented
Пару вопросов по реализации и вещах, которые хотел бы исправить/сделать правильно:
1. Нормальная ли практика использовать input type="date"?
2. Как лучше реализовать переключение часовых поясов? Моя реализация наслаивает текущий вариант и новый
3. Какую заглушку лучше делать для поля? Стоит ли использовать input type="text" для вывода значений?

2021-11-12 13:08 UTC, MZabolotnev commented
> Пару вопросов по реализации и вещах, которые хотел бы исправить/сделать правильно:
> 
> 1. Нормальная ли практика использовать input type="time"?
> 2. Как лучше реализовать переключение часовых поясов? Моя реализация наслаивает текущий вариант и новый
> 3. Какую заглушку лучше делать для поля? Стоит ли использовать input type="text" для вывода значений?

1. Тут больше подойдет type="date"
2. Не совсем понял что ты вкладываешь в понятие "наслаивает"?
3. Input для ввода текста, не для вывода. 

Сейчас все вроде ок, единственное что я не понял - зачем у тебя все option селекта - selected.

2021-11-12 13:09 UTC, MZabolotnev submitted a review, later dismissed
Коммент выше

2021-11-12 15:41 UTC, NickCashFlow requested changes
если покликать на разные селекты, то дата начинает моргать http://i.imgur.com/1UHyWLV.png
смотриться как баг
лучше дату другого пояса выводить рядом с текущим

2021-11-12 15:41 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/4-modules/app.js
> +}
лучше класс вынести в отдельный файл, а все зависимости передавать в конструктор

2021-11-12 15:41 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/4-modules/app.js
> +document.querySelector('[data-datepicker]').addEventListener('change', (e) => {
ссылку на ноду лучше вынести в переменную

2021-11-12 15:41 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/4-modules/app.js
> +    Array.from(document.querySelector('[data-page]').children).filter((element) => element.dataset.card).forEach((element) => {
также в переменную

2021-11-12 15:41 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/4-modules/app.js
> +document.querySelector('[data-page]').addEventListener('click', (e) => {
аналогично

2021-11-12 15:41 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/4-modules/app.js
> +document.querySelector('[data-timezone]').addEventListener('change', (e) => {
аналогично

2021-11-12 15:41 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/4-modules/index.html
> +                        <option value="EST" class="card__timezone" selected>New York</option>
почему все option в состоянии selected?

2021-11-12 22:31 UTC, kovalov commented on homeworks/vladyslav.kovalov_kovalov/4-modules/index.html
> +                        <option value="EST" class="card__timezone" selected>New York</option>
Исправил

2021-11-12 22:38 UTC, kovalov commented on homeworks/vladyslav.kovalov_kovalov/4-modules/app.js
> +}
Сейчас у меня есть класс Time и App. Как лучше разделить и какой использовать (или добавить) для связки остальных?

2021-11-13 08:27 UTC, kovalov commented
> если покликать на разные селекты, то дата начинает моргать http://i.imgur.com/1UHyWLV.png смотриться как баг лучше дату другого пояса выводить рядом с текущим

Исправил

2021-11-13 16:30 UTC, kovalov commented
Переписал shortestWeekDaysNumber. Прошу проверить и подсказать, как улучшить

2021-11-14 16:03 UTC, NickCashFlow requested changes
исправь это, все остальное меня устраивает

2021-11-14 18:19 UTC, NickCashFlow approved these changes

2021-11-14 18:21 UTC, merged