4-module
MastersAcademy/frontend-course-2021 pull request #138
Opened 2021-11-11 14:45 UTC by AndriiMorozov88

https://andriimorozov88.github.io/frontend-course-2021/homeworks/Andrii.Morozov_AndriiMorozov88/4-modules

2021-11-11 17:35 UTC, TArch64 commented
@AndriiMorozov88 Поправ еррори лінтера.

Також запусти в руті проекта `npm install` та постав плагіни `stylelint`, `eslint` та `editoconfig` в IDE

2021-11-11 17:41 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/script_date.js
> +fullWeek();
```js
longMonth();
shortestWeek();
fullWeek();
```
В назвах функцій має бути екшин, дієслово

2021-11-11 18:33 UTC, AndriiMorozov88 commented
> @AndriiMorozov88 Поправ еррори лінтера.
> 
> Також запусти в руті проекта `npm install` та постав плагіни `stylelint`, `eslint` та `editoconfig` в IDE

npm install запустил в папке 4-module. а можно ссылки на инструкции как установить эти плагины?

2021-11-11 18:59 UTC, TArch64 commented
@AndriiMorozov88 Рут проекта це `frontend-course-2021`. Запусти будь-ласка там цю команду. Не в папці з домашкою

2021-11-11 19:00 UTC, TArch64 commented
> > @AndriiMorozov88 Поправ еррори лінтера.
> > Також запусти в руті проекта `npm install` та постав плагіни `stylelint`, `eslint` та `editoconfig` в IDE
> 
> npm install запустил в папке 4-module. а можно ссылки на инструкции как установить эти плагины?

У тебе VS Code?

2021-11-11 19:09 UTC, AndriiMorozov88 commented
Да, VS Code

11 листопада 2021, 21:00:11, від "Taras Turchenko" ***@***.***>:


@AndriiMorozov88 Поправ еррори лінтера.
Також запусти в руті проекта npm install та постав плагіни stylelint, eslint та editoconfig в IDE
npm install запустил в папке 4-module. а можно ссылки на инструкции как установить эти плагины?
У тебе VS Code?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-11-11 19:11 UTC, TArch64 commented
> Да, VS Code 11 листопада 2021, 21:00:11, від "Taras Turchenko" ***@***.***>: @AndriiMorozov88 Поправ еррори лінтера. Також запусти в руті проекта npm install та постав плагіни stylelint, eslint та editoconfig в IDE npm install запустил в папке 4-module. а можно ссылки на инструкции как установить эти плагины? У тебе VS Code? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint
https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

2021-11-13 17:43 UTC, TArch64 commented
@AndriiMorozov88 Лінк на гітхаб пейджес не працює. Показує 404

2021-11-13 17:50 UTC, TArch64 requested changes
Потрібно виконати завдання згідно вимогам завдання

2021-11-13 17:50 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +                monthDays.append(dates);
Додавай елемент в дом тільки тоді коли ти вже зробив всі маніпуляції з ним

2021-11-13 17:50 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +    monthDays.style.height = '30px';
використовуй класи та css файліки для додавання стилів

2021-11-13 17:50 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +        const weekDay = date.getDay();
В завданні є описано які мають бути функції в цьому модулі, як вони мають називатися, що вони мають приймати в аргументи і що мають повертати. Наразі це все не виконано. Почитай уважно опис кожної функції. По всій логіці завдання в цьому модулі має бути робота **тільки** з датами, а вся логіка ui має бути в окремому файлі

2021-11-13 17:50 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/index_date.html
> +<head>
Немає тега html

2021-11-13 17:51 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/index_date.html
> +    <div data-long-month></div>
Ми на курсі фронтенду тому постарайся зробити так щоб це виглядало красіво. Зроби щось карточками чи ще якось

2021-11-15 18:45 UTC, TArch64 requested changes
Максимально сильно уникай if else if у коді. Зазвичай такий код потім робиться не читабельним та його важко розуміти. Винось якісь речі в функції, роби декомпозицію коду

2021-11-15 18:45 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +    }
Це називається хард код. А якщо буде 30 днів у місяці? То ця перевірка уже не спрацює. Дивися апішку js date щоб діставати останній десь https://stackoverflow.com/questions/222309/calculate-last-day-of-month

2021-11-15 18:45 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +    let k = 0;
Давай змінним внятні назви. Ніколи ніяких скорочень до однолітерних назв

2021-11-15 18:45 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +            mondayArray[k] = i;
використовуй для додавання елементів метод `.push`

2021-11-15 18:45 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +    return long.includes(month);
Те ж саме що в першому комменті. js тобі може дати кількість днів у місяці і можна просто звірити чи там 31 день чи ні

2021-11-15 18:45 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +    }
Те ж саме з діставанням останьої дати місяця

2021-11-15 18:45 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/4-modules/time.js
> +    }
Те ж саме з діставанням останьої дати місяця

2021-11-15 21:17 UTC, TArch64 approved these changes

2021-11-15 21:17 UTC, merged