4-modules
MastersAcademy/frontend-course-2021 pull request #141
Opened 2021-11-11 16:15 UTC by BuzRom

https://buzrom.github.io/frontend-course-2021/homeworks/roman.buzukov_BuzRom/4-modules/

I didn't get how to do asterisk task with given two functions.
In my opinion, the easiest way is to use 'timezone'.

2021-11-12 17:59 UTC, electrovladyslav commented
> https://buzrom.github.io/frontend-course-2021/homeworks/roman.buzukov_BuzRom/4-modules/
> 
> I didn't get how to do asterisk task with given two functions. In my opinion, the easiest way is to use 'timezone'.

At least you should realize those two functions `subtractHours` and `addHours`.
And further, you should use it to calculate the time for a given city based on local time.
Sorry, but without it, I can't count the task with an asterisk as done.

2021-11-12 18:00 UTC, electrovladyslav requested changes

2021-11-12 18:00 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/js/time.js
> +    return (weeks[0].length < weeks[weeks.length - 1].length)
same here
Store `store weeks[0].length` and `weeks[weeks.length - 1].length` to the proper named vars

2021-11-12 18:00 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/js/time.js
> +    return (weeks[0].length < weeks[weeks.length - 1].length)
Or use `Math.max`))))

2021-11-12 18:00 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/index.html
> +                    <select class="container__list-select" data-daySelector>
Super

2021-11-12 18:00 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/index.html
> +                    <input class="item__input" type="date" data-userMonth>
type=date - 👍

2021-11-12 18:01 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/css/style.css
> +  height: calc(100vh - 100px);
Same here 
![image](https://user-images.githubusercontent.com/7540757/141513471-e12345e6-da73-40b9-bb34-ee5308a49816.png)

2021-11-12 19:06 UTC, BuzRom commented on homeworks/roman.buzukov_BuzRom/3-async/css/style.css
> -@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;900&display=swap");
This file from previous task '3-async'. I found one small bug and fix it.

2021-11-13 19:19 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/3-async/css/style.css
> -@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;900&display=swap");
Ok then

2021-11-13 19:19 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/css/style.css
> +  height: calc(100vh - 100px);
Cool 
![image](https://user-images.githubusercontent.com/7540757/141656497-442f4909-6b82-4a28-b26d-82127fd941a2.png)

2021-11-13 19:36 UTC, electrovladyslav requested changes

2021-11-13 19:36 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/js/asterisk.js
> +    return new Date(new Date(date).setHours(date.getHours() + hours)).toLocaleTimeString().split(':').join(' : ');
No need to make two Date objects. You can create one, setHours for it, and work with it further.

2021-11-13 19:36 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/js/asterisk.js
> +    return new Date(new Date(date).setHours(date.getHours() + hours)).toLocaleTimeString().split(':').join(' : ');
Also, this line is too long and difficult to understand. Split it into some simpler lines.

2021-11-13 19:36 UTC, electrovladyslav commented on homeworks/roman.buzukov_BuzRom/4-modules/js/time.js
> +    return (firstWeek < lastWeek)
Ok, it's much better now. Last [time](https://github.com/MastersAcademy/frontend-course-2021/pull/141#discussion_r748477612) I've mismatched: the `Math.min`  could be a choice
```
return Math.min(firstWeek, lastWeek)
```

2021-11-14 18:54 UTC, electrovladyslav approved these changes

2021-11-14 18:55 UTC, merged

2021-11-14 18:55 UTC, electrovladyslav commented
Super, thanx, for your job