init task
MastersAcademy/frontend-course-2021 pull request #143
Opened 2021-11-11 19:27 UTC by RevskyAndrey

https://revskyandrey.github.io/frontend-course-2021/homeworks/andrii.revskyi_RevskyAndrey/4--modules/

2021-11-13 18:32 UTC, TArch64 requested changes

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/index.html
> +                <br>
Не використовуй `<br>` для лаяутів. Зроби це флексами. Де потрібно додай ще один враппер

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/index.html
> +                <input value="2021-11-11" data-input class="data-input" placeholder="Enter Date" type="date">
інпут та лейбл тають бути звʼядані за допомогою id

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/index.html
> +                <p class="time" data-time>00:00:00</p>
Є тег з назвою `<datetime>`

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    return new Date(date);
`getCurrentDate` судячи з назви ця фукнція може повертати **тільки** поточну дату, але судячи по реалізації це не так

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    return 33 - new Date(date.getFullYear(), date.getMonth(), 33).getDate();
Що робить магічне число 33?

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    return 33 - new Date(date.getFullYear(), date.getMonth(), 33).getDate();
Чому не 27?

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    for (let i = 1; i <= getCountDaysOfMonth(currentDate); i++) {
`getCountDaysOfMonth` буде викликатися в кожній ітерації. Це точно потрібно?

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    } else if (firstDay > 1) {
Уникай великої кількості if + else в одній фунції. Що потрібно винеси в нову функцію, а де можна додай `return`. Це слово може писатися не тільки в кінця функції, а і всередині if блока

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    if (i < 10) {
Для такого є `padStart`

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/css/style.css
> +  width: 70%;
Замість вказання точних `width` в 2+ блоках краще використай флекси. Ти знаєш що блок з часом має займати n пікселів чи відсотків. Ти можеш вказати їх там а весь інший контент хай заповнює вільне місце

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/css/style.css
> +.time-box {
Зроби назви класів по бему

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/css/style.css
> +.data-input {
вводити можні тільки дані. Тому слово `data` тут не потрібно

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/css/style.css
> +  height: 25px;
....Ти ж знаєш що цю зірочку було не обовʼязково робити?

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/css/style.css
> +  height: 25px;
це текстовий елемент тому старайся тут не вказувати точних розмірів

2021-11-13 18:32 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/css/style.css
> +  display: flex;
тут не потрібен флекс. Просто додай до селекта таймзони `width: 100%;`

2021-11-14 15:49 UTC, RevskyAndrey commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    return new Date(date);
сменил название функции

2021-11-14 15:51 UTC, RevskyAndrey commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    return 33 - new Date(date.getFullYear(), date.getMonth(), 33).getDate();
опечатался - нужно 32  - попытка взять 1 число следующего месяца

2021-11-14 15:52 UTC, RevskyAndrey commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    if (i < 10) {
это можно использовать только для часов  -  так как если использовать на минуты получится не красиво  к примеру 
 1: 1:10

2021-11-14 15:53 UTC, RevskyAndrey commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/css/style.css
> +  height: 25px;
а с ней красивее

2021-11-14 17:39 UTC, RevskyAndrey commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    } else if (firstDay > 1) {
в следующий раз постараюсь

2021-11-15 18:35 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    return 33 - new Date(date.getFullYear(), date.getMonth(), 33).getDate();
@RevskyAndrey А якщо у місяця буде не 31 день? А 27 чи 30?

2021-11-15 18:36 UTC, TArch64 commented on homeworks/andrii.revskyi_RevskyAndrey/4-modules/js/time.js
> +    } else if (firstDay > 1) {
В слідуючий раз потрібно комменти правити одразу, а не писати що потім якось зроблю 🙂

2021-11-15 20:12 UTC, TArch64 approved these changes

2021-11-15 21:16 UTC, merged