4 modules
MastersAcademy/frontend-course-2021 pull request #145
Opened 2021-11-11 22:47 UTC by SanSandru4

2021-11-11 22:52 UTC, SanSandru4 commented
https://sansandru4.github.io/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/

2021-11-12 12:08 UTC, electrovladyslav requested changes

2021-11-12 12:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/time.js
> +        mondayInMonth.setDate(mondayInMonth.getDay() + 1);
А я думаю, почему твоя страничка виснет. А это из-за этого бесконечного цикла. 
Это ты так хочешь на следующий месяц перейти? Тогда можно просто setMonth использовать, без цикла.

2021-11-12 12:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/time.js
> +    const mondayInMonth = new Date(year, month - 1, day);
Эта переменная не содержит в себе количество понедельников в месяце. Это выбранная дата. Поменяй название.

2021-11-12 12:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/time.js
> +        mondays.push(new Date(mondayInMonth.getTime()).getDate());
Зачем так сложно? Я не могу понять, что тут происходит. 
Может просто найти первый понедельник, и потом прибавлять по 7 дней, пока месяц не кончится? Это и будут числа понедельников.

2021-11-13 16:25 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/time.js
> +        mondays.push(new Date(mondayInMonth.getTime()).getDate());
У мене на цій функції мозок зламався((( і видав таке вирішення

2021-11-13 19:51 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/index.html
> +                <div class="out-information" data-short-week></div>
Я так и не понял системы, по которой ты ставишь  `-` , ` _` и `__`
Если это бэм, то блок может называться, например `calendar` или как у тебя `main`
Элемент с датапикером может называться `main__input-date` - сначала название блока, потом, после `__` название элемента. Если название элемента состоит из двух слов, они разделяются `-`.
Все кнопки, раз они выглядят одинаково, будут, например `main__btn`. Если среди всех этих одинаковых кнопок, одна будет недоступна, то этот стиль навешивается через модификатор `main__btn main__btn-disabled`
И т.п.

2021-11-13 19:53 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/index.html
> +                <div class="out-information" data-short-week></div>
Все эти классы нужны только для стилизации. Потому не обязательно в их названия впихивать всю логику элемента или блока (main__form_manipulation-calendar). Достаточно дать уникальное название, по которому ты сможешь их застелизовать (main, main__input, main__text,...)

2021-11-13 20:18 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/time.js
> +            dateDay.setDate(dateDay.getDay() + 1);
Здесь ошибка, которая приводит к бесконечному циклу, если выбираешь, например 5.08.2021.
В скобочках нужен день месяца а не номер дня недели.

2021-11-13 20:18 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/time.js
> +        mondays.push(new Date(mondayInMonth.getTime()).getDate());
Ну ок, вроде работает, если долго повтыкать, можно понять, что к чему)))

2021-11-13 20:21 UTC, electrovladyslav requested changes
Поправь бесконечный цикл

2021-11-14 15:21 UTC, SanSandru4 commented
Наче все переробив, дякую каменти)))

2021-11-14 15:22 UTC, SanSandru4 commented
Наче все зробив, мозок все одно поломаний)))) дякую за каменти))

2021-11-14 19:00 UTC, electrovladyslav commented
> , мозок все одно поломаний))))
Так и будет первое время, это же js 🤷‍♂️

2021-11-14 19:11 UTC, electrovladyslav requested changes

2021-11-14 19:11 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/index.html
> +            <main class="main__form" data-main-form>
Если это [БЭМ](https://ru.bem.info/methodology/naming-convention/#%D0%B8%D0%BC%D1%8F-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0) то на верхнем уровне блока должно быть сам блок. Без элемента. То есть тут у тебя начинается разметка блока, это его корень. Потому просто `main`  без `__form`

2021-11-14 19:11 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/index.html
> +            <main class="main__form" data-main-form>
А в остальном, всё ок, спасибо что прислушался к рекомендациям.

2021-11-14 19:11 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/4-modules/index.html
> +            <main class="main__form" data-main-form>
Маленький лайфках - для удобства разметки, атрибут класса стоит писать самым первым в тэге. Так будет проще его потом искать глазами в разметке:
```
<h3 class="main__data-name">Data:</h3>
<input class="main__input-data" type="date" name="calendar"  data-take-calendar>
<input class="main__btn" type="button" value="Get month monday"  data-get-monday>
...
```

2021-11-14 21:03 UTC, SanSandru4 commented
Зробив правки по лайфхаку)) Дякую!

2021-11-15 09:16 UTC, merged