4 modules
MastersAcademy/frontend-course-2021 pull request #146
Opened 2021-11-11 23:07 UTC by DmitriyKondaurov

2021-11-12 13:34 UTC, MZabolotnev commented
Добавь ссылку на github pages пожалуйста.

2021-11-12 23:21 UTC, DmitriyKondaurov commented
> Добавь ссылку на github pages пожалуйста.
https://dmitriykondaurov.github.io/frontend-course-2021/
![image](https://user-images.githubusercontent.com/23703403/141594485-2ee57809-986e-49e6-a90d-8e69fd42df69.png)

2021-11-13 18:33 UTC, MZabolotnev requested changes
По ссылке должна открываться твоя последняя домашка. То есть ссылка должна быть вот такая:
[https://dmitriykondaurov.github.io/frontend-course-2021/homeworks/dmytro.kondaurov_DmitriyKondaurov/4-modules/index.html](https://dmitriykondaurov.github.io/frontend-course-2021/homeworks/dmytro.kondaurov_DmitriyKondaurov/4-modules/index.html)

Баг с **getMondaysOfMonth** 
![image](https://user-images.githubusercontent.com/25617217/141655230-eef0c545-8ac2-488d-8c1d-54b8a0e76d02.png)

![image](https://user-images.githubusercontent.com/25617217/141655256-7f1174f9-d7a3-4774-9603-cc574f26fbfb.png)




Так же вижу что **shortestWeekDaysNumber** работает не так как ожидается, результат = 1, по факту же должно быть 2:
![image](https://user-images.githubusercontent.com/25617217/141654913-56bd3a48-baf9-4214-8e8d-d1404e64af79.png)
![image](https://user-images.githubusercontent.com/25617217/141654961-0c76a6d3-e12b-4243-990d-9b027b0dbf11.png)
Этот баг воспроизводится и на других месяцах.

2021-11-13 20:18 UTC, DmitriyKondaurov commented
![image](https://user-images.githubusercontent.com/23703403/141657798-d25a12c7-a1ea-4c11-9c24-31f30db997ad.png)
![Screenshot from 2021-11-13 22-16-23](https://user-images.githubusercontent.com/23703403/141657865-af0abc3b-b542-482d-a75b-e295e15ecc78.png)
не пойму почему так, у меня все ок....

2021-11-13 20:22 UTC, DmitriyKondaurov commented
Почему в вашем скрине одни и теже даты в "Get month Monday"?  после нажатия на кнопку  с разными вводными заначениями выдаёт один и тотже результат ?

2021-11-13 20:25 UTC, DmitriyKondaurov commented
Во втором скрине результат тоже правильный при дате 22 февраля 2022 года понедельники будут [7, 14, 21, 28] . а тот месяц с которым вы сравниваете не понятно с какого года ...

2021-11-13 21:15 UTC, MZabolotnev approved these changes

2021-11-13 21:15 UTC, merged