4 modules
MastersAcademy/frontend-course-2021 pull request #147
Opened 2021-11-12 00:36 UTC by turuta7

2021-11-12 19:22 UTC, DrSmile444 requested changes
Пофікси лінтери @turuta7

2021-11-13 18:01 UTC, TArch64 commented
@turuta7 В цьому пулл реквесті не має бути файлів завдання по іншій домашці

2021-11-13 18:01 UTC, TArch64 commented
Додай лінк на гітхаб пейджес

2021-11-13 18:35 UTC, TArch64 requested changes
Завдання не виконано згідно вимог. Немає модуля `time.js` і немає функції в ньому

2021-11-13 20:19 UTC, closed without merging