4-modules
MastersAcademy/frontend-course-2021 pull request #150
Opened 2021-11-12 07:54 UTC by Vladimior

https://vladimior.github.io/frontend-course-2021/homeworks/volodymyr.khrushch_Vladimior/4-modules/index.html

2021-11-12 16:26 UTC, NickCashFlow requested changes
функционал не работает так как описано в issue, такой pull request не принимается, функцинал должен работать в соответствии с issue

2021-11-12 17:12 UTC, Vladimior commented
Что именно не так можно сказать?

2021-11-12 17:17 UTC, NickCashFlow commented
> Что именно не так можно сказать?

после выбора даты и при нажатии на кнопки данные меняються

2021-11-12 17:23 UTC, Vladimior commented
> > Что именно не так можно сказать?
> 
> после выбора даты и при нажатии на кнопки данные не меняються

У меня все работает. Сейчас скину в телегу запись.

2021-11-12 19:47 UTC, NickCashFlow requested changes

2021-11-12 19:47 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/script.js
> +const buttonShortWeek = document.querySelector('[data-shortWeek]');
если хочешь сообщить в названии переменной, что это элемент, то лучше использовать button в конце и полностью соблюдать camelCase, например, fullMonthButton

2021-11-12 19:47 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/script.js
> +    const inputLongMonth = new Date(time.value);
здесь лучше использовать MonthLongVal, аналогично и в других обработчиках

2021-11-12 19:47 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/script.js
> +    const Mounth = inputLongMonth.getMonth();
в js не принято называть переменные и функции с большой буквы, так называют только классы и функции, которые потом используют с оператором new

2021-11-12 19:47 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/time.js
> +    }
этот метод можно упростить, можно начать с switch

2021-11-12 19:47 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/index.html
> +            <article class="content_case">
а зачем article вложен в article?

2021-11-12 19:47 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/css/style.css
> +.content_case {
судя по названиям классов нужно пересмотреть лекцию по БЭМу

2021-11-12 19:47 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/script.js
> +    const Mounth = inputFullWeek.getMonth() + 1;
аналогично

2021-11-15 07:39 UTC, NickCashFlow requested changes

2021-11-15 07:39 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/time.js
> +        mondays.push(` ${pushDate.getDate()}`);
а зачем здесь темплейт литерал при пуше?

2021-11-15 07:39 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/time.js
> +    if (firstDayOfMonth === 7 && lastDayOfMonth >= 1) {
здесь нужно упростить, например, использовать цикл с проверками

2021-11-15 07:39 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/time.js
> +export function isMonthLong(Month, Year) {
здесь также аргументы функции не задаются с большой буквы

2021-11-15 07:39 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/script.js
> +});
и тебе не кажется, что в этих функциях много чего общего и можно переписать так, чтобы код не повторялся?

2021-11-15 09:13 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/script.js
> +});
есть, видел это, но когда выводил все одинаковые переменные в глобальные перестает  правильно отработывать код.

2021-11-15 09:20 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/time.js
> +    if (firstDayOfMonth === 7 && lastDayOfMonth >= 1) {
цикл с проверками ? я пробывал его переписывать в switch, и что бы он правильно заработал, у меня switch вышел еще больше по размеру. 
я сегодня навряд физически успею это сделать.

2021-11-15 09:24 UTC, Vladimior commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/time.js
> +        mondays.push(` ${pushDate.getDate()}`);
что бы добавить пробелы  и красиво вывести, без этого оно выводит все одной слитной строкой

2021-11-15 14:35 UTC, NickCashFlow commented on homeworks/volodymyr.khrushch_Vladimior/4-modules/js/time.js
> +        mondays.push(` ${pushDate.getDate()}`);
можно просто склеивать элементы массива через пробел в момент вывода

2021-11-15 18:45 UTC, NickCashFlow approved these changes

2021-11-15 20:23 UTC, merged