init
MastersAcademy/frontend-course-2021 pull request #155
Opened 2021-11-12 18:10 UTC by AndriiCold

https://andriicold.github.io/frontend-course-2021/homeworks/andrii.kholodenko_AndriiCold/4-modules/

2021-11-13 18:52 UTC, TArch64 requested changes

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/css/style.css
> +.input_date {
```suggestion
.button,
.input_date {
```

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/index.html
> +        <title>Data</title>
```suggestion
        <title>Date</title>
```
Data це дані, а Date це дата

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/index.html
> +            <div data-out-fridays></div>
використай більш семантичні теги для тексту

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/index.html
> +        <input type="date" class="input_date" data-input-date>
Старайся додавати до інпутів лейбли

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/main.js
> +const outMonthLong = document.querySelector('[data-out-month-long]');
додавай до **всіх** зміних де лежать елементи дому закінчення `El`

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/main.js
> +import * as module from './time.js';
Не використовуй імпорти через `*`. У більш складних проектах модулів будуть всякі вебпаки а * дуже погано впливає на розмір фінального js

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/main.js
> +    buttonMonthLong.addEventListener('click', () => {
Ці всі лістнери потрібно додавати при **кожному** зміні дати у філді?

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/main.js
> +        outShortWeek.innerText = module.shortTestWeekDaysNumber(inputDate);
чому в назві є `test`?

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/time.js
> +export function getMondayOfMonth(date) {
Ця фукнція в назві має `get` і коли щось називається так то воно не має ніяк впливати на дані навкого, але поточна реалізація змінює свій аргумент. Це не ок бо через це в майбутньому можуть випливати дивні баги бо по назві ніхто не здогадається що вона щось змінює. Якщо тобі потрібно робити якісь маніпуляції з аргументом то краще зроби його копію

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/time.js
> +export function getMondayOfMonth(date) {
На всяк випадок спитаю: ти знаєш що таке передача даних по посиланню та по значенню в js?

https://www.google.com/search?q=js+pass+variable+by+reference&rlz=1C5CHFA_enUA917UA918&sxsrf=AOaemvJpEaljERQKwjnTZVJeV84C14kqqw%3A1636829207365&ei=FwiQYY3WFcuvrgSKtpj4Ag&oq=js+pass+variable+by+reference&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEIAEMgYIABAFEB46BwgjELADECc6BwgAEEcQsAM6BggAEAcQHjoICAAQBxAFEB5KBAhBGABQwgFY4wxg6xBoA3ACeACAAWuIAdIDkgEDMy4ymAEAoAEByAEJwAEB&sclient=gws-wiz&ved=0ahUKEwjNvdn7_5X0AhXLl4sKHQobBi8Q4dUDCA4&uact=5

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/time.js
> +        return 'True';
використовуй bolean тип даних для такого

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/time.js
> +    } else if (lastDayDate.getDay() === 0) {
забагато `if + else if` і через це важко розуміти що відбувається в цій функції. Перероби це за допомогою `if + return`

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/time.js
> +            arrayFullWeeks.push('week');
Замість такого краще зроби числову зміну та роби її інкремент

2021-11-13 18:52 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/time.js
> +        if (fullWeeksDate.getDay() === 0) {
зорбий цю функцію на декілька менших

2021-11-14 13:51 UTC, AndriiCold commented
Я виправив зауваження, подивыться будь ласка

2021-11-14 14:01 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/main.js
> +import * as module from './time.js';
@AndriiCold  Це коммент не пофікшений

2021-11-14 14:06 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/4-modules/script/time.js
> +    return false;
```suggestion
    return lastDayOfMonth === 31;
```

2021-11-14 14:07 UTC, TArch64 commented
Пофікси 2 остані комменти і я замержу

2021-11-14 14:18 UTC, AndriiCold commented
Виправив)

2021-11-14 14:23 UTC, TArch64 commented
@AndriiCold Залишився ще один коммент 
![image](https://user-images.githubusercontent.com/29049264/141685181-85dfe87f-17ad-43ac-a95b-4765512f4099.png)

2021-11-14 15:55 UTC, AndriiCold commented
Виправив, вибачаюсь не помітив

2021-11-14 16:20 UTC, TArch64 approved these changes

2021-11-14 16:21 UTC, merged