4 modules
MastersAcademy/frontend-course-2021 pull request #159
Opened 2021-11-13 14:22 UTC by VladislavMedvedyev

2021-11-13 15:44 UTC, NickCashFlow commented
есть конфликты с homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/index.html, конфликты нужно отрезолвить, также нет ссылки на github pages

2021-11-13 21:27 UTC, VladislavMedvedyev commented
Поправил, добавил ссылку на гитхаб пейджес. Но есть одно но. Там отображается только файл README.md а не мой код. Как это исправить? Как указать  на конкретный HTML элемент?
https://vladislavmedvedyev.github.io/frontend-course-2021/

2021-11-14 17:06 UTC, NickCashFlow requested changes
и порезолвай конфликты

2021-11-15 18:41 UTC, NickCashFlow approved these changes

2021-11-15 18:43 UTC, merged