4-modules
MastersAcademy/frontend-course-2021 pull request #161
Opened 2021-11-13 20:23 UTC by skyprog

2021-11-13 20:25 UTC, skyprog commented
https://skyprog.github.io/frontend-course-2021/homeworks/roman.kushnirenko_skyprog/4-modules/index.html

2021-11-14 18:52 UTC, electrovladyslav requested changes

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +const currentTime = document.querySelector('[data-current-time]');
По [условию](https://github.com/MastersAcademy/frontend-course-2021/issues/134#issue-1048792821) задания, надо было реализовать в этом модуле методы с определёнными именами (getMondaysOfMonth, isMonthLong). Их здесь нет(((

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +const inputDate = document.querySelector('.input');
Из js стоит искать элементы по дата-атрибутам, тем более ты делаешь это для всех остальных элементов

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +    function getMondays() {
Объявление этой функции надо было вынести в модуль и импортировать её оттуда. 
Вообще объявление одной функции внутри другой - это bad practice. Потом такое сложно понимать и поддерживать.

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +mondaysBtn.addEventListener('click', () => {
Если кликнуть на эту кнопку при пустой дате (не выбранной в инпуте), получается бесконечный цикл и страница зависает. 
Обычно, в таких случаях ставят проверку, есть ли дата и показывают сообщение, мол выберите дату сперва. 
Или просто можно заблокировать все кнопки, и раздизэйблить только тогда, когда дата была выбрана.
![image](https://user-images.githubusercontent.com/7540757/141693800-e39773d7-4a99-44ba-befc-9b79c25bb404.png)

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +}, 0);
Тут логично поставить задержку в 1000 мс хотя бы. А то ты так перегружаешь движок, заставляя считать бесконечно без задержки

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +        setInterval(cityTime, 0, 'europe/kiev');
Интересно, не часто увидишь такое прокидывание аргументов в таймаут/интервал третьим аргументом при вызове.
Вообще интервал работает так себе. Обычно все используют таймаут с функцией, в конце которого этот же таймаут ставиться повторно. Получается поведение интервала, но с постоянной задержкой, а не с плавающей, как в интервале - https://learn.javascript.ru/settimeout-setinterval#rekursivnyy-settimeout

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/index.html
> +        <main class="all__date">
Не понял системы названий классов. Какие разделители между словами ты используешь? Желательно делать это единообразно, если это не какая-то методология. 
У тебя же и `_` и `__` и просто слитные названия `class="getdate"`

2021-11-14 18:52 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +const currentTime = document.querySelector('[data-current-time]');
И задумка была в том, что тут ты реализуешь эти кусочки логики, и будешь их экспортировать. 
Методы должны принимать параметры, их как-то обрабатывать, и отдавать. результат.
А всю работу со страницей будешь делать в другом файле, где будешь применять эти заимпортированные методы.

2021-11-14 19:27 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +    getFullWeeksMonth(mm, year, 1);
Есть такой антипатерн, "[магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))" 
Чтобы его избежать заводят константу, в названии которой объясняют значение:
```
const WEEK_START_NUMBER = 1
getFullWeeksMonth(mm, year, WEEK_START_NUMBER)
```

2021-11-14 19:28 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +    getFullWeeksMonth(mm, year, 1);
Кстати, `mm` тоже так себе название для переменной. Назови по аналогии с соседней -  `month`

2021-11-14 19:34 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +    getFullWeeksMonth(mm, year, 1);
И от функции с названием `getFullWeeksMonth` ждёшь того, что она вернёт полные недели месяца. То, что она что-то выводит на страницу - неприятный сюрприз. 
Надо стремиться к тому, чтобы функции/методы выполняют минимальный кусочек логики, и из их названия явно следует, что они делают. 
А сложные действия достигаются последовательным выполнением таких функций. В идеале, тебе не надо будет заглядывать в то, что написано внутри функций - достаточно посмотреть на название чтобы понять, что она делает.

2021-11-14 19:36 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +export function cityTime(city) {
В названии функции должен быть глагол. `cityTime` - переменная содержащая время города.

2021-11-14 19:37 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +export function numberOfDays(iMonth, iYear) {
Тоже спорное название. И для функции, и для параметров. `iMonth` - что-то связанное с Apple?

2021-11-14 19:39 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +    let trueOrFalse;
Тут ты отталкиваешься от значения переменной. А надо отталкиваться от её смысла. И если переменная содержит логическое значение, она должна начинаться с `is`. Здесь это `isMonthLong`

2021-11-15 18:12 UTC, skyprog commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +        setInterval(cityTime, 0, 'europe/kiev');
Спасибо большое за все пожелания и просмотр задания, нужно еще поизучать эту тему. Третий аргумент я попробовал ради эксперемента, сработало

2021-11-15 18:48 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +        clearInterval(currentOclock);
Если эта строчка выполняется во всех трёх условиях, есть смысл вынести её, и поставить до первого `if`

2021-11-15 18:48 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +        clearInterval(currentOclock);
Если ты несколько раз проверяешь одну и ту же переменную, стоит использовать [switch](https://learn.javascript.ru/switch)

2021-11-15 18:48 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +const currentTime = document.querySelector('[data-current-time]');
Ещё раз: в этом модуле не должно быть работы со страницей. Тут только реализуются методы из условия, которые обрабатывают дату, которую они получают из параметра, и возвращают результат. 
В файле, где тебе нужно их использовать, ты
1. Импортируешь метод.
2. Вызываешь его, передавая дату, как параметр.
3. Метод возвращает результат, и ты показываешь его на странице. 

Потому строки 1-5 лишние в этом модуле.

2021-11-15 18:48 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +const currentTime = document.querySelector('[data-current-time]');
Не реализован метод `shortestWeekDaysNumber ` из [условия](https://github.com/MastersAcademy/frontend-course-2021/issues/134#issue-1048792821)

2021-11-15 18:48 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/time.js
> +    mondaysShow.textContent = dateMondays;
Вот тут ты должен возвращать этот массив, а не рендерить его на страницу. 
Так же и в других методах

2021-11-15 18:51 UTC, electrovladyslav requested changes

2021-11-15 18:51 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +    function getDateOfInput() {
Не стоит объявлять функцию внутри обработчика. 
Объяви её снаружи, а здесь вызови, передав, всё что нужно для её работы в параметрах.

2021-11-15 18:55 UTC, electrovladyslav commented on homeworks/roman.kushnirenko_skyprog/4-modules/js.js
> +    const weekStartNumber = 1;
Если ты не меняешь значение этой переменной, то это не переменная, а константа. Обычно они объявляются в начале файла/модуля и записываются [аперкейсом](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const#basic_const_usage)

2021-11-15 18:56 UTC, electrovladyslav commented
Можно было сконцентрироваться на обязательном задании, оставив задание со звёздочкой на потом. Шансов сдать было бы больше.

2021-11-15 20:22 UTC, closed without merging