add homework4 Turuta
MastersAcademy/frontend-course-2021 pull request #162
Opened 2021-11-13 20:31 UTC by turuta7

2021-11-13 20:48 UTC, turuta7 commented
https://turuta7.github.io/frontend-course-2021/homeworks/Aleksandr.Turuta_turuta7/4-modules/index.html

2021-11-14 13:18 UTC, TArch64 requested changes

2021-11-14 13:18 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-modules/time.js
> +    return `[${counter}]`;
Чому значення що повертається обернуто в `[]`? А якщо потрібно буде потім значення без скобок? В завданні описано що має повертатися масив тому зроби це так. Це форматування -- особливість роботи твого інтерфейсу і ця логіка не має залежати від нього

2021-11-14 13:18 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-modules/time.js
> +    getMondaysOfMonth,
Пиши експорт біля функцій що експортуються

2021-11-14 13:18 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-modules/time.js
> +    return false;
```suggestion
    return daysInMount === 31;
```

2021-11-14 13:18 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-modules/time.js
> +    const daysInMount = new Date(year, month, 0).getDate();
1. Подивися як перекладається слово Mount
2. Можна замінити на `dayCount`

2021-11-14 13:18 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-modules/time.js
> +    let date;
чому ця зміна обʼявляється за межами циклу? Це необхідно?

2021-11-15 18:51 UTC, TArch64 requested changes

2021-11-15 18:51 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/4-modules/script.js
> +};
Почитай, будь-ласка, уважно опис завдання https://github.com/MastersAcademy/frontend-course-2021/issues/134

2021-11-15 20:07 UTC, turuta7 commented
Змінив

2021-11-15 20:07 UTC, TArch64 approved these changes

2021-11-15 20:11 UTC, merged