5-rxjs
MastersAcademy/frontend-course-2021 pull request #167
Opened 2021-11-18 22:28 UTC by SanSandru4

2021-11-18 22:29 UTC, SanSandru4 commented
https://sansandru4.github.io/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/

2021-11-18 22:34 UTC, SanSandru4 commented
Влад, привіт. Чекаю твоїх коментів)

2021-11-19 07:41 UTC, electrovladyslav commented
> Влад, привіт. Чекаю твоїх коментів)

Привет, лучше писать в Тележку. Письма не всегда просматриваю сразу, как они приходят.

2021-11-19 07:50 UTC, SanSandru4 commented
Привіт, не хотів тебе випадково розбудить, повідомлення прилетить в час ночі, а звук на телефоні не вимкнений

2021-11-19 09:08 UTC, electrovladyslav requested changes

2021-11-19 09:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/style.css
> +@media screen and (max-width: 520px) {
Если медиа-квери одинаковые, зачем разбивать их на два?

2021-11-19 09:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/style.css
> +  .header__nav a.icon { display: block; }
В открытом состоянии иконка должна меняться на крестик. Это минимальный интерактив
![image](https://user-images.githubusercontent.com/7540757/142595324-bb30d077-1aa2-45fc-b7ea-9ed4121e3fb5.png)

2021-11-19 09:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/style.css
> +  .section { width: 100%; }
А тут переходы на новую строку куда делись? Не скопипастились?)))

2021-11-19 09:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +    filter((value) => (value > 50)),
У тебя меню не появляется, когда скролишь вверх. Возможно надо взять два значения вместо одного (`pairwise`), и вычислять разницу между ними. А то сейчас у тебя логика работает только в пределах верхних 50 пикселей.

2021-11-19 09:08 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +fromEvent(window, 'scroll').pipe(
[DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself) - если код в строках 16-20 и 22-26 почти идентичный, может его можно переписать на один фрагмент?

2021-11-20 07:54 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/index.html
> +                            <i class = "fa fa-times" style="display: none" data-attr-times></i>
Дай нормальные имена классов, по БЭМу этим иконкам и обращайся к ним из css.
Нет никакой надобности прописывать здесь инлайном `style="display: none"` - вынеси это в css

2021-11-20 07:54 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/index.html
> +                        <a class = "icon" href = "javascript:void(0);" data-min-menu>
Зачем эта штука, что она делает?
```
href = "javascript:void(0);"
```

2021-11-20 07:54 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/index.html
> +                        <a class = "header__nav_menu_link" href = "#news">News</a>
Смотри, у тебя набор одинаковых элементов - пунктов меню. Из соображений семантики, такие наборы одинаковых элементов размечают специально сделанным для этого тэгом - `ul`. Это [ненумерованный список](https://developer.mozilla.org/ru/docs/Web/HTML/Element/ul#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BE%D0%B1_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8)
Замени `div. header__nav_menu` на  `ul.header__nav_menu` и оберни ссылки в `li`

2021-11-20 08:47 UTC, electrovladyslav requested changes

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/style.css
> +  .header__nav .header__nav-link { display: none; background-color: #000;}
тут куда-то пропали все переводы на новую строку. 
Внутри медиа-квери стили можно размечать так же как и снаружи, не одной строкой. 
Поправь плиз, неудобно читать

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/style.css
> +  .header__menu.responsive { position: absolute; left: 0; margin-top: 40px; width: 100%; display: flex; flex-direction: column; z-index: 2; }
`responsive` - это модификатор открытого меню. Назови по БЭМ, и поменяй название на `opened` например.

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +    if (x.className === 'header__menu') {
в таких случаях надо пользоваться методами  свойства [classList](https://developer.mozilla.org/ru/docs/Web/API/Element/classList): contain, add, remove, toggle.
А то ошибёшься на пробельчик -  и вся логика сломается.

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +    const x = document.querySelector('[data-nav-menu]');
Назови эти переменные согласно тому, что они в себе содержат:
- элемент копки меню
- элемент иконки открытого меню
- ...
Из названий `x` и `times` ничего не понятно.

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +    // pairwise(window.pageYOffset[0] - window.pageYOffset[1]),
оператор  [pairwise](https://www.learnrxjs.io/learn-rxjs/operators/combination/pairwise) вызывается без параметров.

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +    filter((value) => (value > 50) || (value < window.pageYOffset)),
тут у тебя в  `value` прилетает из предыдущей строчки pageYOffset и ты его сравниваешь с pageYOffset опять.
Тут надо смотреть на сколько изменился этот pageYOffset. Для этого используй  pairwise, чтобы брать не текущее значение, а текущее и предыдущее. Смотри на разницу и фильруй.

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +    .subscribe(() => { headerEl.classList.toggle('header--hidden'); });
Тут не понятно, когда ты накидываешь этот класс, когда снимаешь. 
Тебе нужны определённые условия:
- если скрол вниз - прячем
- если скрол вверх - показываем

2021-11-20 08:47 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/script.js
> +    .subscribe(() => { headerEl.classList.toggle('header--hidden'); });
Советы:
- перечитай, что делает каждый из операторов, предложенных тебе в [описании задания](https://github.com/MastersAcademy/frontend-course-2021/issues/163#issuecomment-971333017)
- Напиши, как ты будешь обрабатывать скрол, по шагам:
** ползователь проскролил, тебе прилетела в `pipe` величина скрола
** ты взял предыдущую величину и передал дальше обе- оператор...
** из двух величин вычислил изменение величины и передал дальше - оператор...
** пофильтровал и передал дальше - оператор...
** ...
** ...

2021-11-20 10:37 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/index.html
> +                            <i class = "fa fa-times" style="display: none" data-attr-times></i>
Влад, перейменувать ці класи (fa fa-bars, fa fa-times) не можу, вони імпортовані(((

2021-11-20 10:39 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/style.css
> +  .header__nav .header__nav-link { display: none; background-color: #000;}
не міг розібратися, а потім правила лінтера почитав - зробив))

2021-11-20 11:01 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/5-rxjs/index.html
> +                            <i class = "fa fa-times" style="display: none" data-attr-times></i>
Так ты можешь добавить бэм-класс к уже существующим классам с иконочными шрифтами

2021-11-20 17:43 UTC, merged