5-rxjs
MastersAcademy/frontend-course-2021 pull request #171
Opened 2021-11-19 12:35 UTC by svkul

https://svkul.github.io/frontend-course-2021/homeworks/serhii.kulakivskyi_svkul/5-rxjs/

2021-11-19 13:10 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/animations.css
> +    -webkit-transform: translateY(-1000px);
А зачем ты используешь префиксы?

2021-11-19 13:11 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/animations.css
> +  -webkit-animation: slide-out-top .5s cubic-bezier(.55, .085, .68, .53) both;
А зачем ты используешь префиксы?

2021-11-19 13:23 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/animations.css
> +    -webkit-transform: translateY(-1000px);
Для лучшей поддержки

2021-11-19 13:23 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/animations.css
> +  -webkit-animation: slide-out-top .5s cubic-bezier(.55, .085, .68, .53) both;
Для лучшей поддержки

2021-11-19 13:26 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/js/index.js
> +        if (headerWrapperEl && headerEl) {
у тебя еще времечко есть, попробуй это сделать с меньшим количеством `if`
Побей на логические куски, вынеси в функции и тд.

2021-11-19 13:28 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/index.css
> +.header.header--button .logo,
.header.header--button
.header.header--button .header__nav
.header.header--button .header__text

а зачем тебе такая вложенность и специфичность? Без нее никак?

2021-11-19 13:37 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/index.html
> +        <div class="header__wrapper" data-header-wrapper>
что то мне подсказывает что это враппер тебе ненужен, ты его якобы используешь в коде, но как то смысла нет в этом.

2021-11-19 13:43 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/index.html
> +                        <a class="header__nav-item" href=".">Новости</a>
Область клика у ссылок особенно в навигации, должна быть максимальной, у тебя сейчас в нее максимально сложно попасть
https://bit.ly/32bvPzD

2021-11-19 13:44 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/index.html
> +                    <button class="header__nav-button" type="button" data-nav-btn>
Какую функцию выполняет эта кнопка? Я на странице не вижу вообще?

2021-11-19 13:47 UTC, smithua requested changes
Привет, исправь пожалуйста все комментарии и пингуй меня в телеге.

2021-11-19 13:53 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/index.html
> +                    <button class="header__nav-button" type="button" data-nav-btn>
Это бургер. Нужно смотреть на разрешении меньше 768px

2021-11-19 13:59 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/animations.css
> +    -webkit-transform: translateY(-1000px);
Fixed

2021-11-19 13:59 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/animations.css
> +  -webkit-animation: slide-out-top .5s cubic-bezier(.55, .085, .68, .53) both;
Fixed

2021-11-19 14:10 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/index.html
> +                        <a class="header__nav-item" href=".">Новости</a>
Fixed

2021-11-19 15:44 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/index.html
> +        <div class="header__wrapper" data-header-wrapper>
У меня хедер изначально fixed, враппером задаю отступ от контента.

2021-11-19 15:45 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/index.css
> +.header.header--button .logo,
Проапдейтил

2021-11-19 15:45 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/js/index.js
> +        if (headerWrapperEl && headerEl) {
Добавил функции: hideHeader & showHeader

2021-11-21 22:18 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/index.html
> +                        <a class="header__nav-item" href=".">Новости</a>
![image](https://user-images.githubusercontent.com/1473254/142780634-f6169a6e-2af1-4f2b-bcd8-f5ab9a060532.png)

Уже пусть будет как есть, я лишь добавлю что верстка самого хедера не совсем правильна. Я понимаю что фокус был на другом, просто в целом какие то подходы используются "интересные".
`line-height` - всегда должен быть с каким то базовым значением `(1.43, 1.5 etc...)` все остальные отступы должны задаваться `padding`, и когда я говорил что ссылке нужна больше область клика, это не только свеху/снизу, но и по ширине.
![image](https://user-images.githubusercontent.com/1473254/142780966-d9a20100-f308-4c5d-b962-b7b84aa333e2.png).
При изменении `line-height` у тебя когда текст пойдет в 2 строчки (обычный перенос) будет очень не красивая ситуация.
Так же `position: fixed` пойдет, но почитай про крутое свойство `position: sticky`

2021-11-21 22:25 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/css/animations.css
> +  -webkit-animation: slide-out-top .5s cubic-bezier(.55, .085, .68, .53) both;
эм, если бы это так и было то конечно, согласен 100%.
Информация по поддежке немного устарела, как мы говорили на лекциях, что бы знать наверняка, заходим на сервис по проверке поддежки и проверяем:
https://caniuse.com/?search=animation

2021-11-21 22:42 UTC, smithua commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/js/index.js
> +                    // eslint-disable-next-line no-unused-expressions
Решил считерить и что бы не казалось что много ифов переделать в тернарку, но тут линтер "ударил порукам", т.к нельзя такое запихнуть в тернарку(не изменяя код), ты решил добавить заветное `// eslint-disable-next-line no-unused-expressions`? 
`if (scrollDirection === DIRECTIONS.DOWN) {
      showHeader(buyNowBtnTopPosition);
  } else {
      hideHeader(buyNowBtnTopPosition);
  }`

Ай ай ай, нельзя так делать, если не можешь переписать этот кусок кода что было красивенько, оставь ифом. Не комментируй правила линта, без везких на то причин.

2021-11-21 22:44 UTC, smithua reviewed
Подфиксь пожалуйста комент по ESlint'y, если нет времени верни его в `if` и принимаю.

2021-11-22 06:56 UTC, svkul commented on homeworks/serhii.kulakivskyi_svkul/5-rxjs/src/js/index.js
> +                    // eslint-disable-next-line no-unused-expressions
Fixed

2021-11-22 08:04 UTC, smithua approved these changes
Good enough, thanks!

2021-11-22 08:04 UTC, merged