5-rxjs
MastersAcademy/frontend-course-2021 pull request #172
Opened 2021-11-19 13:52 UTC by MaksymSelenkov

https://maksymselenkov.github.io/frontend-course-2021/homeworks/maksym.selenkov_MaksymSelenkov/5-rxjs/index.html

2021-11-21 07:53 UTC, DrSmile444 requested changes

2021-11-21 07:53 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/5-rxjs/index.html
> +                <span class="header__logo">Logo</span>
In general, when you click on a logo, you expect to be redirected to the main page. For this purpose, you need to mark your logo as a link, not a span. I consider using the `a` tag here.

2021-11-21 07:53 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/5-rxjs/index.html
> +            <main class="main" data-main>
You have never used the 'data-main' selector. So it's better to make your code cleaner and remove it

2021-11-21 07:53 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/5-rxjs/app.js
> +        filter((v) => Math.abs(v[1] - v[0]) > 50),
[non-blocking] For me, it's better to destruct arguments and give them descriptive names. `previousScroll` and `currentScroll` sounds better, then `v[1]` and `v[0]`

2021-11-21 07:53 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/5-rxjs/app.js
> +        map((v) => v[0] < v[1]),
same here

2021-11-21 07:53 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/5-rxjs/app.js
> +    .subscribe((v) => {
v? What does it mean? It should describe is header hidden. Try to create a better name for this variable, please

2021-11-21 07:53 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/5-rxjs/app.js
> +        if (v) {
I'd like to say that you have `v` again, but do you really need this `v` and if? 😄
fromEvent returns PointerEvent, which always true, so this if is useless

2021-11-21 08:54 UTC, MaksymSelenkov commented
Header covers the main text. How to fix it?

2021-11-21 21:25 UTC, DrSmile444 submitted a review, later dismissed
Well done! Thank you 👍

2021-11-21 21:27 UTC, DrSmile444 commented
> Header covers the main text. How to fix it?

I think it's better to add additional space between the top of the page in this case. You can do it by using CSS.

2021-11-22 06:55 UTC, MaksymSelenkov commented
Thank you for review)

2021-11-22 11:12 UTC, DrSmile444 approved these changes

2021-11-22 17:02 UTC, merged