first commit
MastersAcademy/frontend-course-2021 pull request #174
Opened 2021-11-19 15:56 UTC by Nikkarchinskiy

2021-11-21 10:50 UTC, DrSmile444 requested changes
There's no JS. Nothing to review

2021-11-21 10:50 UTC, DrSmile444 commented on homeworks/nikita.karchinskiy_Nikkarchinskiy/5-rxjs/index.html
> +                    <menu class="menu-nav">
You don't need the `menu` tag here. It's better to remove it:
w3schools.com/tags/tag_nav.asp

2021-11-24 09:02 UTC, DrSmile444 requested changes
There's no Github Pages link still.

2021-11-24 09:02 UTC, DrSmile444 commented on homeworks/nikita.karchinskiy_Nikkarchinskiy/5-rxjs/rx.js
> +    if (e) {
What is e? I don't understand. Find a better name for this variable, please

2021-11-24 15:29 UTC, Nikkarchinskiy commented
Я сделал но линтер уже не пропускает название ветки, как я понял

2021-11-24 15:31 UTC, Nikkarchinskiy commented
https://nikkarchinskiy.github.io/frontend-course-2021/homeworks/nikita.karchinskiy_Nikkarchinskiy/5-rxjs/index.html

2021-11-24 16:27 UTC, DrSmile444 requested changes

2021-11-24 16:27 UTC, DrSmile444 commented on package.json
> +        "rxjs": "^7.4.0",
I see here an extra rxjs package

2021-11-24 17:15 UTC, closed without merging