5-rxjx
MastersAcademy/frontend-course-2021 pull request #175
Opened 2021-11-19 16:16 UTC by AndriiCold

https://andriicold.github.io/frontend-course-2021/homeworks/andrii.kholodenko_AndriiCold/5-rxjx/#

2021-11-21 10:58 UTC, TArch64 requested changes

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/index.html
> +                        <button class="header__button__buy" type="button" data-button-buy>Buy now</button>
1. Уникай в назвах класів подвійного `__`
2. Судячи по назві класу то в тебе тут має бути класс `header__button` і в середині елемента з таким класом лежить ця кнопка? `__` використовується **тільки** тоді коли є жорстка привʼязка до того що один елемент лежить всередині іншого

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/index.html
> +                    <div class="navigation__wrapper" data-navigation-wrapper>
`wrapper` це слово яке не несе ніякої інформативної ціності. Якщо тобі тут потрібно робити враппер чогось то може краще щось зробити новим блоком на сторінці? `burger` це елемент хедера чи навігації? а link? у тебе все елементи належать хедеру хоча деякі з них мобуть бути новим блоком

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/index.html
> +                        <img class="logo_image" src="img/Logo.svg" alt="Логотип">
Можеш зробити лого через svg sprite?

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/img/Logo.svg
> +    <g>
прожени цю іконку через оптимізатор. Зазвичай для чого svgo використовують

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/css/style.css
> +  .header__menu.active {
Якщо робити класи по БЕМу то тут не може бути такої конструкції. active це клас який робить елемент активним. Тобто він модифікує клас до активного стану

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/css/style.css
> +.content__text p {
не використовуй стилі на теги

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/css/style.css
> +    transition: all .5s ease-out;
не використовуй `transition: all`. якщо робити так то браузер буде це розуміти наче **всі** властивості твого хедера можуть бути анімовані, а це дуже рідко так. Краще точно вказуй яка властивість може анімуватися

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/css/style.css
> +    margin: -10px;
тут точно потрібен мінусовий маржін? Може десь можна зменшити падінг на 10px на мобайлі. Старайся не використовувати відʼємні числа у відступах бо це несе за собою всілякі дивні баги

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/css/style.css
> +  .header.active {
Точно так же.  По бему не може бути такий селектор. active має бути модифікатором

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/js/script.js
> +    map((event) => event.path[1].pageYOffset),
Я б тут краще замінив на `window.scrollY`

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/js/script.js
> +            return 'scrollUp';
Такі значення краще виносити в констнати. Наприклад це може бути так

```js
const SROLL_DIRECTIONS = {
  UP: 'scrollUp',
  DOWN: 'scrollDown'
};
```

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/js/script.js
> +    .subscribe((event) => {
ну і тут краще назвати аргумент `scrollDirection`. Це більш інформативно

2021-11-21 10:58 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/js/script.js
> +            headerEl.classList.add('hidden');
використай тут `classList.toggle` з 2м аргументом

2021-11-22 13:21 UTC, TArch64 requested changes

2021-11-22 13:21 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/index.html
> +                    </svg>
1. Якщо ти хочеш використати спрайт, то цей тег svg має десь бути в руті біля body. В ньому будуть всі svg сторінки тому біля самої іконки його класти не слід
2. замість `display="none"` краще використай інлайнові стилі. Не дуже впевнений на рахунок підтримки браузерами атрибута `display`
3. тег `g` в іконки зайвий, бо він нічого не робить. На ньому немає ніяких атрибутів
4. додавай до ід іконки закінчення `icon` щоб можна було розрізняти ід іконок поміж інших айдішок

2021-11-22 13:21 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/index.html
> +                                <a href="#" class="navigation__list__item__link">Контакты</a>
Дуже багато `__`. Коли їх 2 це уже погано, а їх тут 3. Якщо тобі таке доводиться писати то це означає що потрібно зробити новий блок на сторінці. Деякі можна просто писати через `-`, бо не в БЕМ головне вказати що цей елемент належить до певного блока. Не потрібно передавати всю ієрархію вкладностей через назву класа

2021-11-22 13:21 UTC, TArch64 commented on homeworks/andrii.kholodenko_AndriiCold/5-rxjx/index.html
> +                        <span class="burger__line" data-burger-line></span>
Якщо ти використовуєш `burder__line` то в тебе має бути і клас `burger`. Елемент не може використовуватися без блока

2021-11-22 17:45 UTC, AndriiCold commented
Я змінив, подивіться будь ласка, я правильно зробив?

2021-11-22 17:58 UTC, TArch64 approved these changes

2021-11-22 18:00 UTC, merged