5 rxjs
MastersAcademy/frontend-course-2021 pull request #176
Opened 2021-11-19 17:48 UTC by turuta7

2021-11-19 18:07 UTC, turuta7 commented
https://turuta7.github.io/frontend-course-2021/homeworks/Aleksandr.Turuta_turuta7/5-rxjs/index.html

2021-11-21 11:13 UTC, TArch64 commented
У тебе хедер дуже маленький на мобайлі, а кнопку посередині контенту ледь знайшов. Щось не так з мета тегами які роблять респонсів. Пофікси це

![image](https://user-images.githubusercontent.com/29049264/142759532-6b38a3bc-6f90-4141-928e-b98b66587e2e.png)

2021-11-21 11:16 UTC, TArch64 requested changes

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/index.html
> +            <nav class="header__nav nav" data-naigation>
```suggestion
            <nav class="header__nav nav" data-navigation>
```

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/index.html
> +                        <a class="nav__list-item-link" href="#">Новости</a>
ul не може елементом ul. Тут мав бути li

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/script.js
> +        tap(() => console.log(window.pageYOffset)),
тут дебаг лог залишився. Таке потрібно видаляти

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/script.js
> +        map((data) => data[1] - data[0]),
давай зрозумілі назви зміним. Уникай слова data бо воно не несе ніякої інформативної ціності. Всі зміні є даними

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/script.js
> +                headerEl.classList.add('absolute');
використай замість `add` & `remove` метод `toggle`

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/script.js
> +        setTimeout(() => {
чому деякі видалення\додавання класів всередині setTimeout?

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/script.js
> +        setTimeout(() => {
Виглядає як костиль

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/style.css
> +.nav__label-chech  span {
не використовуй стилі на теги

2021-11-21 11:16 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/style.css
> +.nav__label-chech-input[type="checkbox"] {
тут точно потрібна ця специфічність з `[type="checkbox"]`?

2021-11-21 18:52 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/script.js
> +                headerEl.classList.add('absolute');
залишу в цьому місці так як було, тому що буде не тек спрацьовувати, як задумано.

2021-11-21 19:29 UTC, TArch64 commented
В лінок навігації зʼявилися зайві точки

![image](https://user-images.githubusercontent.com/29049264/142776250-f85d5a0a-e017-46c4-a08b-0d3031dd08f0.png)

2021-11-21 19:30 UTC, TArch64 commented
Ти десь бачив сайт де при відкритті сторінки відкрита навігація на мобайлі?

![image](https://user-images.githubusercontent.com/29049264/142776267-7f475c94-d86f-4895-85bf-71120f2411d3.png)

2021-11-21 19:31 UTC, TArch64 commented
В навігації все ще маленький шрифт. Ти дивися які потрібно мета теги ставити щоб все коректно працювало на мобайлі?

2021-11-21 19:31 UTC, TArch64 commented
Хедер показується при скролі вниз, а не вверх. Повино бути навпаки

2021-11-21 19:32 UTC, TArch64 commented
Коли хедер схований, то бургер меню не має бути видно

![image](https://user-images.githubusercontent.com/29049264/142776320-75b6f8e5-60e0-46b9-8262-3e0d0c4be00b.png)

2021-11-21 19:32 UTC, TArch64 commented
Бургер меню вилазить за межі хедера

![image](https://user-images.githubusercontent.com/29049264/142776328-d71883d9-91e5-4ab0-8268-2b79c66def51.png)

2021-11-21 19:33 UTC, TArch64 commented
`nav__label-chech` виглядає як те що має бути всередині хедера, а не за його межами

2021-11-21 19:34 UTC, TArch64 commented
На десктопі дуже огромна кнопка в тексті + немає частини хедера. Просто збільшити шрифт в тексті не варіант

![image](https://user-images.githubusercontent.com/29049264/142776378-a2fae6ca-d0de-47af-8d2c-7dc8b00a3c71.png)

2021-11-21 19:36 UTC, TArch64 commented
@turuta7 Пиши **людсько-зрозумілі** меседжі коммітів. Меседж комміт має пояснювати зміни комміта так щоб було зрозуміло що було змінено не відкриваючи цей комміт. Ніяких `fix js,css and html` та `fix homework`

2021-11-21 19:40 UTC, TArch64 requested changes

2021-11-21 19:40 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/index.html
> +            <span class="nav__label-chech-span_one nav__label-chech-span"></span>
1. Задовгі назви класів. Можливо тут потрібно зробити ще один блок?
2. не додавай назви тегів у назви класів. Що якщо тут буде дів? Робити інший клас для цього?

2021-11-21 19:40 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/index.html
> +            <span class="nav__label-chech-span_one nav__label-chech-span"></span>
`nav__label-chech-span_one` -- це модифікатор?

2021-11-21 19:40 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/5-rxjs/style.css
> +.nav__label-chech-input[type="checkbox"]:checked ~ .nav__label-chech-span_three {
тут точно потрібна додаткова специфічність з `[type="checkbox"]`?

2021-11-21 22:23 UTC, turuta7 commented
setTimeout добавил, что бы работала анимация, при использовании   display: none;

2021-11-22 13:22 UTC, TArch64 commented
> setTimeout добавил, что бы работала анимация, при использовании display: none;

Звучить як костиль, але так як заняття по анімаціях ще не було то ладно. Але по хорошому коли ти робиш таймаут в 0 то ти робиш щось не так

2021-11-22 13:25 UTC, TArch64 approved these changes

2021-11-22 13:26 UTC, merged