5-rxjs
MastersAcademy/frontend-course-2021 pull request #182
Opened 2021-11-20 10:35 UTC by AndriiMorozov88

Hamburger Menu not work yet, till 21-00 i wil fix it
https://andriimorozov88.github.io/frontend-course-2021/homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/index_rxjs.html

2021-11-21 11:18 UTC, TArch64 commented
@AndriiMorozov88 На рахунок що дороблю до дедлайну це буде останній раз. Має бути або виконано або ні. Уяви що ти таке скажеш замовнику який тобі гроші платить?

2021-11-21 11:18 UTC, TArch64 commented
@AndriiMorozov88 Лінка на гітхаб пейджес не працює

2021-11-21 11:27 UTC, TArch64 requested changes

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/index_rxjs.html
> +        <header class="header__content" data-header>
чому тут в назві класу та інших є контент?

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/index_rxjs.html
> +                <li class="header__content-menu-li">
Не використовуй назви тегів у класах. Якщо тут тег зміниться? Це потрібно буде уже інший клас використовувати

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/index_rxjs.html
> +        <script src="script_rxjs.js"></script>
Додай `defer` атрибут до скріптів щоб вони не блочили завантаження сторінки

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/script_rxjs.js
> +    const scrollWay = pair[1] - pair[0];
в `subscribe` має приходити тільки інформація про те чи заховати хедер чи показати його, інші обрахунки мають бути в операторах

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/script_rxjs.js
> +        logo.style.position = 'fixed';
використовуй для цього класи замість інлайнових стилів

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/script_rxjs.js
> +const menu = document.querySelector('[data-menu]');
додавай до змінних в яких елементи дому закінчення `El`

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/style_rxjs.css
> +  margin-top: -10px;
Для чого тут відʼємний маржін?

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/style_rxjs.css
> +.header__content-menu-ul {
тут обовʼязково мати назви тегів та `content`? Чому не можна без них `header__menu`?

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/style_rxjs.css
> +a {
не використовуй стилі на теги, тільки класи

2021-11-21 11:27 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/style_rxjs.css
> +  .header__content-menu-ul-active {
`header__content-menu-ul-active` в назві є слово `active` по всій своїй суті це клас який малює якийсь стан елемента. Або ще кажуть що він модифікує якийсь елемент тому це має бути модифікатором. Так же само і в `header__content-menu-ul-hidden`

2021-11-22 10:23 UTC, AndriiMorozov88 commented
> @AndriiMorozov88 Лінка на гітхаб пейджес не працює
homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs


> @AndriiMorozov88 Лінка на гітхаб пейджес не працює

 https://andriimorozov88.github.io/frontend-course-2021/homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/index_rxjs.html

2021-11-22 13:27 UTC, TArch64 commented
@AndriiMorozov88 Викоиристай такі кольори щоб не було больно дивитися на сторінку та текст на ній. Ми на курсі фронтенду тому коли ти робиш щось то це має виглядає приємно для очей

![image](https://user-images.githubusercontent.com/29049264/142869667-e53afaf7-42b8-4925-8759-29a804830bd5.png)

2021-11-22 13:29 UTC, TArch64 commented
Дуже довгий комміт меседж. Це говоробить про те що комміти мають бути менші і їх має бути більше. Кожен комміт не невеличка зміна чогось. Якщо ти починаєш перелічувати зміни через кому чи `and` то тут вже щось не так і потрібно розбити комміт на декілька менших

2021-11-22 13:29 UTC, TArch64 commented
Немає бургер меню на мобайлі. Це було частиною завдання. Без нього домашка не буде прийнята

![image](https://user-images.githubusercontent.com/29049264/142869951-8192a5c7-8ade-4f48-b435-4f0c401a79f6.png)

2021-11-22 13:32 UTC, TArch64 requested changes

2021-11-22 13:32 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/script_rxjs.js
> +        logo.className = 'header-hidden';
`className = ` перезаписує **всі** класи для елементи. В абсолютній більшості випадків це дуже погано і може ломати візуал. Завжди використовуй `classList` та його методи `add`, `remove` та `toggle`

2021-11-22 13:32 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/5-rxjs/script_rxjs.js
> +    map((pairDifference) => pairDifference[1] - pairDifference[0]),
```suggestion
    map(([previous, current]) => current - previous),
```
Іноді краще використовувати деструкторизацію в масивах

2021-11-22 17:56 UTC, TArch64 approved these changes

2021-11-22 17:57 UTC, merged