Task end
MastersAcademy/frontend-course-2021 pull request #183
Opened 2021-11-20 14:45 UTC by VladislavMedvedyev

https://vladislavmedvedyev.github.io/frontend-course-2021/homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/

2021-11-20 15:48 UTC, NickCashFlow requested changes

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +        <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.6.3/rxjs.umd.min.js" integrity="sha512-JnZPWAckMDks0CCIeGznqEo7ifmYK7VowHq/NVFlSXGkwxv4OBCJFy7nouOtJZmVldHo7FQLIdeWTI55yyZc4Q==" cro
перемести script rxjs перед твоим скриптом вниз страницы, здесь нет смысла в нем

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +                </section>
переделай навигацию с "section" с "p" на "nav" со списком со ссылками

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +                <section class="header-buy">BUY NOW</section>
это должна быть кнопка, с нормальным классом по БЭМу

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +                <button class="header-button" data-header-button type="button">&#9776</button>
у этой кнопки нет паддингов и маржинов, и назови ее как элемент навигации, а не как какую-то абстрактную кнопка в хедере

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +            </section>
мобильный хедер не должен быть отдельной секции, переделай с помощью верстки, чтобы меню перестраивалось на мобильной, как показывалось на одном из предыдущих уроков и ДЗ

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    headerEl.style.transform = 'scale(0)';
добавь класс в css отвечающий за transform и меняй class, вместо изменения inline стилей через js

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    headerEl.style.transform = 'scale(0)';
аналогично, добавь класс в css отвечающий за transform и меняй class, вместо изменения inline стилей через js

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    headerEl.style.transform = 'scale(1)';
аналогично, добавь класс в css отвечающий за transform и меняй class, вместо изменения inline стилей через js

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    headerEl.style.transform = 'scale(1)';
аналогично, добавь класс в css отвечающий за transform и меняй class, вместо изменения inline стилей через js

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +headerButtonEl.addEventListener('touchstart', () => {
переделай на fromEvent с rxjs

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +headerButtonEl.addEventListener('click', () => {
переделай на fromEvent с rxjs

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +burgerMenuButtonEl.addEventListener('touchstart', () => {
переделай на fromEvent с rxjs

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    filter((px) => (px[1] - px[0]) > 50 || (px[0] - px[1]) > 50),
в аргументы колбека можно передать деструктурированые элементы массива

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    map((px) => px[0] < px[1]),
аналогично в аргументы колбека можно передать деструктурированые элементы массива

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/style.css
> +@media (min-width: 769px) {
стандартный брейкпоин до 768пх

2021-11-20 15:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/style.css
> +@media (max-width: 768px) {
стандартный брейкпоинт в данном случае 767px

2021-11-22 11:18 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +        <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.6.3/rxjs.umd.min.js" integrity="sha512-JnZPWAckMDks0CCIeGznqEo7ifmYK7VowHq/NVFlSXGkwxv4OBCJFy7nouOtJZmVldHo7FQLIdeWTI55yyZc4Q==" cro
Исправил

2021-11-22 11:18 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +                </section>
Исправил

2021-11-22 11:19 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +                <section class="header-buy">BUY NOW</section>
Кнопку убрал. Я не разобрался сначала, она для задания с *. Я это задание не делал.

2021-11-22 11:20 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +                <button class="header-button" data-header-button type="button">&#9776</button>
Исправил. Кнопка переделана.

2021-11-22 11:20 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/index.html
> +            </section>
Исправил

2021-11-22 11:20 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    headerEl.style.transform = 'scale(0)';
Сделал через класс

2021-11-22 11:22 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +headerButtonEl.addEventListener('touchstart', () => {
Переделал. Создал стрим для click и через subscribe показыва/прячу бургер

2021-11-22 11:22 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +headerButtonEl.addEventListener('click', () => {
Переделал. Создал стрим для click и через subscribe показыва/прячу бургер

2021-11-22 11:23 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    filter((px) => (px[1] - px[0]) > 50 || (px[0] - px[1]) > 50),
Я не совсем понял, что и как сделать. Можно пример?

2021-11-22 11:23 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/style.css
> +@media (min-width: 769px) {
Исправил

2021-11-22 11:23 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/style.css
> +@media (max-width: 768px) {
Исправил

2021-11-22 11:24 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +burgerMenuButtonEl.addEventListener('touchstart', () => {
Переделал. Создал стрим для click и через subscribe показываю/прячу бургер

2021-11-22 15:49 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    filter((px) => (px[1] - px[0]) > 50 || (px[0] - px[1]) > 50),
Исправил, спасибо

2021-11-22 16:12 UTC, NickCashFlow requested changes

2021-11-22 16:12 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    console.log(px);
удалить

2021-11-22 17:17 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/5-rxjs/script.js
> +    console.log(px);
Удалил

2021-11-22 18:10 UTC, NickCashFlow approved these changes

2021-11-22 18:13 UTC, merged