6 typescript
MastersAcademy/frontend-course-2021 pull request #195
Opened 2021-11-26 17:28 UTC by SanSandru4

https://sansandru4.github.io/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/dist/

2021-11-27 09:59 UTC, electrovladyslav commented
Доделай, плиз, требования по [ТЗ](https://github.com/MastersAcademy/frontend-course-2021/issues/186#issue-1061622446)

> - each time the score changes (added or subtracted), the player must see how his score has changed on the side of the square. A block should appear in which the value of the account has changed (+10, +8, -25);
> - the game must respond to both the uppercase key (S) and the lowercase (s).
Сейчас клавиша шифт считается за нажатие неправильной клавиши.

2021-11-27 10:04 UTC, electrovladyslav commented
Прикольный дизайн прогрес-бара. Непонятно, до какого момент идёт игра. Можно нарисовать кружок, который соответствует 200 и подписать как-то, или просто текстовый блок добавить: 0 - lose, 200 - win

2021-11-27 10:05 UTC, electrovladyslav commented
Ещё нашёл чит-баг: можно нажимать одну букву несколько раз, и очки защитываются. В задании вроде это описано, реализуй, плиз

> when a key is pressed, the player has 2 seconds;

2021-11-27 10:33 UTC, electrovladyslav requested changes
Молодец, почти всё чётенько, по функциям.

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/dist/index.html
> +                    <div class="position__sphere" data-attr-sphere></div>
тут ты неправильное ими блока использовал.

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index
> +import _ from 'lodash';
А для чего этот файл? Вроде он не используется для выполнения задания?
Если да, то удали его из пулл реквеста, плиз.

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function outPoints(num: number): void {
`outPoints` - не вполне понятно, что именно эта функция делает из названия. Если в ней ты показываешь очки на экране, лучше использовать `render` например

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +outPoints(points);
не стоит смешивать декларацию функций и их вызов. 
вынеси вызов в функцию init, или в твою gameProcess

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function winOrLoser(pointsNum: number): void {
победаИлиПроигравший? пусть тогда будет  победаИлиПроигрыш

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function randomSymbol<T>(symbolArray: T[]): T {
добавь `get` в название, если ты возвращаешь этот символ

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function randomSymbol<T>(symbolArray: T[]): T {
Для чего тут дженерик? Эта функция всегда возвращает строку (символ из массива).

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function winOrLoser(pointsNum: number): void {
Я бы разбил эту функцию на две:
1. Определяет, победил или проиграл пользователь.
2. Что-то делает на экране

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function changesIncSphere(randomP: number): void {
1. Название так себе. Что это за изменения корпорации Сфера?))
2. Строки 44-45 и 50-51 практически идентичны. А если ты сначала будешь обновлять значение счёта...
3. То функция будет одна - обновитьРазмерСферы

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +let symbolTimer = setInterval(() => {
Это тоже надо вынести в `init`

2021-11-27 10:33 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/package.json
> +    "lodash": "^4.17.21"
Так и зачем тебе лодаш?

2021-11-27 17:17 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function randomSymbol<T>(symbolArray: T[]): T {
Дженерік тут - чисто для "попробувать, як работає")))

2021-11-27 20:18 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function changesIncSphere(randomP: number): void {
шось, у мене в голові викластися не може((( функції дуже схожі, але вони роблять протилежні зміни з елементом, тут у мене ступор((((

2021-11-28 08:40 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function randomGetSymbol(symbolArray: string[]): string {
Имя функции/метода должно начинаться с глагола. Таким образом с первого взгляда понятно, что это штука совершает какое-то действие.

2021-11-28 08:40 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +let symbolTimer = setInterval(() => {
... или хотя бы перенести вниз. У тебя везде объявление функции в декларативном стиле, а это - function expression.

2021-11-28 08:40 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +    if (pointsNum >= 200) {
Предлагаю избавиться от [магических чисел](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)), назвать 200 и 0 апперкейсом и вынести наверх файла

2021-11-28 08:40 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function randomNum(min: number, max: number): number {
тут же ты тоже возвращаешь это случайное число. Потому имя `getRandomNumber` сразу об этом скажет.

2021-11-28 08:40 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +function changesIncSphere(randomP: number): void {
тебя наверное сбивает короткая запись. `points -= randomP`. По сути это `points = points - randomP`. Получается что у тебя это одинаковое действие производится в трёх строчках
```
sphereBlockEl.style.width = points - randomP + 'px';
sphereBlockEl.style.height = points - randomP + 'px';
points = points - randomP
```
Это противоречит [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself)
Поэтому можно сначала обновить значение очков, а потом назначить это значение в размер сферы. Тогда первое действие можно из этой функции убрать.
И вообще, не очень хорошо, когда функция изменения размеров сферы делает ещё что-то неявное - обновляет значение очков. Это называется сайд-эффект, и такого лучше избегать.

2021-11-28 15:13 UTC, electrovladyslav requested changes

2021-11-28 15:13 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +    sphereBlockEl.style.width = points + 'px';
Ок, теперь вынеси присвоение нового значения очков из этих двух функций changesUpSphere и changesDownSphere. 
И ты увидишь, что это одно и то же, то есть можно использовать одну функцию перерисовки сферы.

2021-11-28 15:13 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +    }, interval);
Тут надо добавить логику вычитания очков у пользователя, если ни одна кнопка не была нажата

2021-11-28 15:13 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-typescript/src/index.ts
> +        winnerOrLoser(points);
Тут надо добавить логику для предотващения чит-бага. Если пользователь ввёл что-то, таймер должен сбрасываться

2021-11-28 20:04 UTC, electrovladyslav commented
Молодец 👍

2021-11-28 20:05 UTC, merged