6 adaptive
MastersAcademy/frontend-course-2021 pull request #207
Opened 2021-11-29 23:53 UTC by SanSandru4

https://sansandru4.github.io/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/

2021-11-30 11:31 UTC, electrovladyslav requested changes

2021-11-30 11:31 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <img src="images/bonik_delivery_logo.png" alt="bonik delivery logo">
А почему лого в png? Оно же векторное на макете

2021-11-30 11:31 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  padding-left: 143px;
margin - внешние отступы, padding - внутренние. 
Зачем этому блоку занимать столько места?
Он должен быть размером с картинку, и отталкиваться от правого соседа `margin-right: auto`. Во флексовом контейнере, это заберёт всё свободное место.
А сам `header` должне ограничить свой контент справа и слева внутренними отступами (padding)

2021-11-30 11:31 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +    url("/fonts/Pragmatica-Medium.woff2") format("woff2"),
Шрифты не приехали - нет папки фонтс на твоём сайте. 
![image](https://user-images.githubusercontent.com/7540757/144037419-f108ba33-1fa9-4a7a-b984-f445152f87e2.png)
Тут можно посмотреть тот шрифт, который отрендерился в реале. 
![image](https://user-images.githubusercontent.com/7540757/144037902-6aec6fca-f7e7-47d8-8c74-45b021646f0b.png)

2021-11-30 11:31 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  font-family: "Pragmatica-Medium", sans-serif;
И может быть один веббезопасный шрифт подключишь? А то у меня для разных блоков разные шрифты сан-сериф поподключались.

2021-11-30 11:31 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <div class="header__info-number-phone">+088 01877576457</div>
Это [ссылка](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel) для телефона

2021-11-30 11:31 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <div class="header__info_btn">Sign In</div>
Это, и рядом, с языком, кнопки. У них дложны быть ховеры по заданию.

2021-11-30 11:31 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  position: relative;
Ой, нет, так позиционировать нельзя))
Задай родителю флекс, и сделай как в шапке.

2021-11-30 18:50 UTC, electrovladyslav requested changes

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <svg width="12" height="16" viewBox="0 0 12 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Интересно, а по какому принципу ты решал, какую свгшку вынести в отдельный файл и подключить, а какую вставить инлайном в html?
Обычно в html инлайном вставляют те свг, с которыми нужно взаимодействие - перекрашивать что-то по ховеру, например. 
Давай ты и тут все свг, которые тебе не нужны для интерактива вынесешь в отдельные файлы.
Потом можно будет сделать из них спрайт, чтобы он одним файлом приезжал, а не кучей мелких. Вот например [статья](https://viktoriavasileva.medium.com/svg-%D1%81%D0%BF%D1%80%D0%B0%D0%B9%D1%82%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%B8%D0%BA%D0%BE%D0%BD%D0%BE%D0%BA-fb0e6595ff44). Или можно погуглить "свг спрайт"

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <div class="main__process_section">
так может это отдельный БЭМ блок, process? Раз ты его так выносишь тут и далее.

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <div class="main__choose-us">
Тоже отдельный БЭМ блок

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +.main__choose-us_text-paragraph {
это не Бэм

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  background: #FFF3EB;
так может это модификаторы для блока card?

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +.main__choose-us_text-paragraph {
Почитай ещё про БЭМ-именование классов, например [это](https://site2go.ru/article/bem-nejming-dlya-html-verstki-sajtov)
```
блок
блок__элемент
блок--модификатор-блока
блок__элемент--моодификатор-элемента
```

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +.main__choose-us_list-card {
Опасно фиксировать и высоту и ширину для блока, у которого есть содержимое, которое может изменится. Один из параметров надо отпустить, задав, например минимальную высоту:
![image](https://user-images.githubusercontent.com/7540757/144106038-0de4058a-1cac-48f6-9e6a-29694c573003.png)
![image](https://user-images.githubusercontent.com/7540757/144106312-ba1fb95c-5fdb-4ad1-a821-6cf344909ceb.png)

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +.main__choose-us_list-card {
Так же, из-за того, что у тебя[ box-sizing](https://learn.javascript.ru/box-sizing): content-box (значение по умолчанию), значение внутренних отступов прибавляется к значению ширины, и она получается больше чем на макете. Поправь
![image](https://user-images.githubusercontent.com/7540757/144106925-872b7280-859e-46a3-8c7e-b1494b7ba8a4.png)

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  margin-top: 28px;
Нужны стили для ховера

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  height: 103px;
Зачем ты ограничиваешь высоту тут?

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  font-family: "Segoe UI", sans-serif;
Шрифт надо подключить - у меня отрендерилась Гелветика

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  padding-top: 100px;
Это тоже внешний отступ а не внутренний, и он должен быть не у ребёнка а у родителя. У самого верхнего блока, который отталкивается от своего соседа сверху

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                        <p>FAQs</p>
Это всё ссылки на другие страницы сайта

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <div class="footer__logo_social-link">
Каждая из иконок - ссылка на соц-сеть. Нужны ссылки в разметке и стили для ховера

2021-11-30 18:50 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  width: 1440px;
Тут тоже ты зафиксировал оба размера. По этому и этот промежуток снизу
![image](https://user-images.githubusercontent.com/7540757/144109184-80b1732f-1150-4fc2-bdd6-ae853619ff02.png)

2021-11-30 18:54 UTC, electrovladyslav commented
- [ ] Все кнопки/ссылки сделай такими и добавь ховеры и cursor:pointer
- [ ] Все свг-шки, с которыми не будешь взаимодействовать - в отдельный файлы, потом в спрайт
- [ ] Пересмотри все paddings, и подумай, действительно ли это внутренние отступы, а не внешние?
- [ ] Там где зафиксированы высота и ширина, один параметр отпусти, ограничив минимальным значением. Это должен быть параметр, за счёт которого элемент будет увеличивать свой размер, когда будет становиться больше контента.

2021-12-02 08:06 UTC, electrovladyslav commented
Супер, уже гораздо лучше

2021-12-02 08:06 UTC, electrovladyslav requested changes

2021-12-02 08:06 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                            <p class="card__learn-more_link">Learn More</p>
Ты тут даже в названии класса пишешь, что это линк (ссылка). Почему же тогда размечаешь параграфом?
Это ссылка, и надо добавить к ней ховер.

2021-12-02 08:06 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                            <svg width="18" height="16" viewBox="0 0 18 16" fill="none" xmlns="http://www.w3.org/2000/svg">
А эту свгшку убрать в спрайт

2021-12-02 08:14 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  display: flex;
и задай минимальный размер для всего контента на странице. А то так на маленьких экранах он не скролиться нормально. Обычно, для этого используют отдельный div.wrapper
![image](https://user-images.githubusercontent.com/7540757/144383310-6bb63340-ab8a-493b-9f0f-3d9beff2656a.png)

2021-12-02 21:16 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +    url("/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/fonts/Pragmatica-Bold.woff2") format("woff2"),
Я вообще-то имел в виду заменить абсолютный путь на относительный. Мало ли ещё куда положат папку с твоими файлами.
```
index.html
styles.css
fonts
\_ Pragmatica-Bold.woff2
...
```
значит относительный путь к файлу будет `./fonts/Pragmatica-Bold.woff2`

2021-12-02 21:16 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                    <svg class="phone">
Если ты сильно хочешь оставить эту свгшку в разметке, то хоть оберни её в ссылку `href="tel`
Картинка трубки и сам номер телефона - это одна большая кнопка, для звонка.
А если как сейчас у тебя - ховер на трубке отдельно работает - то выходит что это отдельный интерактивный элемент. 
Ховер показывает, что с элементом можно взаимодействовать. А с твоей трубкой не повзаимодействуеш ь сейчас.

2021-12-02 21:16 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                <div class="header__info_btn">Sign In</div>
> Разметь семантично, не дивом а батоном или ссылкой. Так они будут доступны с клавиатуры, например их можно будет выбрать пощёлкав табом. Для дива эту функцию, и ещё кучу всего, надо добавлять вручную.
Так что лучше такие интерактивные элементы размечать интерактивными тэгами - ссылкой, или кнопкой.

2021-12-02 21:34 UTC, electrovladyslav requested changes
С каждым разом всё лучше и лучше. 
Полезно после создания/обновления  пулл-реквеста заглядывать не только в код, но и на сайт, с гитхаб-пейджес. Всё ли выглядит нормально? Приехали ли ли все шрифты, или есть какие-то ошибки в консоли?
Открываешь рядом макет в фигме и свой сайт на 100%. И сверяешь. И сразу становиться ослепительно ясно)))
![image](https://user-images.githubusercontent.com/7540757/144506706-dd5946cd-e20c-4bca-9b99-7a0ea4b54c48.png)

2021-12-02 21:34 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  font-family: "Segoe UI", Roboto, sans-serif;
Не приехал шрифт 
Так же в качестве разделителей между словами в названии блоков в БЭМе используют `-` а не `_`
Поправь здесь и по всей страничке.
![image](https://user-images.githubusercontent.com/7540757/144505033-2551f41a-83ba-47c1-8d61-f8a6f364cc71.png)

2021-12-02 21:34 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                            <a class="card__learn-more_link" href="#Learn">Learn More</a>
Тут тоже, как и с трубкой, ситуация - стрелка - это часть ссылки. 
И ховер у неё должен появляться одновременно с ховером текста
![image](https://user-images.githubusercontent.com/7540757/144506033-722f0e97-fb53-40e6-9ae5-874b69519e63.png)

2021-12-02 22:01 UTC, SanSandru4 commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                    <svg class="phone">
Перефарбовуватись одночасно не хоче((( то я зробив йому другий ховер.

2021-12-03 10:55 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  font-family: "Segoe UI Bold", Roboto, sans-serif;
Параметры текста не соответствуют макету 
![image](https://user-images.githubusercontent.com/7540757/144589425-59107cb8-0fbd-4036-b0b5-8921a5a94f38.png)

2021-12-03 10:55 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/style.css
> +  fill: #444B51;
Сделай цвет по макету, и дай класс по БЭМу
![image](https://user-images.githubusercontent.com/7540757/144590272-624ae8ef-e286-4951-93f4-ec2a914b2697.png)

2021-12-03 10:55 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                    <svg class="globus">
Так, ещё раз, это кнопка или ссылка. При клике переключается язык. Ховера не достаточно, разметь кнопкой или ссылкой. И текст и значёк глобуса

2021-12-03 10:55 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/6-adaptive/index.html
> +                    <svg class="phone">
Так пойдёт. В тз же не указано, какой должен быть ховер. 
А вообще не обязательно на эти два элемента навешивать одинаковые стили для ховера. Можно сделать это по отдельности
```
.header__phone:hover {
  color: red. // например
}

.header__phone:hover .header__phone-icon {
  fill: red.
}

2021-12-03 16:43 UTC, electrovladyslav commented
Класс 👍

2021-12-03 16:44 UTC, merged