6 adaptive
MastersAcademy/frontend-course-2021 pull request #208
Opened 2021-11-30 08:45 UTC by VladislavMedvedyev

https://vladislavmedvedyev.github.io/frontend-course-2021/homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html

2021-11-30 09:19 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Verified Products.svg
> +<svg width="72" height="73" viewBox="0 0 72 73" fill="none" xmlns="http://www.w3.org/2000/svg">
нельзя оставлять названия файлов с пробелами, потому что в разных операционных системах пробелы интерпретируются по разному, переименуй в стиле кебаб кейс, например, name-of-picture.svg

2021-11-30 09:24 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-typescript/package.json
> +{
откати этот файл в этом pull request, так как изменения в нем не относиться к функционалу этого задания

2021-11-30 09:25 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-test/style.css
> +.container {
удали этот файл с pull request, так как он не относиться к функционалу этого задания

2021-11-30 09:25 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-typescript/src/index .html
> +<!DOCTYPE html>
откати этот файл с этого pull request, так как изменения в нем не относиться к функционалу этого задания

2021-11-30 09:25 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-typescript/src/index.ts
> +import { fromEvent, Observable } from 'rxjs'
аналогично удали этот файл с pull request, так как он не относиться к функционалу этого задания

2021-11-30 09:25 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-typescript/src/style.css
> +.container {
удали этот файл с pull request, так как он не относиться к функционалу этого задания

2021-11-30 09:26 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-typescript/tsconfig.json
> +{
аналогично

2021-11-30 09:26 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-typescript/webpack.config.js
> +const path = require('path');
удали этот файл с pull request, так как он не относиться к функционалу этого задания

2021-11-30 09:27 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <img src="images/bonik delivery logo.png" alt=" Boic delivery Logo">
аналогично о пробелах в названиях

2021-11-30 09:28 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <svg width="12" height="16" viewBox="0 0 12 16" fill="none" xmlns="http://www.w3.org/2000/svg">
добавление сырого svg это плохая практика, также все svg должны быть сжаты и подключены через тег use

2021-11-30 09:31 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <a href="">+088 01877576457</a>
отступы не соответствуют дизайну, атрибут href не должен быть пустым, иначе html-файл невалидный, добавь  # в href атрибут

2021-11-30 09:31 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <svg width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg">
аналогично

2021-11-30 09:34 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <a href="">EN</a>
здесь нужно сделать выпадающий список еще с  парой языков, чтобы можно было выбирать с него. Также,  отступ от картинки до текста не соответствует дизайну

2021-11-30 09:35 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <svg width="72" height="71" viewBox="0 0 72 71" fill="none" xmlns="http://www.w3.org/2000/svg">
добавление сырого svg это плохая практика, также все svg должны быть сжаты и подключены через тег use

2021-11-30 09:35 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <svg width="92" height="71" viewBox="0 0 92 71" fill="none" xmlns="http://www.w3.org/2000/svg">
аналогично

2021-11-30 09:36 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <svg width="111" height="71" viewBox="0 0 111 71" fill="none" xmlns="http://www.w3.org/2000/svg">
аналогично

2021-11-30 09:37 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                        <section class="advantages_industry-leading-tech">
зачем section вложен в section, переделай, Тарас показывал пример в конце лекции Тайпскрипт.
Отступы между карточками не соответствуют дизайну

2021-11-30 09:44 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <svg width="71" height="70" viewBox="0 0 71 70" fill="none" xmlns="http://www.w3.org/2000/svg">
добавление сырого svg это плохая практика, также все svg должны быть сжаты и подключены через тег use

2021-11-30 09:44 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                        <section class="advantages_best-cod-rates">
добавление сырого svg это плохая практика, также все svg должны быть сжаты и подключены через тег use

2021-11-30 09:46 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                            <picture class="news-three_picture">
картинки и отступы вокруг них не соответствуют дизайну, нужно доработать

2021-11-30 09:48 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/index.html
> +                                <a href="">FAQs</a>
на >>>ВСЕХ<<< ссылках и кнопках нету ховер эффекта, а по заданию должны быть. Ссылки, которые никуда не ведут, должны иметь атрибут href="#"

2021-11-30 09:51 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/style.css
> +  display: grid;
ты везде используешь grid, но по факту потребности в нем на этом макете нету, потому что он очень простой. Переделывать не нужно, но нужно думать, что ты используешь и зачем ты это используешь.

2021-12-01 21:46 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Best COD rates.svg
> +<svg width="92" height="70" viewBox="0 0 92 70" fill="none" xmlns="http://www.w3.org/2000/svg">
Шрифты подключил, файлы с пробелами переименовал/удалил

2021-12-01 21:46 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Facebook.svg
> +<svg width="32" height="33" viewBox="0 0 32 33" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:47 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Fastest Delivery.svg
> +<svg width="111" height="71" viewBox="0 0 111 71" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:47 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Industry-leading tech.svg
> +<svg width="72" height="71" viewBox="0 0 72 71" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:47 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Learn more.svg
> +<svg width="126" height="28" viewBox="0 0 126 28" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:48 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/LinkedIn.svg
> +<svg width="33" height="33" viewBox="0 0 33 33" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:48 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Logo.svg
> +<symbol id="logo" width="270" height="39" viewBox="0 0 270 39" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:48 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Nationwide coverage.svg
> +<svg width="92" height="71" viewBox="0 0 92 71" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:49 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Next day payment.svg
> +<svg width="71" height="70" viewBox="0 0 71 70" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:49 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Pinter.svg
> +<svg width="33" height="33" viewBox="0 0 33 33" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:49 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Product insurance.svg
> +<svg width="70" height="71" viewBox="0 0 70 71" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:49 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Realtime Monitoring.svg
> +<svg width="76" height="70" viewBox="0 0 76 70" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:50 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Twitter.svg
> +<svg width="33" height="33" viewBox="0 0 33 33" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-01 21:50 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/6-adaptive/images/Verified Products.svg
> +<svg width="72" height="73" viewBox="0 0 72 73" fill="none" xmlns="http://www.w3.org/2000/svg">
Файлы с пробелами переименовал/удалил

2021-12-03 16:00 UTC, NickCashFlow requested changes
доделай нормальную адаптивность

2021-12-05 16:04 UTC, NickCashFlow approved these changes

2021-12-05 16:08 UTC, merged