7-oop
MastersAcademy/frontend-course-2021 pull request #215
Opened 2021-12-01 17:38 UTC by kovalov

2021-12-01 18:33 UTC, TArch64 requested changes

2021-12-01 18:33 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/index.ts
> +            const imageSource = image.getAttribute('src');
Ти в JS логіці відштовхуєшся від того що в тебе в домі. Краще робити навпаки: У тебе є масив даних (імеджі) і ти їх рендериш в дом а по кліку показуєш імедж. UI потрібно робити на основі даних, а не дані на основі UI

2021-12-01 18:33 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/index.ts
> +        this.fullScreenElement?.addEventListener('click', event => {
Вся логіка в одному класі що не є добре. У тебе є декілька різних стейтів (галерея, фулл скрін імедж, лодер) і як мінімум це буде вже 3 різні класи. Наприклад ти можеш використати композицію і передавати 2 останніх в клас галереї

2021-12-01 18:33 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/index.ts
> +        imageUploaderElement?.addEventListener('change', event => {
1. Тут мабуть мало б бути `this.imageUploaderElement `
2. Чи буде корректно працювати клас якщо не передати всі ці імеджі що ти перевіряєш через опшіонал чейнінг? Ні, не будуть. Це те без чого клас не може працювати взагалі тому це потрібно перевіряти при створенні класа і викидати помилку що каже чого не вистачає. Поточний варіант ніяк не інформує користувача класа що він щось зробив не так

2021-12-01 18:33 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/index.ts
> +        return new Promise((resolve, reject) => {
краще використовувати ObjectURL в base64 є проблем з перформансом

https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

2021-12-01 18:33 UTC, TArch64 commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/index.ts
> +    private getBase64(file: any) {
Поправ всі ці ворнінги що тут висять про any і в майбутньому **ніколи** не використовуй це тип даних

2021-12-05 17:26 UTC, NickCashFlow requested changes
никаких any

2021-12-05 17:26 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/gallery.ts
> +        this.imageUploader = new Uploader(document.querySelector('[data-image-uploader]') as HTMLElement, this.onImageUploaded);
вот это нужно выносить в зависимости

2021-12-05 17:26 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/fullscreen.ts
> +        const closeElement: HTMLElement | null = this.el.querySelector<HTMLElement>('[data-full-screen-close]');
это тоже нужно выносить в зависимости

2021-12-05 17:26 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/fullscreen.ts
> +        const element: HTMLElement | null = (content as HTMLImageElement).querySelector('[data-full-screen-image]');
аналогично в зависимости

2021-12-05 17:26 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/gallery.ts
> +        const element: any = (content as HTMLImageElement).querySelector('[data-new-image-template-element]');
и это в зависимости

2021-12-05 17:26 UTC, NickCashFlow commented on homeworks/vladyslav.kovalov_kovalov/7-oop/src/uploader.ts
> +        const spinnerElement: HTMLElement | null = this.el.querySelector('[data-image-uploader-spinner]');
и это в зависимости

2021-12-07 12:10 UTC, NickCashFlow approved these changes

2021-12-07 12:16 UTC, TArch64 approved these changes

2021-12-07 12:16 UTC, merged