add homeWork 7 Turuta
MastersAcademy/frontend-course-2021 pull request #218
Opened 2021-12-04 00:55 UTC by turuta7

2021-12-04 00:58 UTC, turuta7 commented
https://turuta7.github.io/frontend-course-2021/homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html

2021-12-04 17:01 UTC, TArch64 commented
@turuta7 Не відповідає дизайну. Не буду дивитися код, допоки це не буде виглядати так як має бути

https://www.figma.com/file/bhRSiKJdeAoG5HgMH5MSAq/OOP-Home-Task?node-id=0%3A1

2021-12-04 20:36 UTC, turuta7 commented
correcting the code for the layout

2021-12-05 15:03 UTC, TArch64 commented
@turuta7 Хедер має бути фіксований на всіх девайсах
![image](https://user-images.githubusercontent.com/29049264/144752077-4fbb6e4e-19d5-44f3-8302-686a953b1005.png)

2021-12-05 15:04 UTC, TArch64 commented
Не показується лоадер при додаванні імеджа

2021-12-05 15:07 UTC, TArch64 commented
На сторінці не той шрифт що потрібно

2021-12-05 15:41 UTC, TArch64 requested changes

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/assets/Vector (1).svg
> +<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
Давай внятні назви всім файлам. Тобі зрозуміло по назві що таке вектор1? Також в назвах файлів не має бути пробілів

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +            <img class="modal__container-cancel" data-cancel src="../assets/Vector (1).svg" alt="">
Підключай іконки через svg sprite

https://w3bits.com/svg-sprites/

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +            <img class="modal__container-cancel" data-cancel src="../assets/Vector (1).svg" alt="">
клікабельні елементи мають бути кнопкою. Не можна слухати клік в діва чи імеджа

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +            <img class="modal__container-cancel" data-cancel src="../assets/Vector (1).svg" alt="">
мають бути у всіх кнопок ховер та фокус стейти

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +            <p class="header__name-app">MyLibrary</p>
Це хедінг тому для цього має використовуватися певний тег

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +                        </div>
Лодер це не частпина списка імеджів тому він не має бути всередині цього списку

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +            </footer>
На сторінці немає ніякого футера. А той FAB має бути окремим елементом на сторінці

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +                    <img class="main__footer-image" src="../assets/1. Standard.png" alt="camera">
Це круглий елемент з тесктом всередині. Це не має бути імеджом. Це може бути просто html

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +                    <input class="main__footer-input" type="file" data-image>
потрібно вказувати які саме типи файлів можна обрати через інпут

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +                    <input class="main__footer-input" type="file" data-image>
А що якщо хтось архів додасть сюди?

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +            </div>
класи мають юути по БЕМу. Поточний варіант це не бем

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +        })
лодер не має сам вирішувати коли йому показуватися а коли ховатися. Він має мати методи для цього, а вони уже викликаються коли потрібно

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +        this.loaderEl.classList.remove('display__flex')
зроби класс `hidden` який буде ховати елемент. Якщо ти захочеш там не флекс то що? Логіка ховання елемента не має залежати від його стилізації

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +    constructor(private readonly loaderEl: HTMLElement,) { }
1 файл = 1 клас

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +class LoaderImage {
Це просто лодер який показує лодер. В нього немає нічого спільного з імеджом

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +        private readonly mRindow: HTMLElement
Внятні і зрозумілі назви всім полям, зміних та функціям

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +        private readonly mRindow: HTMLElement
Або тут зайві модифікатори доступу в констуктора або зберігання в поля. Раз у тебе на кожне поле є дублікат

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +    async getBase64(image: FileList[0]) {
```suggestion
    async getBase64(image: File) {
```

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +            this.getBase64((element.files as FileList)[0])
логіка парсіння імеджа має бути в окремому класі і тут викликатися. В цьому класі має бути тільки логіка роботи з ui списком імеджа (показати & додати). Вся інша логіка в інших класах

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +        }
Цей метод називається `getBase64` і **ВСЕ** що він має робити це повертати текст промісом. Ніяких додавань в дом чи лістнерів. Тільки парсіння імеджа і все. Інша логіка має бути в інших методах чи класах

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +            new LoaderImage(document.querySelector('[data-loader]')).visible().then(() => {
обʼєкт лодера має створюватися один раз і надалі перевикористовуватися

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +        imageDateEl.addEventListener('click', () => {
має бути окремий клас імеджа де будуть всі лістери та логіка відмалювання імеджа

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  margin: 32px auto 0;
відступи від контейнера до чайдів мають робитися через падінги. Маржіни **ТІЛЬКИ** для відступів між 2 елеменами в одному контейнері

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  line-height: 24px;
`line-height` вказують зазвичай не через пікселі

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  width: 56px;
Цей елемент точно не має містити ніяких розмірів. І більше схоже на те що він має бути фіксований на сторінці, а не імедж

![image](https://user-images.githubusercontent.com/29049264/144752882-bec68a3a-706e-4c50-8fab-0925b12c016b.png)

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +.main__footer-input[type=file] {
Посясни, будь-ласка, для чого тут тобі потрібна ця специфічність

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  transition: .3s;
Вказуй які саме поля ти хочеш анімувати

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +.image__block {
цей клас не використовується на сторінці

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  height: 254px;
імедж не має мати фіксовані розміри. Розмір колонок може змінюватися і розмір імеджа відповідно також

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  margin: 0 10px 20px;
не можна робити маржіни в усі сторони. використовуй gap

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  justify-content: left;
Коли тобі потрібно робити плиточки то скоріш всього тут тобі потрібно грід і тут він саме потрібен. Флекс не підходить

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  margin-top: 5%;
маржіни не можна задавати у відсотках. Знайди інший спосіб центрувати елементи

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  margin: 0 auto;
Тут ти переписуєш всі маржіни і той маржін вверху нічого не робить

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  height: auto;
height: auto;

Це дефолтне значення цього атрубуту

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  position: absolute;
в кожної кнопки мають бути ховер та фокус стейти і в кнопок іконоками має бути також збільшена область кліка. Візуально має бути той же самий розмір, але область куди можна клікнути має бути більна

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  position: absolute;
лодер має існувати окремо від усіх і не має бути тільки для відкриття імеджа. При додаванні також потрібно показувати. В ньог має бути всій оверлей і він має бути незалежним компонентом ui

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +}
ці класи не по БЕМу. У тебе десь є блок з класом `display`? Я такого не бачив

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +.loader .loader__children {
Це має робитися без вкладених селекторів

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +    margin: 0 5.5px 11px;
**Ніколи** не використовуй пікселі з не цілими числами

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +    margin: 0 5.5px 11px;
Між імеджами завжди адекватний падінг на дизайі і не бачу причини робити тут 5.5px чи 11px

2021-12-05 15:41 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +    max-width: 834px;
просто хай контейнер розтягується скільки може, а імеджі будуть також розтягуватися та заповнювати вільний простій. Стосується всіх девайсів

2021-12-06 11:33 UTC, TArch64 commented
@turuta7 Розділяй комміти по логічним змінах. Не можна робити комміт з назвою `fix code` де все на світі. Має бути написаний меседж що дає зрозуміти які зміни зроблені в цьому коммітові без необхідності відкривати комміт і самі комміти мають бути розділені на логічно завершені зміни по проекту. Зазвичай 1 комментар до пулл реквесту = 1 комміт

2021-12-06 12:20 UTC, TArch64 requested changes

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +const loader = new Hidden(document.querySelector('[data-loader]'), 'display__flex')
Ці залежності мають передаватися через конструктор

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +            this.modalRindow.querySelector('[data-cancel-button]').classList.remove('display__flex')
Замість того щоб прибирати в кожного елемента видимість роби це тільки з рутовим, а всі інші заховаються бо їх парент захований

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/script.ts
> +            this.modalRindow.classList.remove('display__flex')
використовуй для ховання елементів класс `hidden`

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  margin: 32px auto 0;
@turuta7 Цей комментар не виправлений

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/index.html
> +                    <image href="../assets/Close_icon.svg"></image>
використовуй спрайт для іконок. Я закидав туторіал як це робити

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  line-height: 24px;
@turuta7 Цей комментар не виправлений

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  width: 56px;
@turuta7 Цей комментар не виправлений

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  transition: .3s;
@turuta7 Цей комментар не виправлений

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  grid-auto-rows: 22.5vw;
ніколи не використовуй `vw` чи `vw`. Для того щоб зробити однакові колонки є `fr`

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +}
стилі оверлея лоадера та відритого імеджа однакові той є сенс зробити для цього один класс

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  margin-top: 5%;
@turuta7 Цей комментар не виправлений

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +  margin: 0 auto;
@turuta7 Цей комментар не виправлений

2021-12-06 12:20 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/7-oop/src/style.css
> +@media (min-width: 425px) and (max-width: 1194px) {
чому вирішив використати саме ці брейкпоніти?

2021-12-06 19:01 UTC, TArch64 commented
Дедлайн

2021-12-06 19:05 UTC, closed without merging