End task
MastersAcademy/frontend-course-2021 pull request #226
Opened 2021-12-11 17:32 UTC by VladislavMedvedyev

https://vladislavmedvedyev.github.io/frontend-course-2021/homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html

2021-12-12 11:06 UTC, NickCashFlow requested changes
Переименуй pull request на 8-css-variables.
Это очень простой макет, который не требует использования grid'a, переделай все на флекс, доработай респонсив, оптимизируй js-код

2021-12-12 11:06 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +  .footer__about-us a {
опять селектор тега, переделай на класс

2021-12-12 14:47 UTC, NickCashFlow requested changes

2021-12-12 14:47 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +  --advantages-svg-stroke-color: rgba(0, 0, 0, 1);
может среди этих переменных есть переменные с одинаковыми значениями?

2021-12-13 03:52 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +}
Я переделал, но мне не совсем понятно, какой смысл стилизовать через классы конкретно эти элементы (a, ul, h и т.д.) Я понимаю, зачем используются классы, но если  у меня ко всем тегам <a> приминяется один стиль, как-то странно добавлять ко всем <a> класс "a".

2021-12-13 03:55 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +                            <button class="advantages__consultation" type="button">FREE CONSULTATION</button>
Добавил на кнопки класс <button>

2021-12-13 03:57 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +            <header class="header">
У Тараса спрашивали, надо ли делать бургер-меню. Он сказал на свое усмотрение. Изначально я бургер-меню не делал. Если ты считаешь, что это меню должно быть выпадающим - переделаю

2021-12-13 03:58 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +                    </svg>
А как быть с разными значеями width и height у этих svg? Привести их к общему значению?

2021-12-13 04:02 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/script.js
> +});
Конечно, я заметил повторы кода. К сожалению, не получилось оптимизировать. Думал-гадал, ничего не придумал. Можно использовать массив из setProperty? Буду благодарен за подсказку.

2021-12-13 04:04 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +@media (min-width: 1024px) {
Данный медиа-запрос убран. Задублированный код, который нашел, удалил.

2021-12-13 04:04 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +  }
Исправил через классы

2021-12-13 04:09 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +    width: 40.5%;
Мне не совсем понятно, как это реализовать, чтоб дизайн был респонсив. В фигме указаны фиксированные значения ширины. Если я их укажу - элементы не будут динамически изменяться при изменении ширины экрана.
Поэтому реализую это следующим образом: 1. Беру ширину элемента. 2 Беру ширину родительского блока. 3. Через пропорцию выясняю соотношение элемента к род. блоку в %.

2021-12-13 04:09 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +  .archmove__picture img {
Исправил

2021-12-13 04:10 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +  .footer__about-us a {
Исправил

2021-12-13 04:10 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +  --advantages-svg-stroke-color: rgba(0, 0, 0, 1);
Исправил

2021-12-13 04:12 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +    width: 45.7%;
Подскажи, как подход правильно использовать. Буду благодарен

2021-12-13 07:05 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +}
не нужно добавлять ко всем тегам класс "а", нужно либо использовать нормалайз или ресет, о котором рассказывалось в предыдущих лекциях. Но по классическому БЕМу сбросы/нормалайзы не используются. С БЭМом не нужно использовать наследование и потому лучше писать стили только на классах, а не на селекторах тега

2021-12-13 07:06 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +            <header class="header">
Просто доделай адаптив, чтобы он нормально выглядел, бургер - необязательно

2021-12-13 07:07 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +                    </svg>
Ты можешь менять их через js, но лучше привести их к общему значению

2021-12-13 07:15 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/script.js
> +});
Лучше делать вообще по другому:
- сделать дата атрибут с названием темы на теге боди
- описать для темной темы значения переменных, например, [data-theme="dark"] {}
- а потом в js работать только со сменой значения этого дата атрибута

Это упростит твой js-код и оставит css-переменные только в css

2021-12-13 07:18 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +    width: 40.5%;
Не нужно так делать, в некоторых моментах значения ширины и высоты совсем не нужно устанавливать, контент сам подстроиться, а если выглядит не так, как нужно, то нужно просто ограничить ширину в px

2021-12-13 07:28 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +    width: 45.7%;
в данном случае нужно переверстать archmove__advantages advantages и не делать ей относительный маржин-лефт, а сделать вместо этого у внутренних элементов маржины, полностью переверстать все на флексы и не использовать коламн-геп, тогда добавить падинги для самой кнопки и не регулировать её ширину с помощью width в %

2021-12-13 07:30 UTC, NickCashFlow requested changes
полностью убери grid, он здесь не нужен

2021-12-14 01:09 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +}
Понял, поисправлял.

2021-12-14 01:20 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +            <header class="header">
Столкнулся с тем, что мой сайт отображается по разному на github pages и на моем локальном сервере. У меня отображается корректно, при этом на pages - нет. Ниже скриншоты.
https://www.dropbox.com/s/vvbe2r4nynri686/image%20%281%29.png?dl=0
https://www.dropbox.com/s/m9k1smi9lwghvdz/image.png?dl=0

2021-12-14 01:56 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +                    </svg>
Сделал одним тегом. Но теперь функция по клику срабатывает не всегда. Есть предположение, что причиной этой проблемы является два листнера на один svg.

2021-12-14 01:56 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/script.js
> +});
Спасибо. Исправил на твой вариант.

2021-12-14 01:57 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +    width: 45.7%;
Исправил

2021-12-14 02:00 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/style.css
> +    width: 40.5%;
Понял, учту. И ещё вопрос по этой теме. Марджины/паддинги выставлять правильно в отностиельных величинах(% и т.п.) или в фиксированных(px)? Или это все ситуативно?

2021-12-14 08:58 UTC, NickCashFlow requested changes
Доделай нормальный адаптив и исправь баги

2021-12-14 08:58 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +            <header class="header">
Даже если и так;-) http://joxi.ru/a2XgXwxHlY0MLm, то тебе нужно с этим разобраться и сделать, чтобы на гитхаб пейджах показывалось так, как у тебя на локалке.

2021-12-14 08:58 UTC, NickCashFlow commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/script.js
> +});
ты делаешь не верно, нужно клик слушать на кнопке, а не на теге use, потому у тебя этот функционал работает лишь 1 раз после загрузки страницы

2021-12-14 19:38 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +                    </svg>
Исправил

2021-12-14 19:40 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/script.js
> +});
Исправил

2021-12-15 09:43 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/8-css-variables/index.html
> +            <header class="header">
Исправил. Я использовал расширение VsCode для поднятия простого сервера. А он криво отображал width.

2021-12-15 12:28 UTC, NickCashFlow approved these changes

2021-12-15 12:28 UTC, merged