8 css variables
MastersAcademy/frontend-course-2021 pull request #229
Opened 2021-12-12 08:27 UTC by DmitriyKondaurov

2021-12-12 08:30 UTC, DmitriyKondaurov commented
https://dmitriykondaurov.github.io/frontend-course-2021/homeworks/dmytro.kondaurov_DmitriyKondaurov/8-css-variables/

2021-12-12 12:33 UTC, MZabolotnev commented
![image](https://user-images.githubusercontent.com/25617217/145712404-60009872-864f-4502-a5d3-1a3c4bd80569.png)
Выглядит плохо на мобайле

2021-12-12 12:35 UTC, MZabolotnev requested changes
Нужно проапдейтить мобильный вид, возможно тут поможет выпадающее меню

2021-12-13 12:33 UTC, DmitriyKondaurov commented
I fix your comment, can you check my HW please @MZabolotnev

2021-12-18 17:00 UTC, MZabolotnev approved these changes

2021-12-18 17:01 UTC, merged