9 animations
MastersAcademy/frontend-course-2021 pull request #241
Opened 2021-12-16 20:48 UTC by SanSandru4

https://sansandru4.github.io/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/9-animations

2021-12-16 21:29 UTC, SanSandru4 commented
https://sansandru4.github.io/frontend-course-2021/homeworks/oleksandr.prylutskiy_SanSandru4/9-animations/

2021-12-17 17:18 UTC, electrovladyslav requested changes
Класс!
Не уверен, что та анимация, которую ты применил к картинкам, отвечает требованию ТЗ. Спрошу у Коли.

> Pictures should appear nicely when scrolling

2021-12-17 17:18 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/8-css-variables/index.html
> +            <div class="loader__spin"></div>
Если родительский блок называется `preloader` то и его дочерние элементы должны начинаться с такого же слова. Это создаёт одинаковое [пространство имён ](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%81%D1%82%D0%B2%D0%BE_%D0%B8%D0%BC%D1%91%D0%BD)

2021-12-19 12:04 UTC, electrovladyslav requested changes
Уже почти. 
Если хочешь, давай созвонимся, побеседуем за БЭМ.

2021-12-19 12:04 UTC, electrovladyslav commented on homeworks/oleksandr.prylutskiy_SanSandru4/9-animations/script.js
> +    const observer = new IntersectionObserver(onEntry, options);
Класс

2021-12-19 16:02 UTC, electrovladyslav approved these changes

2021-12-19 16:02 UTC, merged

2021-12-19 16:02 UTC, electrovladyslav commented
Супер!