9 animations
MastersAcademy/frontend-course-2021 pull request #245
Opened 2021-12-17 15:58 UTC by MaksymSelenkov

https://maksymselenkov.github.io/frontend-course-2021/homeworks/maksym.selenkov_MaksymSelenkov/9-animations/index.html

2021-12-18 09:02 UTC, DrSmile444 requested changes

2021-12-18 09:02 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/9-animations/index.js
> +    const lightTheme = 'light.css';
It's better to move such consts to the global scope.

2021-12-18 09:02 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/9-animations/light.css
> +* {
Apply all comments in this CSS file as well

2021-12-18 09:02 UTC, DrSmile444 commented on homeworks/maksym.selenkov_MaksymSelenkov/9-animations/style.css
> +a {
Nooo 😢
You should NEVER use tag selectors in CSS. Create a class and apply it to all elements. Review all your CSS code to replace such tag selectors

2021-12-18 09:05 UTC, DrSmile444 commented
One more thing:
Please, review how your site is responsive. It displays wrong on 1024px, so I didn't check fewer sizes.

![maksymselenkov github io_frontend-course-2021_homeworks_maksym selenkov_MaksymSelenkov_9-animations_index html (1)](https://user-images.githubusercontent.com/33941060/146635775-b990e5f8-fce7-4263-8430-81b56786b1af.png)

2021-12-18 09:06 UTC, DrSmile444 commented
And one more:
You don't have SVG animation on the site load, as is mentioned in the task:

> When the page is loaded, the svg logo must be animated once

2021-12-19 11:20 UTC, MaksymSelenkov commented
I have SVG animation in CSS and seems it works or I should add it by window.onload in JS?

2021-12-19 11:41 UTC, DrSmile444 commented
> I have SVG animation in CSS and seems it works or I should add it by window.onload in JS?

Oh, I fount the animation, my bad, sorry). I just thought it would be like loader, but not a problem.

> As for BEM classes: I write 2 classes when I want to make a block from the element: "page__section section" to use further "section__title", "section__content". In this case I have to remove one of them?

I got the point. So let's keep it as it is.

PS: Still, responsive for iPad looks bad. Could you double-check it, please?

![image](https://user-images.githubusercontent.com/33941060/146673587-5c958716-1c26-4808-b2e5-eca6a5f59cfb.png)

2021-12-19 18:07 UTC, DrSmile444 requested changes
Almost great!
But you forgot to fix the header. Review the whole page and fix other bugs, if any.

![image](https://user-images.githubusercontent.com/33941060/146685805-ff38a6ce-a25f-4043-9c5d-16668f390815.png)

2021-12-21 07:18 UTC, DrSmile444 approved these changes
Great job! Thank you!

2021-12-21 07:21 UTC, merged