10 components
MastersAcademy/frontend-course-2021 pull request #253
Opened 2021-12-20 10:05 UTC by DmitriyKondaurov

2021-12-21 09:21 UTC, MZabolotnev requested changes
А зачем сервис с подключением шрифтов?

2022-01-08 10:20 UTC, DmitriyKondaurov commented
@MZabolotnev I'v done, can you review please.

2022-01-10 15:52 UTC, MZabolotnev approved these changes

2022-01-10 15:52 UTC, MZabolotnev commented on homeworks/dmytro.kondaurov_DmitriyKondaurov/10-components/tic-tac-toe/src/app/app.component.ts
> +            [0, 0, 0],
В чем смысл хранить в коде два одинаковых массива? Вынеси в констатнту

2022-01-10 17:05 UTC, merged