10-components
MastersAcademy/frontend-course-2021 pull request #254
Opened 2021-12-20 12:40 UTC by 20-Igorek-21

2021-12-20 14:01 UTC, 20-Igorek-21 commented
https://20-igorek-21.github.io/frontend-course-2021/homeworks/ihor.kropyvnyi_20-Igorek-21/10-components/game-10-components/dist/game-10-components/

2021-12-21 08:40 UTC, MZabolotnev requested changes

2021-12-21 08:40 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/10-components/game-10-components/src/app/app.component.ts
> +
Ты манипулируешь с узлами DOM в ручном режиме. Фреймворк мы используем как раз для того что бы этого не делать. Никаких ручных манипуляций в дз не должно быть - используй интерполяцию и связывание .

2021-12-21 08:40 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/10-components/game-10-components/src/app/app.component.ts
> +  onClick(event: Event) {
Ты передаешь вверх компоненту - родителю узел DOM дочернего и вручную меняешь в нем что-то. Намного более логично будет передавать наверх только индекс - а состоянием управлять из родительского компонента. Никаких манипуляций DOM вручную быть не должно.

2021-12-23 13:54 UTC, MZabolotnev requested changes

2021-12-23 13:54 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/10-components/game-10-components/src/app/components/player-actions/player-actions.component.ts
> +  @Input() squares : any;
тип any - плохо

2021-12-23 13:54 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/10-components/game-10-components/src/app/app.component.ts
> +      setTimeout(() => {
Зачем тут  setTimeout ?

2022-01-10 15:51 UTC, merged