11 directives
MastersAcademy/frontend-course-2021 pull request #261
Opened 2022-01-15 00:31 UTC by 20-Igorek-21

2022-01-15 00:32 UTC, 20-Igorek-21 commented
https://20-igorek-21.github.io/frontend-course-2021//homeworks/ihor.kropyvnyi_20-Igorek-21/11-directives/dist/11-directives/

2022-01-16 14:31 UTC, MZabolotnev commented
Верхнего отступа нет, не очень красиво

2022-01-16 14:31 UTC, MZabolotnev requested changes

2022-01-16 14:31 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/11-directives/src/app/services/get-recipes.service.ts
> +              delay(3000)
А зачем delay?)

2022-01-16 14:31 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/11-directives/src/app/pipes/filter-ingredients.pipe.ts
> +    transform(value: any): IngredientModel[] {
А почему тут any? У тебя же есть интерфейс который описывает все данные, вынеси его часть в отдельный интерфейс

2022-01-16 14:31 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/11-directives/src/app/models/recipes.model.ts
> +        amount: {
`        amount: {
          unit: string,
          value: number
        },`
Повторяется много раз. Вынеси в отдельный интерфейс

2022-01-16 14:31 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/11-directives/src/app/models/array-ingredientsModel.ts
> +    hops:{
А что будет если количество элементов в hops в ответе поменяется? попробуй сделать что то типа:
`[key: number]: IHope`

2022-01-16 14:31 UTC, MZabolotnev commented on homeworks/ihor.kropyvnyi_20-Igorek-21/11-directives/src/app/components/cards/cards.component.ts
> +  isLoader = false;
Можно isLoader = true сделать еще при обьявлении, и тогда в ngOnInit тебе вообще не надо будет this.isLoader = true;

2022-01-17 18:10 UTC, MZabolotnev approved these changes

2022-01-18 07:12 UTC, merged