add homework 2-dom Turuta
MastersAcademy/frontend-course-2021 pull request #57
Opened 2021-10-27 06:51 UTC by turuta7

2021-10-29 23:40 UTC, turuta7 commented
Переписав майже весь js

2021-10-30 09:33 UTC, TArch64 requested changes

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    const clonedNode = templateEl.content.cloneNode(true);
сточатку потрібно зробити копію, а потім змінювати теги **копії**. Оригінальний темплейт ніколи не має змінюватися

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +        document.querySelector(`[data-number_message="${buttonDelete.dataset.button_delete}"]`).remove();
ти модеш просто передати сюди з метода `createMessage` меседж який ти додєш і тоді не потрібно буде шукати елементи по індексах

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    const buttonDelete = document.querySelector(`[data-button_delete="${i}"]`);
слова у атрибутах роздіяються `-`

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +const templateEl = document.querySelector('#template');
шукати елементи завжди потрібно за дата атрибутами

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +const createMessageDiv = document.querySelector('[data-container-messages]');
`createMessageDiv` це назва фукнції що створює дів для меседжа. А тут більш правильно буде назвати `messageListEl`

1. Назва повина відображати суть того що зберігається
2. Додавай до всіх зміних де лежать елементи дому закінчення `El`

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    if (!textValueMessage.value) return;
Якщо немає текста для месежа то навіть і не викликай цю функцію. Такі перевірки краще робити за межами функції

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    const clonedNode = templateEl.content.cloneNode(true);
```js
const messageTemplateEl = document.querySelector('[data-message-template]');


const messageEl = messageTemplateEl.content.cloneNode(true);

messageEl.querySelector('[data-message-text]').textContent = text;
messageEl.querySelector('[data-button-delete-message]').addEventListener(() => removeMessage(messageEl));

messageListEl.appendChild(messageEl);
```

2021-10-30 09:33 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +//     textareaEl.value = '';
видаляй коментарений код

2021-10-30 15:00 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    if (!textValueMessage.value) return;
ок

2021-10-30 15:00 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +//     textareaEl.value = '';
видалив

2021-10-30 15:01 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +const createMessageDiv = document.querySelector('[data-container-messages]');
добавив

2021-10-30 15:01 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +const templateEl = document.querySelector('#template');
ок

2021-10-30 15:01 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    const buttonDelete = document.querySelector(`[data-button_delete="${i}"]`);
ок

2021-10-30 15:01 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +        document.querySelector(`[data-number_message="${buttonDelete.dataset.button_delete}"]`).remove();
зробив

2021-10-30 15:01 UTC, turuta7 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    const clonedNode = templateEl.content.cloneNode(true);
ок

2021-10-30 15:12 UTC, TArch64 requested changes

2021-10-30 15:12 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +        document.querySelector(`[data-number-message="${buttonDeleteMessage.dataset.buttonDelete}"]`).remove();
А ти хіба не можеш тут викликати в `buttonDeleteMessage` метод `remove`? Тобі точно ще раз потрібно шукати елемент в домі?

2021-10-30 15:12 UTC, TArch64 commented on homeworks/Aleksandr.Turuta_turuta7/2-dom/script.js
> +    const messageTemplateEl = document.querySelector('[data-message-template]').content;
Це можна зробити один раз за межами функції. Темплейт завжди в домі один і він не змінюється

2021-10-30 17:19 UTC, TArch64 approved these changes

2021-10-30 17:24 UTC, merged