homework without *
MastersAcademy/frontend-course-2021 pull request #62
Opened 2021-10-27 18:57 UTC by AndriiMorozov88

2021-10-30 09:42 UTC, TArch64 commented
@AndriiMorozov88 Розберися з файлими домашки. У тебе чомусь тут 2 папки додано. Повидаляй все що не потрібно

2021-10-30 15:20 UTC, TArch64 requested changes

2021-10-30 15:20 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/style.css
> +h1 {
Не використовуй стилі на теги (body це окей, а всі інші ні)

2021-10-30 15:20 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/script.js
> +    document.querySelector('input[type=text]').value = '';
додай дата атрибут для текстовго філда

2021-10-30 15:20 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/script.js
> +const mainChat = document.querySelector('.chat__body');
використовуй дата атрибути для пошуку елементів в домі

2021-10-30 15:20 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/script.js
> +document.onkeydown = function (e) {
використовуй `addEventListener` замість onkeydown, onclick etc

2021-10-30 15:20 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/script.js
> +    if (e.keyCode === 13) {
keyCode деприкейчений і його використовувати не можна. Заміни на key

2021-10-30 15:20 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/script.js
> +    const message = document.querySelector('.message__input');
більш правильно буде назвати цю змінну `messageTextField` бо це не меседж, а поле в яке вводять меседж. Також додавай до всіх зміних де лежать елементи дому закінчення `El`

2021-10-30 15:20 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/script.js
> +    chatMessage.className = 'chat__message';
Створюй елементи месседжа через темплейт

2021-10-30 15:22 UTC, TArch64 commented on homeworks/Andrii.Morozov_AndriiMorozov88/2 - DOM/index.html
> +        <button id="btn">Send</button>
оберни текстовий філд та кнопку форму та зроби додавання меседжа через івенти форми (submit). Це буде більш семантично правильно + у браузерів є своя логіка для форми яку ти зараз реалізуєш сам

2021-10-30 15:23 UTC, MZabolotnev requested changes
Нужно убрать возможность отправлять пустые сообщения

2021-11-01 08:52 UTC, MZabolotnev approved these changes

2021-11-01 16:52 UTC, merged