2 dom
MastersAcademy/frontend-course-2021 pull request #75
Opened 2021-10-29 09:24 UTC by VladislavMedvedyev

2021-10-30 09:50 UTC, TArch64 requested changes

2021-10-30 09:50 UTC, TArch64 commented on package.json
>          "@types/faker": "^5.5.8",
Відміни зміни у package.json та package-lock.json

2021-10-31 09:31 UTC, TArch64 commented
@VladislavMedvedyev ping-ping

2021-10-31 10:06 UTC, VladislavMedvedyev commented on package.json
>          "@types/faker": "^5.5.8",
Відмінив зміни. Взяв код цих двой файлів з репозиторію MastersAcademy:main

2021-10-31 14:01 UTC, TArch64 requested changes

2021-10-31 14:01 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  width: 500px;
Страйся не використовувати фіксовані значення для width та height. Якщо є можливіть то це має бути динамічний розмір `%`. Якщо тобі потрібно робити обмеження по ширині чи висоті є `max-width` та `max-height`

2021-10-31 14:18 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +/* eslint-disable linebreak-style */
Виправив, довго шукав як пофіксити ці помилки, а виявилось, що потрібно банально змінити End of line з CRLF на LF =)

2021-10-31 14:19 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +function messageSend() {
Не впевнений.

2021-10-31 14:20 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +/* eslint-disable linebreak-style */
Соррі, не побачив коментарі нижче. Пішов виправляти.

2021-10-31 17:14 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +});
Виправив

2021-10-31 17:15 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +        document.querySelector('.input').value = '';
Змінну input видалив, перестала бути необхідна

2021-10-31 17:15 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +    if (message.length === 0) {
Виправив

2021-10-31 17:16 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +        createP.className = 'message';
Це обов'язково? Чи це порада на майбутнє? Я поки не зрозумів, як через цей тег зробити. Якщо обов'язково - буду розбиратись

2021-10-31 17:16 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +function messageSend() {
Виправив

2021-10-31 17:17 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +const input = document.querySelector('.input');
Виправив

2021-10-31 17:17 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +const input = document.querySelector('.input');
Виправив

2021-10-31 17:17 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  background-color: #9ACD32;
Виправив

2021-10-31 17:17 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  margin: 20px;
Можна приклад, не зовсім зрозумів

2021-10-31 17:18 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  width: 500px;
Можливо знаєш якийсь сайт, де розписані марджіни та піддінги? Я пробував виправити, але вже заплутався в процентах

2021-11-01 11:12 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  width: 500px;
Маржіни та падінги в пікселях це ок. Це якраз було `width` та `height` у пікселях

2021-11-01 11:14 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  margin: 20px;
Замість
```html
<ul>
  <li style="margin: 20px"></li>
  <li style="margin: 20px"></li>
  <li style="margin: 20px"></li>
  <li style="margin: 20px"></li>
</ul>
```
має бути отак
```html
<ul>
  <li style="margin-bottom: 20px"></li>
  <li style="margin-bottom: 20px"></li>
  <li style="margin-bottom: 20px"></li>
  <li></li>
</ul>
```
margin дає відступ у всі сторони і вони накладаються один на один. Такого краще уникати і робити так щоб відступи були в одну сторону (всі маржіни внизу)

2021-11-01 11:15 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +        createP.className = 'message';
Краще зробити через нього. Приклад

```html
<template data-post-template>
  <article>
    <h2 data-post-title></h2>
    <img data-post-img>
  </article>
</template>
```

```js
const postListEl = document.querySelector('[data-post-list]');
const postTemplateEl = document.querySelector('[data-post-template]');

// Add new post
const postEl = postTemplateEl.content.cloneNode(true); // clone node first

// Make change to cloned node
postEl.querySelector('[data-post-title]').textContent = 'some title';
postEl.querySelector('[data-post-img]').src = 'https://some/url/to/img';

// Add post
postListEl.appendChild(postEl);
```

2021-11-01 12:24 UTC, TArch64 requested changes

2021-11-01 12:24 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/index.html
> +            <button class="send" data-send>send</button>
кнопка має бути всередині форми з `type="submit"` тоді ти можеш прибрати `click` лістенер з кнопки бо по кліку на кнопку буде відбуватися івент сабміта

2021-11-01 12:26 UTC, TArch64 commented
@VladislavMedvedyev  ping-ping

2021-11-01 13:06 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/index.html
> +            <button class="send" data-send>send</button>
Я наче ж помістив input в форму. click лістенер у мене використовується лише для елемента button. Можливо я не так тебе зрозумів.

2021-11-01 14:07 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +        createP.className = 'message';
Намагаюсь переробити через template по цьому прикладу. А що значить атрибут data-post-list? Він же в HTML не заданий

2021-11-01 14:52 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/script.js
> +        createP.className = 'message';
Зробив через Template

2021-11-01 14:53 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  margin: 20px;
Виправив, якщо правильно зрозумів

2021-11-01 14:54 UTC, VladislavMedvedyev commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  width: 500px;
Змінив фіксовані значення на % всюди, крім ".container". Як не намагався - дизай ламається.

2021-11-01 17:10 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/index.html
> +            <button class="send" data-send>send</button>
Угу. Я описав. Потім пошукай як працює сабміт у форм. Батон теж має бути всередині тега форми і тоді не потрібен лістенер кліка на кнопці бо кнопка буде трігерити сабміт івент форми

2021-11-01 17:15 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/style.css
> +  width: 500px;
Хай буде так. Але в майбутньому старайся не робити так. Бо така стилізація не буде нормально працювати на різних девайсах

2021-11-01 17:16 UTC, TArch64 commented on homeworks/vladyslav.medvediev_VladislavMedvedyev/2-dom/index.html
> +            <button class="send" data-send>send</button>
Зроби цю кнопочку не через клік а через сабміт і я прийму домашку. Це буде останній коммнент

2021-11-01 18:37 UTC, TArch64 approved these changes

2021-11-01 18:39 UTC, merged