2 dom
MastersAcademy/frontend-course-2021 pull request #77
Opened 2021-10-29 10:18 UTC by ConstantinRusenko

2021-11-01 09:17 UTC, Chebutalio requested changes

2021-11-01 10:36 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.html
> +        <section class="main__message-window" data-message-window>
В задние не описано что нужно использовать form и отправлять через submit. Можно конечно через  form, если эта форма будет использоваться в дальнейших дз. Но так как в этом дз не было это указано, то я сделал через section. Если есть критическая необходимость, то я могу изменить на form. Буду благодарен узнать нужно ли вносить изменения.

2021-11-01 10:49 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.js
> +    if (keyCode === 13 && !e.shiftKey) {
Resolved

2021-11-01 11:21 UTC, Chebutalio commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.html
> +        <section class="main__message-window" data-message-window>
В завданні багато чого не написано. Через форму буде правильно, тому я й написав. Це не критична помилка, але на майбутнє точно варто врахувати.

2021-11-01 11:29 UTC, Chebutalio commented
Дуже дивно якось працює твоя домашка. По кліку на поле чату воно зникає і більше повідомлення не з'являються, як і саме поле.

2021-11-01 13:34 UTC, NickCashFlow requested changes

2021-11-01 13:34 UTC, NickCashFlow commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.js
> +messageWindow.addEventListener('click', (event) => {
это не верная интерпретация задания со звёздочкой
нужно чтобы у каждого сообщения был свой крестик, при клике на который это сообщение удалялось, а при клике на поле со всеми сообщениями удалялось это поле

2021-11-01 13:34 UTC, NickCashFlow commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.js
> +    newMessage.classList.add('new-message');
вот здесь сообщения не [дооформленные](https://prnt.sc/1y25sww), вёрстка являеться важной частью фронтенда

2021-11-01 18:21 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.js
> +messageWindow.addEventListener('click', (event) => {
![image](https://user-images.githubusercontent.com/30158130/139720478-f2414deb-3b20-45b0-81cf-5337df7c958e.png)
"а при клике на поле со всеми сообщениями удалялось это поле" не увидел такого в задании.
Добавил крестик для каждого сообщения.

2021-11-01 18:38 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.js
> +    newMessage.classList.add('new-message');
Доработал, в дальнейшем буду обращать на это больше внимания.

2021-11-01 21:24 UTC, ConstantinRusenko commented on homeworks/konstantin.rusenko_ConstantinRusenko/2-dom/index.html
> +        <section class="main__message-window" data-message-window>
Понял, спасибо.

2021-11-02 07:12 UTC, Chebutalio approved these changes

2021-11-02 07:16 UTC, merged