2-dom
MastersAcademy/frontend-course-2021 pull request #82
Opened 2021-10-29 11:53 UTC by skyprog

2021-10-29 18:20 UTC, skyprog commented
Ура! Виправив

2021-10-30 10:21 UTC, TArch64 requested changes

2021-10-30 10:21 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/index.html
> +        <section class="chat_messages" data-all_messages>
В html слова в атрибутах роздіяються `-`

2021-10-30 10:21 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/index.html
> +        <section class="char_bottom">
```suggestion
        <section class="chat_bottom">
```

2021-10-30 10:21 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/index.html
> +                <input type='submit' class='chat-form_submit' data-text_submit value='Send'>
Зроби кнопку через тег `<button>`

2021-10-30 10:21 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    closeMessage.className = 'close_message';
Використай тег `<template>` для створення меседжа. І старайся не змінювати елемент який щойдо додав в дом. Краще зроби спочатку всі потрібні зміни а потім додавай елемент. Кожен раз коли ти взаємодієш з домом браузер відповідно реагує та оновлює сторінку

2021-10-30 10:21 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    closeMessage.className = 'close_message';
```html
<template data-post-template>
  <article>
    <h2 data-post-title></h2>
    <img data-post-img>
  </article>
</template>
```

```js
const postListEl = document.querySelector('[data-post-list]');
const postTemplateEl = document.querySelector('[data-post-template]');

// Add new post
const postEl = postTemplateEl.content.cloneNode(true); // clone node first

// Make change to cloned node
postEl.querySelector('[data-post-title]').textContent = 'some title';
postEl.querySelector('[data-post-img]').src = 'https://some/url/to/img';

// Add post
postListEl.appendChild(postEl);
```

2021-10-30 10:21 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    chatMessages.scrollTop = 9999;
краще використовуй для цього висоту контента. Хто зна скільки там буде меседжів) `chatMessages.scrollHeight`

2021-10-30 10:21 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/style.css
> +  margin-top: -1px;
Намагайся уникати відʼємних відступів

2021-10-31 08:40 UTC, skyprog commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    closeMessage.className = 'close_message';
Використав  <template>, але тепер не робить кнопка видалення closeMessage, не знаю в чому причина

2021-10-31 08:40 UTC, skyprog commented on homeworks/roman.kushnirenko_skyprog/2-dom/style.css
> +  margin-top: -1px;
Тут окрім відʼємного відступу - нічого не працює

2021-10-31 09:04 UTC, TArch64 requested changes

2021-10-31 09:04 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +const closeMessage = template.content.querySelector('[data-close-message]');
Порядок роботи з темплейтом такий що ти завжди спочатку робиш `content.cloneNode(true)` а потім змінюєш значення в копії твого темплейта і це потрібно робити всередині функції `createMessage` щоб кожен меседж був окремим js обʼєктом

2021-10-31 09:04 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    chatMessageContent.innerHTML = messageInput;
використовуй `textContent` замість `innerHTML`. Остнанній має проблеми з секюріті якщо в контент йде з контролів від юзера. Почитай що таке XSS

2021-10-31 09:04 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    chatMessageContent.innerHTML = messageInput;
`innerHTML` має використовуватися тільки в тому випадку якщо ти точно впевнений в тому що тобі потрібно вставляти html як контент та в тому що там всередині контенту

2021-10-31 09:04 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    chatMessageContent.innerHTML = messageInput;
Наприклад якщо відправити у твій меседж `<script>alert('hello to XSS attacks')</script>` то побачиш магію)

2021-10-31 09:04 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/style.css
> +  position: absolute;
Старайся уникати абсолютного позиціювання. За можливості використовуй статичні елементи

2021-10-31 09:05 UTC, TArch64 commented
В комміт меседжах описуй зміни що ти зробив. Це потрібно для того щоб в майбутньому мати можливість зрозуміти що за зміни були зроблеми в конкретному коммітові

2021-11-01 10:15 UTC, skyprog commented
1. Скажіть, будь ласка, чому не робить кнопка видалення closeMessage? Без <template> вона робила. 
Та й взагалі все робило до виправлень)
2. Після заміни innerHTML на textContent - не робить replace(/\n/g, '<br/>') для перенесення на інший рядок

2021-11-01 11:20 UTC, TArch64 commented
> 1. Скажіть, будь ласка, чому не робить кнопка видалення closeMessage? Без  вона робила.
>    Та й взагалі все робило до виправлень)
> 2. Після заміни innerHTML на textContent - не робить `replace(/\n/g, '<br/>') `для перенесення на інший рядок

1. Бо `template.content.cloneNode(true)` повертає не елемент а `DocumentFragment` і `removeChild` не дуже коректено з ним працює. Потрібно додати firstElementChild після нього.

```js
const messageShow = template.content.cloneNode(true).firstElementChild;
```
Також потрібно пофіксити ось ці селектори
```js
const containerM = template.content.querySelector('[data-container]');
const chatMessageContent = template.content.querySelector('[data-message-content]');
const closeMessage = template.content.querySelector('[data-close-message]');
```

бо в темплейта не можна шукати та змінювати елементи. Це потрібно робити в `messageShow`


2. Так і має бути. Додавай перенос рядка через символ переносу рядка. `<br/>` це html тег і він не працює з textContent

2021-11-01 14:19 UTC, TArch64 approved these changes

2021-11-01 14:19 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/index.html
> +                <button type='submit' class='chat-form_submit' data-text-submit>Send</button>
немає закриваючого тега `form`

2021-11-01 14:19 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    if (!chatFormInput.value == '') {
```suggestion
    if (!chatFormInput.value === '') {
```

2021-11-01 14:19 UTC, TArch64 commented on homeworks/roman.kushnirenko_skyprog/2-dom/js.js
> +    });
```suggestion
    closeMessage.addEventListener('click', () => messageShow.remove());
```

2021-11-01 14:20 UTC, merged