2 dom
MastersAcademy/frontend-course-2021 pull request #84
Opened 2021-10-29 12:36 UTC by Nikkarchinskiy

2021-10-31 09:30 UTC, TArch64 commented
@Nikkarchinskiy  Тут помилки падають в лінтерах, пофікси їх

2021-11-01 12:30 UTC, TArch64 commented
@Nikkarchinskiy ping-ping

2021-11-01 17:11 UTC, NickCashFlow requested changes

2021-11-01 17:11 UTC, NickCashFlow commented on homeworks/nikita.karchinskiy_Nikkarchinskiy/2-dom/index.js
> +        input.value = '';
этот кусок кода лучше вынести в отдельную функцию и вызывать в каждом колбеке

2021-11-01 19:31 UTC, NickCashFlow submitted a review, later dismissed

2021-11-01 20:28 UTC, NickCashFlow approved these changes

2021-11-01 20:29 UTC, merged