2 dom
MastersAcademy/frontend-course-2021 pull request #89
Opened 2021-10-29 14:00 UTC by vtanaschuk

2021-10-30 10:33 UTC, TArch64 requested changes

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +            // span.setAttribute('onclick', 'removeElement(this)');
видаляй коментарений код

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +    for (let i = 0; i < myNodeList.length; i++) {
що робить ця функція?

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/index.html
> +    <input type="search" class="message-input-block-input" placeholder="enter your message" data-message-input>
оберни інпут та кнопку в тег форми та слухай в неї івент `submit`

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/index.html
> +    <span class="addBtn" data-message-input-btn>Add</span>
Всі кнопки мають робитися через тег `button`

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/index.html
> +
видали зайві переноси рядків

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +const inputBnt = document.querySelector('[data-message-input-btn]');
додавай до зміних в яких лежить елемент дому закінчення `El`

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +        const text = document.createTextNode(newMessage);
Використай тег `<template>` для створення меседжа

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +        const text = document.createTextNode(newMessage);
```html
<template data-post-template>
  <article>
    <h2 data-post-title></h2>
    <img data-post-img>
  </article>
</template>
```

```js
const postListEl = document.querySelector('[data-post-list]');
const postTemplateEl = document.querySelector('[data-post-template]');

// Add new post
const postEl = postTemplateEl.content.cloneNode(true); // clone node first

// Make change to cloned node
postEl.querySelector('[data-post-title]').textContent = 'some title';
postEl.querySelector('[data-post-img]').src = 'https://some/url/to/img';

// Add post
postListEl.appendChild(postEl);
```

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +    const list = document.querySelector('[data-message-otput]');
input та list збережи за межами цього колбеку. Тобі не потрібно шукати їх кожен раз при додаванні меседжа бо вони статичні на сторінці

2021-10-30 10:33 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/style.css
> +  float: right;
не використовуй `float` для позиціювання елементів на сторінці

2021-10-31 10:53 UTC, vtanaschuk commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +    for (let i = 0; i < myNodeList.length; i++) {
добавляє знак видалити в повідомленні

2021-10-31 10:58 UTC, vtanaschuk commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +            // span.setAttribute('onclick', 'removeElement(this)');
ок

2021-10-31 10:58 UTC, vtanaschuk commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/index.html
> +    <input type="search" class="message-input-block-input" placeholder="enter your message" data-message-input>
ок

2021-10-31 11:00 UTC, vtanaschuk commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/index.html
> +    <span class="addBtn" data-message-input-btn>Add</span>
ок

2021-10-31 11:01 UTC, vtanaschuk commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/index.html
> +
ок

2021-10-31 11:19 UTC, vtanaschuk commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +    const list = document.querySelector('[data-message-otput]');
ок

2021-10-31 11:28 UTC, vtanaschuk commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +const inputBnt = document.querySelector('[data-message-input-btn]');
ок

2021-10-31 17:17 UTC, TArch64 requested changes

2021-10-31 17:17 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/index.html
> +      <article class="message">
Ти впевнений в тому що тут має бути `article` та `<h2 data-post-title></h2>`?

2021-10-31 17:17 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +    const postTemplateEl = document.querySelector('[data-post-template]');
Приклад є прикладом тому що там показується можливе застосування яке ти мав би адаптувати а не копіпастити. Повиправляй назви та html до того що тут справді тобі потрібно

2021-10-31 17:17 UTC, TArch64 commented on homeworks/vasil.tanashchuk_vtanaschuk/2-dom/lib/script.js
> +    for (let i = 0; i < myNodeList.length; i++) {
А він десь використовується?

2021-11-01 12:26 UTC, TArch64 commented
@vtanaschuk ping-ping

2021-11-01 17:34 UTC, TArch64 approved these changes

2021-11-01 17:45 UTC, merged