2 dom
MastersAcademy/frontend-course-2021 pull request #94
Opened 2021-10-30 12:32 UTC by ErnestMk1

2021-10-30 12:38 UTC, TArch64 commented
https://github.com/MastersAcademy/frontend-course-2021/pull/90

2021-10-30 12:56 UTC, ErnestMk1 commented
> #90

так это же исправлено. Есть ещё что-то?

2021-10-30 12:57 UTC, TArch64 commented
> > #90
> 
> так это же исправлено. Есть ещё что-то?

Це щоб не загубився старий пулл реквест

2021-10-30 13:02 UTC, electrovladyslav requested changes

2021-10-30 13:02 UTC, electrovladyslav commented on homeworks/Ernest.Myrmyr_ErnestMk1/2-dom/script.js
> +messToFillEl.addEventListener('keypress', (e) => {
Ты молодец, что разметил этот блок формой. Это семантически верно. 
Теперь можно пойти дальше, и ловить не нажатия кнопок, а событие отправки формы. 
Плюс, тогда ты можешь добавить атрибут `required`  на поле ввода и пофильтровать этим пустые сообщения от отправки.

2021-11-01 15:21 UTC, electrovladyslav requested changes

2021-11-01 15:21 UTC, electrovladyslav commented on homeworks/Ernest.Myrmyr_ErnestMk1/2-dom/script.js
> +        e.preventDefault();
строки 7-11 и 16-20 идентичны. 
Есть такой принцип в программировании [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself)
Вынеси эти куски в функцию, и вызывай её в том, и другом случае

2021-11-01 15:21 UTC, electrovladyslav commented on homeworks/Ernest.Myrmyr_ErnestMk1/2-dom/script.js
> +        e.preventDefault();
Даже не так. 
Enter, который мы нажали в любом текстовом инпуте формы, вызывает событие submit для этой формы. 
Получается, тебе не надо обрабатывать отдельно нажатие на кнопку сабмит, и отдельно энтер в инпуте. Ведь и то и то вызывает самбит формы, которое ты уже обрабатываешь на строке 15. 
Получается, этот кусок (5-13) можно просто выбросить.

2021-11-01 15:21 UTC, electrovladyslav commented on homeworks/Ernest.Myrmyr_ErnestMk1/2-dom/styles.css
> +}
Этого файла не должно быть в твоём пулл-реквесте.

2021-11-01 16:14 UTC, electrovladyslav commented on package-lock.json
> -{
Я наверное неправильно выразился. 
**Изменений** этого файла не должно быть в твоём пулл-реквесте. 
То есть ты должен вернуть его к [состоянию](https://github.com/MastersAcademy/frontend-course-2021/blob/main/package-lock.json) мэйн репозитория

2021-11-01 16:20 UTC, ErnestMk1 commented on package-lock.json
> -{
этого сделать сегодня уже не смогу. Ставьте нолик. В след раз верну его в прежнее состояние)

2021-11-01 20:55 UTC, closed without merging