2-dom
MastersAcademy/frontend-course-2021 pull request #96
Opened 2021-10-31 13:29 UTC by SanSandru4

https://github.com/MastersAcademy/frontend-course-2021/pull/78

2021-10-31 13:31 UTC, SanSandru4 commented
Це той пул, що був скинутий вчасно - https://github.com/MastersAcademy/frontend-course-2021/pull/78

2021-11-01 07:33 UTC, NickCashFlow requested changes

2021-11-01 08:19 UTC, NickCashFlow requested changes
внесите пожалуйста изменения

2021-11-01 13:15 UTC, NickCashFlow requested changes
внесите изменения

2021-11-01 16:43 UTC, NickCashFlow requested changes

2021-11-01 16:43 UTC, NickCashFlow commented on homeworks/oleksandr.prylutskiy_SanSandru4/2-dom/index.html
> +        <div class="blockS-send">
лишняя буква S

2021-11-01 16:43 UTC, NickCashFlow commented on homeworks/oleksandr.prylutskiy_SanSandru4/2-dom/style.css
> +.basis, .messages, .btn-send, .message-box {
и оформи как-то свои сообщения, потому что не понятно, то сообщение одно или несколько http://i.imgur.com/aptBEws.png

2021-11-01 16:43 UTC, NickCashFlow commented on homeworks/oleksandr.prylutskiy_SanSandru4/2-dom/style.css
> +  position: relative;
position: relative; - здесь не играет никакую роль

2021-11-01 17:00 UTC, NickCashFlow requested changes

2021-11-01 17:00 UTC, NickCashFlow commented on homeworks/oleksandr.prylutskiy_SanSandru4/2-dom/script.js
> +const btnSub = document.querySelector('.btn-send');
для обращения с js к html-тегам лучше использовать дата-атрибуты

2021-11-01 19:27 UTC, NickCashFlow approved these changes

2021-11-01 19:30 UTC, merged